### PR TITLE
Eth66 protocol request id changes should only apply to the Eth protocol

### LINKED ISSUE #2682: Besu and Quorum peering fails with Eth65 subprotocol
The latest version of Besu (git b5113e715f6afdf01f7357453905423aa6d3488a) is failing to establish a peer with latest Quorum (git 44959d08568d22a6dd9ffa20271a3d0f7459dbbf) using eth65.

Error occurs when Besu sends a GetBlockHeadersData message to Quorum which Quorum fails to decode.

```
2021-08-27 10:18:24.373+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.402+00:00 | nioEventLoopGroup-3-3 | DEBUG | EthProtocolManager | Sending status message to Peer 0x2a3cd1b7c15b1fb666....
2021-08-27 10:18:24.373+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.402+00:00 | nioEventLoopGroup-3-3 | TRACE | AbstractPeerConnection | Writing org.hyperledger.besu.ethereum.eth.messages.StatusMessage@92a2d171 to PeerInfo{version=5, clientId='Geth/quorum/v1.9.24-stable-972809e3(quorum-v21.7.1)/linux-amd64/go1.15.5', capabilities=[eth/63, eth/64, eth/65, istanbul/64, istanbul/99, istanbul/100], port=0, nodeId=0x2a3cd1b7c15b1fb666f6815117e471bcfef7d847b0da3c10f1eccf4c0a9a1c96cdf405ff1ba4e0a4ffc782be34764e47e8aebeadc2dee16395a41df512c17844} via protocol eth/65
2021-08-27 10:18:24.374+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: TRACE[08-27|00:18:24.403|eth/downloader/downloader.go:310]                Registering sync peer                    peer=b746e9fe7c498e57
2021-08-27 10:18:24.374+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: DEBUG[08-27|00:18:24.403|eth/quorum_protocol.go:65]                       consensus subprotocol retrieved eth peer from peerset id=b746e9fe7c498e57 conn=staticdial       ethPeer.id=b746e9fe7c498e57 ProtoName=istanbul
2021-08-27 10:18:24.375+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.404+00:00 | nioEventLoopGroup-3-3 | TRACE | EthProtocolManager | Process message eth/65, 0
2021-08-27 10:18:24.376+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.404+00:00 | nioEventLoopGroup-3-3 | DEBUG | EthProtocolManager | Received status message from Peer 0x2a3cd1b7c15b1fb666...: org.hyperledger.besu.ethereum.eth.messages.StatusMessage@92a2d171
2021-08-27 10:18:24.376+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.405+00:00 | nioEventLoopGroup-3-3 | DEBUG | ChainHeadTracker | Requesting chain head info for Peer 0x2a3cd1b7c15b1fb666...
2021-08-27 10:18:24.377+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.406+00:00 | nioEventLoopGroup-3-3 | DEBUG | GetHeadersFromPeerByHashTask | Requesting 1 headers from peer Peer 0x2a3cd1b7c15b1fb666....
2021-08-27 10:18:24.377+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.406+00:00 | nioEventLoopGroup-3-3 | TRACE | AbstractPeerConnection | Writing RawMessage{code=3, data=0xe680e4a0aac4bda4c5ba587e5a1e08fe1bfc3a9f394cda1c899914d07524c86193c8ce3f018080} to PeerInfo{version=5, clientId='Geth/quorum/v1.9.24-stable-972809e3(quorum-v21.7.1)/linux-amd64/go1.15.5', capabilities=[eth/63, eth/64, eth/65, istanbul/64, istanbul/99, istanbul/100], port=0, nodeId=0x2a3cd1b7c15b1fb666f6815117e471bcfef7d847b0da3c10f1eccf4c0a9a1c96cdf405ff1ba4e0a4ffc782be34764e47e8aebeadc2dee16395a41df512c17844} via protocol eth/65
2021-08-27 10:18:24.378+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.407+00:00 | nioEventLoopGroup-3-3 | DEBUG | WaitForPeerTask | Finished waiting for peer connection.
2021-08-27 10:18:24.378+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.407+00:00 | nioEventLoopGroup-3-3 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
2021-08-27 10:18:24.379+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: DEBUG[08-27|00:18:24.408|eth/handler.go:418]                              Ethereum message handling failed         id=b746e9fe7c498e57 conn=staticdial       err="Invalid message - msg #3 (39 bytes): invalid message: (code 3) (size 39) rlp: expected input string or byte for uint64, decoding into (eth.getBlockHeadersData).Amount"
2021-08-27 10:18:24.379+10:00 | docker-java-stream-1453587586 | INFO  | Web3Provider | besu: 2021-08-27 00:18:24.408+00:00 | nioEventLoopGroup-3-3 | DEBUG | WaitForPeerTask | Waiting for new peer connection. 1 peers currently connected.
2021-08-27 10:18:24.379+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: DEBUG[08-27|00:18:24.408|eth/handler.go:254]                              Removing Ethereum peer                   peer=b746e9fe7c498e57
2021-08-27 10:18:24.379+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: TRACE[08-27|00:18:24.408|eth/downloader/downloader.go:331]                Unregistering sync peer                  peer=b746e9fe7c498e57
2021-08-27 10:18:24.379+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: TRACE[08-27|00:18:24.408|p2p/peer.go:399]                                 Protocol eth/65 failed                   id=b746e9fe7c498e57 conn=staticdial       err="Invalid message - msg #3 (39 bytes): invalid message: (code 3) (size 39) rlp: expected input string or byte for uint64, decoding into (eth.getBlockHeadersData).Amount"
2021-08-27 10:18:24.379+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: DEBUG[08-27|00:18:24.408|eth/quorum_protocol.go:92]                       Ethereum quorum message handling failed  id=b746e9fe7c498e57 conn=staticdial       err=EOF
```

This seems to be interesting part decoding the getBlockHeadersData struct
```
2021-08-27 10:18:24.379+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: TRACE[08-27|00:18:24.408|p2p/peer.go:399]                                 Protocol eth/65 failed                   id=b746e9fe7c498e57 conn=staticdial       err="Invalid message - msg #3 (39 bytes): invalid message: (code 3) (size 39) rlp: expected input string or byte for uint64, decoding into (eth.getBlockHeadersData).Amount"
2021-08-27 10:18:24.379+10:00 | docker-java-stream-733481287 | INFO  | Web3Provider | quorum: DEBUG[08-27|00:18:24.408|eth/quorum_protocol.go:92]                       Ethereum quorum message handling failed  id=b746e9fe7c498e57 conn=staticdial       err=EOF
```

### PR DESCRIPTION
**Pull request by jframe**
## PR description
Besu using the instanbul/99 or instanbul/100 incorrectly encodes messages with a requestId from eth66.

## Fixed Issue(s)

Fixes #2682

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by siladu** [comment]
I think we should also remove Capability.compareTo as it was only created for this comparison. 

I agree that doing this comparison in the client code is better: it's more explicit than the compareTo, which assumes you would know comparing Capabilities means comparing versions of the same Capability.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java [hunk 1]
```diff
@@ -108,7 +108,10 @@ public EthPeer(
 
     final boolean supportsRequestId =
         getAgreedCapabilities().stream()
-            .anyMatch(capability -> capability.compareTo(EthProtocol.ETH66) >= 0);
+            .anyMatch(
+                capability ->
+                    EthProtocol.NAME.equals(capability.getName())
+                        && capability.compareTo(EthProtocol.ETH66) >= 0);
```
Comment (siladu) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java:114]:
```suggestion
                        && capability.getVersion() >= EthProtocol.ETH66.getVersion());
```

Comment (jframe) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java]: I don't like this specific knowledge being in the EthPeers class. I've created a method in EthProtocol to do this. It will also make it easier to test this.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java [hunk 2]
```diff
@@ -169,4 +169,8 @@ public static EthProtocol get() {
     public static final int V65 = 65;
     public static final int V66 = 66;
   }
+
+  public static boolean isEth66Compatible(final Capability capability) {
+    return capability.getName().equals(NAME) && capability.getVersion() >= ETH66.getVersion();
```
Comment (usmansaleem) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java:174]: Would `Object.equals(capability.getName(), NAME)` would be safer, as you wouldn't have to do null checks?

**Review by usmansaleem — APPROVED** [review]
LGTM - minor suggestion.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java (hunk 2 above)
Comment (jframe) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java:174]: Changed to do ```NAME.equals(capability.getName())```

**Review by lucassaldanha — APPROVED** [review]
LGTM
