### PR TITLE
fix get proof issue for missing account

### LINKED ISSUE #8075: 【EIP-1186】Proofs for non existent values
In the process of using Besu, I found that the **_get_Proof_** interface returned an **_Account Not Found_** error when processing non existent accounts.
This seems to be inconsistent with the provisions of [EIP-1186](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1186.md):

> Proofs for non existent values
In case an address or storage-value does not exist, the proof needs to provide enough data to verify this fact. This means the client needs to follow the path from the root node and deliver until the last matching node. If the last matching node is a branch, the proof value in the node must be an empty one. In case of leaf-type, it must be pointing to a different relative-path in order to proof that the requested path does not exist.

I would like to know why Besu returns an error directly and what are the considerations for this design.
In addition, are there any plans to modify the implementation of the **_get_Proof_** interface for non existent accounts in the future?

If you see it, please answer my confusion, thank you very much~

### PR DESCRIPTION
**Pull request by matkt**
## PR description

Fix an issue in the eth_getProof RPC api when we are asking a proof for a missing account
fixes #8075 

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/proof/WorldStateProof.java [hunk 1]
```diff
@@ -39,12 +40,18 @@ public WorldStateProof(
       final PmtStateTrieAccountValue stateTrieAccountValue,
       final Proof<Bytes> accountProof,
       final SortedMap<UInt256, Proof<Bytes>> storageProofs) {
-    this.stateTrieAccountValue = stateTrieAccountValue;
+    this.stateTrieAccountValue = Optional.of(stateTrieAccountValue);
```
Comment (garyschulte) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/proof/WorldStateProof.java]: should this be Optional.ofNullable() ?

Comment (matkt) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/proof/WorldStateProof.java]: make sense I will change that
