### PR TITLE
Manage unexpected exceptions during block creation

### LINKED ISSUE #9167: MinerExecutor - Noisy Log Message when block building times out
# Description
When Besu interrupts block building task due to timeout logs a very long exception stack trace, this generates log noise without adding value because it is not the exceptional case.

## Current Behaviour

```
2025-09-10 16:29:21.803+00:00 | MinerExecutor | WARN  | BlockTransactionSelector | Interrupting the selection of transactions for block inclusion as it exceeds the maximum configured duration of 1800ms
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[?:?]
	at org.hyperledger.besu.ethereum.blockcreation.txselection.BlockTransactionSelector.timeLimitedSelection(BlockTransactionSelector.java:208) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.ethereum.blockcreation.txselection.BlockTransactionSelector.buildTransactionListForBlock(BlockTransactionSelector.java:180) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.selectTransactions(AbstractBlockCreator.java:399) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:236) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:146) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:128) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.mineBlock(BlockMiner.java:143) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.consensus.clique.blockcreation.CliqueBlockMiner.mineBlock(CliqueBlockMiner.java:73) ~[besu-consensus-clique-25.7.0-linea1.jar:25.7.0-linea1]
	at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.run(BlockMiner.java:83) ~[besu-ethereum-blockcreation-25.7.0-linea1.jar:25.7.0-linea1]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
``` 

## Expected Behaviour

```
2025-09-10 16:29:21.803+00:00 | MinerExecutor | WARN  | BlockTransactionSelector | Interrupting the selection of transactions for block inclusion as it exceeds the maximum configured duration of 1800ms
```

### PR DESCRIPTION
**Pull request by fab-10**
## PR description

Adding protection against unexpected runtime exceptions that could be triggered by plugins, or internally, during block creation.

These exceptions are treat like internal errors, because they should have been handled, so they represent bugs and for that reason are logged as error for high visibility, and to avoid possible a inconsistent state a rollback is forced, so that the selection can continue with a clean state.

## Fixed Issue(s)

fixes #9167

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java [hunk 1]
```diff
@@ -422,7 +419,14 @@ public TransactionSelectionResults evaluateTransactions(final List<Transaction>
...
   private TransactionSelectionResult evaluateTransaction(
       final PendingTransaction pendingTransaction) {
-    final var evaluationResult = evaluatePendingTransaction(pendingTransaction);
+
+    TransactionSelectionResult evaluationResult;
+    try {
+      evaluationResult = evaluatePendingTransaction(pendingTransaction);
+    } catch (Throwable t) {
+      LOG.error("Unhandled exception evaluating transaction {}", pendingTransaction, t);
+      evaluationResult = INTERNAL_ERROR;
```
Comment (macfarla) [inline ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java:446]: would it be helpful to maybe print stack trace to TRACE log here - would it have extra info?

File: acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/account/Accounts.java [hunk 2]
```diff
@@ -44,6 +49,10 @@ public Account getSecondaryBenefactor() {
     return richBenefactorTwo;
   }
 
+  public Account getThirdBenefactor() {
```
Comment (macfarla) [inline acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/account/Accounts.java:52]: this doesn't get used

File: CHANGELOG.md [hunk 3]
```diff
@@ -23,6 +23,7 @@
 - Configurable limit for how much time plugins are allowed take, to propose transactions, during block creation [#9184](https://github.com/hyperledger/besu/pull/9184)
 - Add Osaka, BPO1 and BPO2 fork times for holesky, hoodi and sepolia [#9196](https://github.com/hyperledger/besu/pull/9196/files)
 - Implement optional sender balance checks in the layered txpool [#9176](https://github.com/hyperledger/besu/pull/9176)
+- Manage unexpected exceptions during block creation [#9208](https://github.com/hyperledger/besu/pull/9208)
```
Comment (macfarla) [inline CHANGELOG.md]: needs moving out of 25.9.0

File: plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java [hunk 4]
```diff
@@ -156,6 +157,13 @@ public boolean penalize() {
   public static final TransactionSelectionResult BLOCK_OCCUPANCY_ABOVE_THRESHOLD =
       new TransactionSelectionResult(BaseStatus.BLOCK_OCCUPANCY_ABOVE_THRESHOLD);
 
+  /**
+   * There was an unhandled exception during the evaluation of the transaction. Ideally this should
+   * never happen, otherwise it means there is a bug somewhere.
```
Comment (macfarla) [inline plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java]:
```suggestion
   * If this occurs, it indicates there is a bug somewhere.
```

File: plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java [hunk 5]
```diff
@@ -156,6 +157,13 @@ public boolean penalize() {
   public static final TransactionSelectionResult BLOCK_OCCUPANCY_ABOVE_THRESHOLD =
       new TransactionSelectionResult(BaseStatus.BLOCK_OCCUPANCY_ABOVE_THRESHOLD);
 
+  /**
+   * There was an unhandled exception during the evaluation of the transaction. Ideally this should
```
Comment (macfarla) [inline plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionSelectionResult.java]:
```suggestion
   * There was an unhandled exception during the evaluation of the transaction. 
```

File: ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java (hunk 1 above)
Comment (fab-10) [reply ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/txselection/BlockTransactionSelector.java:446]: stack trace is already logged as part of the `LOG.error` statement

File: acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/account/Accounts.java (hunk 2 above)
Comment (fab-10) [reply acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/account/Accounts.java:52]: the method itself is not used, but `Accounts.GENESIS_ACCOUNT_THREE_PRIVATE_KEY` is, so for uniformity with the other 2 account I also added this method

File: CHANGELOG.md (hunk 3 above)
Comment (fab-10) [reply CHANGELOG.md]: done
