### PR TITLE
Backward sync - check we have peers before starting

### LINKED ISSUE #8072: Besu can't backward sync after a restart.
Some kind of race condition seems to be preventing a backward sync session from running with 0 peers. This happened on holesky, after a system restart.

```javascript
{"@timestamp":"2024-12-28T20:08:03,302","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
2024-12-28T20:08:03.312955761Z vert.x-worker-thread-0 WARN found 2 argument placeholders, but provided 3 for pattern `Unable to retrieve block {} from any peer, with {} peers available. Could be a reorged block. Waiting for the next block from t
he consensus client to try again.`
{"@timestamp":"2024-12-28T20:08:03,313","level":"WARN","thread":"vert.x-worker-thread-0","class":"BackwardSyncAlgorithm","message":"Unable to retrieve block 0x41b13c8b0dc2c17c84d9e5c309d865bf91c50aa1bacd570851df46b8728affb9 from any peer, with 0
 peers available. Could be a reorged block. Waiting for the next block from the consensus client to try again.","throwable":""}
{"@timestamp":"2024-12-28T20:08:03,313","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2024-12-28T20:25:50,995","level":"WARN","thread":"vert.x-worker-thread-0","class":"MergeCoordinator","message":"Internal error, backward sync completed but failed to import finalized block 0x1d7358ec1e6f38cad3fe71894de010c7110c03f
a2cbd287de1e2acb01586090e","throwable":""}
``` 

Restarting the consensus client (teku) did not help.
Restarting besu did fix it.

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
## PR description
Don't start backward sync if zero peers.
* change isReady check to ensure we have > 0 peers
* check isReady before first step of backward sync

## Fixed Issue(s)

Fixes #8072

Testing performed to verify this PR prevents the issue described in #8072
- nodes set up with frequent restarts to trigger frequent backward syncs 
- this PR prevents backward sync from starting before the node finds peers
- details in comments below

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Comment by macfarla** [comment]
Currently running an experiment to see if I can replicate to test this out 
* 4 nodes running besu + nimbus on this PR
* 2 nodes running commit d690980987839eaecaa0b382eae2bab9a1e710a6 ie main right before this PR
* all 6 are being restarted every 2h with a copy of the `nightly` jenkins job that updates & restarts the nightly nodes, which were showing the issue #8072 

Hypothesis being the 2 controls will experience the issue in #8072 and the 4 nodes running this PR will not.

**Comment by macfarla** [comment]
`zgrep -E "BackwardSyncAlgorithm|BackwardSyncContext" besu.log.1.gz`
control - you can see that backward sync frequently tries to start when the node still has zero peers
```

{"@timestamp":"2025-07-31T10:31:09,428","level":"INFO","thread":"ForkJoinPool.commonPool-worker-7","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 2069 blocks. Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T10:31:09,429","level":"INFO","thread":"ForkJoinPool.commonPool-worker-7","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T12:20:34,237","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T12:20:34,242","level":"WARN","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Unable to retrieve block 0xb7c22390a2721834f2c523133f0c8b48661ffdfde4654d198940524f9a1c567f from any peer, with 0 peers available. Could be a reorged block. Waiting for the next block from the consensus client to try again.","throwable":""}
{"@timestamp":"2025-07-31T12:20:34,242","level":"INFO","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T12:20:36,660","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T12:20:37,549","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23039043, target head 23039046). Peers: 2","throwable":""}
{"@timestamp":"2025-07-31T12:20:38,802","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 2","throwable":""}
{"@timestamp":"2025-07-31T12:20:38,803","level":"INFO","thread":"ForkJoinPool.commonPool-worker-7","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T14:20:20,631","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T14:20:20,637","level":"WARN","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Unable to retrieve block 0xea24168a53b8d49d32c1626ac050c2de9d94cbe25b55c809484037cb97c074b0 from any peer, with 0 peers available. Could be a reorged block. Waiting for the next block from the consensus client to try again.","throwable":""}
{"@timestamp":"2025-07-31T14:20:20,637","level":"INFO","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T14:20:24,907","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T14:20:28,216","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23039638, target head 23039641). Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T14:20:29,165","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 7","throwable":""}
{"@timestamp":"2025-07-31T14:20:29,165","level":"INFO","thread":"ForkJoinPool.commonPool-worker-5","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T16:20:13,970","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T16:20:13,977","level":"WARN","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Unable to retrieve block 0xa4f4e73e0e0ea0331590c601f5b6dd9e9db62c08e30be08c6728574e5ea4273b from any peer, with 0 peers available. Could be a reorged block. Waiting for the next block from the consensus client to try again.","throwable":""}
{"@timestamp":"2025-07-31T16:20:13,977","level":"INFO","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T16:20:25,647","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T16:20:30,044","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 20.00% completed, imported 1 blocks of at least 5 (current head 23040234, target head 23040238). Peers: 4","throwable":""}
{"@timestamp":"2025-07-31T16:20:31,198","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 5 blocks. Peers: 4","throwable":""}
{"@timestamp":"2025-07-31T16:20:31,199","level":"INFO","thread":"ForkJoinPool.commonPool-worker-2","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T18:20:19,674","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T18:20:19,682","level":"WARN","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Unable to retrieve block 0x8a43c6361fdf24647f253242b95748c37671fa8c7b308a95af987b95f41759fe from any peer, with 0 peers available. Could be a reorged block. Waiting for the next block from the consensus client to try again.","throwable":""}
{"@timestamp":"2025-07-31T18:20:19,683","level":"INFO","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T18:20:24,616","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T18:20:30,473","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23040826, target head 23040829). Peers: 6","throwable":""}
{"@timestamp":"2025-07-31T18:20:31,452","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 7","throwable":""}
{"@timestamp":"2025-07-31T18:20:31,452","level":"INFO","thread":"ForkJoinPool.commonPool-worker-1","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T20:20:10,572","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T20:20:10,579","level":"WARN","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Unable to retrieve block 0xb0fea7cee7ff0352c12f34ac3adb15b3b85dd3824e9f383dc697e7ce6cf26825 from any peer, with 0 peers available. Could be a reorged block. Waiting for the next block from the consensus client to try again.","throwable":""}
{"@timestamp":"2025-07-31T20:20:10,579","level":"INFO","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T20:20:13,098","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T20:20:14,872","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23041421, target head 23041424). Peers: 2","throwable":""}
{"@timestamp":"2025-07-31T20:20:16,146","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 4","throwable":""}
{"@timestamp":"2025-07-31T20:20:16,147","level":"INFO","thread":"ForkJoinPool.commonPool-worker-4","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T22:20:15,494","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T22:20:15,505","level":"WARN","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Unable to retrieve block 0xcd6e21221d37a6e492782a9b083457878ef9d8df6031e2e455a1ecf28ca09c91 from any peer, with 0 peers available. Could be a reorged block. Waiting for the next block from the consensus client to try again.","throwable":""}
{"@timestamp":"2025-07-31T22:20:15,505","level":"INFO","thread":"EthScheduler-Workers-0","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T22:20:15,642","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T22:20:21,247","level":"INFO","thread":"ForkJoinPool.commonPool-worker-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23042014, target head 23042017). Peers: 3","throwable":""}
{"@timestamp":"2025-07-31T22:20:23,748","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 4","throwable":""}
{"@timestamp":"2025-07-31T22:20:23,749","level":"INFO","thread":"ForkJoinPool.commonPool-worker-4","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
```

**Comment by macfarla** [comment]
logs from node running this PR - backward sync does not start while node still has zero peers
```
zgrep -E "BackwardSyncAlgorithm|BackwardSyncContext" besu.log.1.gz
{"@timestamp":"2025-07-31T00:20:14,676","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T00:20:18,928","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23035470, target head 23035473). Peers: 4","throwable":""}
{"@timestamp":"2025-07-31T00:20:20,342","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 4","throwable":""}
{"@timestamp":"2025-07-31T00:20:20,343","level":"INFO","thread":"ForkJoinPool.commonPool-worker-6","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T02:20:26,361","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T02:20:30,834","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 20.00% completed, imported 1 blocks of at least 5 (current head 23036068, target head 23036072). Peers: 6","throwable":""}
{"@timestamp":"2025-07-31T02:20:32,026","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 5 blocks. Peers: 7","throwable":""}
{"@timestamp":"2025-07-31T02:20:32,027","level":"INFO","thread":"ForkJoinPool.commonPool-worker-1","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T04:20:24,938","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T04:20:28,238","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 20.00% completed, imported 1 blocks of at least 5 (current head 23036664, target head 23036668). Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T04:20:29,528","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 5 blocks. Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T04:20:29,528","level":"INFO","thread":"ForkJoinPool.commonPool-worker-6","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T06:20:24,029","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T06:20:27,229","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23037259, target head 23037262). Peers: 8","throwable":""}
{"@timestamp":"2025-07-31T06:20:28,964","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 8","throwable":""}
{"@timestamp":"2025-07-31T06:20:28,964","level":"INFO","thread":"ForkJoinPool.commonPool-worker-1","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T08:20:36,452","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T08:20:37,332","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 20.00% completed, imported 1 blocks of at least 5 (current head 23037854, target head 23037858). Peers: 4","throwable":""}
{"@timestamp":"2025-07-31T08:20:38,730","level":"INFO","thread":"ForkJoinPool.commonPool-worker-7","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 5 blocks. Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T08:20:38,731","level":"INFO","thread":"ForkJoinPool.commonPool-worker-7","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T09:42:02,984","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T09:42:13,072","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 12.45% completed, imported 32 blocks of at least 257 (current head 23038039, target head 23038264). Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:42:23,173","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 27.34% completed, imported 70 blocks of at least 256 (current head 23038077, target head 23038263). Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:42:33,700","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 41.25% completed, imported 106 blocks of at least 257 (current head 23038113, target head 23038264). Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:42:43,761","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 57.36% completed, imported 148 blocks of at least 258 (current head 23038155, target head 23038265). Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:42:53,811","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 70.27% completed, imported 182 blocks of at least 259 (current head 23038189, target head 23038266). Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:43:03,941","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 83.08% completed, imported 216 blocks of at least 260 (current head 23038223, target head 23038267). Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:43:14,397","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 97.71% completed, imported 256 blocks of at least 262 (current head 23038263, target head 23038269). Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:43:17,980","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 261 blocks. Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:43:18,147","level":"INFO","thread":"ForkJoinPool.commonPool-worker-28","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 262 blocks. Peers: 25","throwable":""}
{"@timestamp":"2025-07-31T09:43:18,148","level":"INFO","thread":"ForkJoinPool.commonPool-worker-28","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T10:20:25,138","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T10:20:34,083","level":"INFO","thread":"ForkJoinPool.commonPool-worker-7","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 20.00% completed, imported 1 blocks of at least 5 (current head 23038448, target head 23038452). Peers: 8","throwable":""}
{"@timestamp":"2025-07-31T10:20:35,689","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 5 blocks. Peers: 8","throwable":""}
{"@timestamp":"2025-07-31T10:20:36,067","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 6 blocks. Peers: 8","throwable":""}
{"@timestamp":"2025-07-31T10:20:36,067","level":"INFO","thread":"ForkJoinPool.commonPool-worker-4","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T10:21:26,879","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T10:21:34,663","level":"INFO","thread":"ForkJoinPool.commonPool-worker-2","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23038454, target head 23038457). Peers: 16","throwable":""}
{"@timestamp":"2025-07-31T10:21:35,633","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 16","throwable":""}
{"@timestamp":"2025-07-31T10:21:35,633","level":"INFO","thread":"ForkJoinPool.commonPool-worker-1","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T10:21:41,078","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T10:21:46,368","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 1 blocks. Peers: 18","throwable":""}
{"@timestamp":"2025-07-31T10:21:46,813","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 2 blocks. Peers: 18","throwable":""}
{"@timestamp":"2025-07-31T10:21:46,813","level":"INFO","thread":"ForkJoinPool.commonPool-worker-2","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T12:20:36,660","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T12:20:43,072","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23039043, target head 23039046). Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T12:20:44,199","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T12:20:44,200","level":"INFO","thread":"ForkJoinPool.commonPool-worker-2","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T14:20:24,891","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T14:20:28,440","level":"INFO","thread":"nioEventLoopGroup-3-7","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23039638, target head 23039641). Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T14:20:29,388","level":"INFO","thread":"nioEventLoopGroup-3-7","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 5","throwable":""}
{"@timestamp":"2025-07-31T14:20:29,388","level":"INFO","thread":"ForkJoinPool.commonPool-worker-4","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T16:20:25,611","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T16:20:26,273","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 20.00% completed, imported 1 blocks of at least 5 (current head 23040234, target head 23040238). Peers: 13","throwable":""}
{"@timestamp":"2025-07-31T16:20:27,487","level":"INFO","thread":"ForkJoinPool.commonPool-worker-6","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 5 blocks. Peers: 15","throwable":""}
{"@timestamp":"2025-07-31T16:20:27,487","level":"INFO","thread":"ForkJoinPool.commonPool-worker-6","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T18:20:24,704","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T18:20:26,669","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23040826, target head 23040829). Peers: 8","throwable":""}
{"@timestamp":"2025-07-31T18:20:27,677","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 9","throwable":""}
{"@timestamp":"2025-07-31T18:20:27,678","level":"INFO","thread":"ForkJoinPool.commonPool-worker-3","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T20:20:13,117","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T20:20:14,956","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23041421, target head 23041424). Peers: 2","throwable":""}
{"@timestamp":"2025-07-31T20:20:16,168","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 2","throwable":""}
{"@timestamp":"2025-07-31T20:20:16,180","level":"INFO","thread":"ForkJoinPool.commonPool-worker-2","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
{"@timestamp":"2025-07-31T22:20:24,652","level":"INFO","thread":"vert.x-worker-thread-0","class":"BackwardSyncContext","message":"Starting a new backward sync session","throwable":""}
{"@timestamp":"2025-07-31T22:20:29,177","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2, 25.00% completed, imported 1 blocks of at least 4 (current head 23042015, target head 23042018). Peers: 9","throwable":""}
{"@timestamp":"2025-07-31T22:20:30,542","level":"INFO","thread":"nioEventLoopGroup-3-8","class":"BackwardSyncContext","message":"Backward sync phase 2 of 2 completed, imported a total of 4 blocks. Peers: 7","throwable":""}
{"@timestamp":"2025-07-31T22:20:30,543","level":"INFO","thread":"ForkJoinPool.commonPool-worker-7","class":"BackwardSyncAlgorithm","message":"Current backward sync session is done","throwable":""}
```

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgSpecTest.java [hunk 1]
```diff
@@ -210,6 +210,7 @@ public void shouldSyncWhenThereIsUnprocessedHash() {
     backwardChain.addNewHash(hash);
     doReturn(CompletableFuture.completedFuture(null)).when(algorithm).executeSyncStep(hash);
 
+    doReturn(true).when(context).isReady();
```
Comment (pinges) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgSpecTest.java:213]: You haven't got a test case for when we have 0 peers.

Comment (macfarla) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgSpecTest.java:213]: added to BackwardSyncContextTest.

**Review by pinges — APPROVED** [review]
LGTM
