### PR TITLE
4169 dont recurse

### LINKED ISSUE #4169: StackOverflow on recursive call to MergeCoordinator.isDecendantOf()
Kiln is now old enough (over 200k blocks since TTD) that the recursive nature of this method will blow stack:

> issue on Kiln with ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_forkchoiceUpdatedV1. what could be the cause? the Besu node is connected to a lighthouse beacon. logs in the thread.

>   at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.isDescendantOf(MergeCoordinator.java:536)                                                                                         ││ 2022-07-22 14:16:23.052+00:00 | vert.x-eventloop-thread-2 | ERROR | ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_forkchoiceUpdatedV1                                                │
│ java.lang.StackOverflowError                                                                                                                                                                                 ││     at org.hyperledger.besu.ethereum.rlp.RLPEncodingHelpers.isSingleRLPByte(RLPEncodingHelpers.java:28)                                                                                                      │
│     at ....
 
Method needs to be refactored into a non-recursive pattern, since the distance from TTD will only increase as long as the network is alive.

### PR DESCRIPTION
**Pull request by jflo**
## PR description

Replaces recursive implementation of isDescendentOf with a loop.

## Fixed Issue(s)
fixes #4169 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [X] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

File: consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java [hunk 1]
```diff
@@ -530,17 +530,24 @@ public boolean isDescendantOf(final BlockHeader ancestorBlock, final BlockHeader
         newBlock.getNumber(),
         newBlock.getBlockHash());
 
-    if (ancestorBlock.getBlockHash().equals(newBlock.getHash())) {
+    Optional<BlockHeader> parentOf =
```
Comment (garyschulte) [inline consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java:533]: because this is a public method that gets called from fcU, we need to check whether ancestorblock == newBlock, OR we can just start with newBlock instead of its parent.. i.e. parentBlock = Optional.of(newBlock), and then loop

**Review by garyschulte — CHANGES_REQUESTED** [review]
LGTM, but we need to account for ancestor == newBlock

File: consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java [hunk 2]
```diff
@@ -530,17 +530,24 @@ public boolean isDescendantOf(final BlockHeader ancestorBlock, final BlockHeader
...
-    if (ancestorBlock.getBlockHash().equals(newBlock.getHash())) {
+    // start with self, because descending from yourself is valid
+    Optional<BlockHeader> parentOf = Optional.of(newBlock);
+
+    while (parentOf.isPresent()
+        && !parentOf.get().getBlockHash().equals(ancestorBlock.getBlockHash())) {
+      parentOf = protocolContext.getBlockchain().getBlockHeader(parentOf.get().getParentHash());
+    }
+
+    if (parentOf.isPresent()
```
Comment (garyschulte) [inline consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java:541]: I think we can add one extra comparison here and short circuit unrelated forks: check that parentOf.getNumber() is not < ancestor.  That way we don't run all the way back to genesis if we are comparing hashes of blocks on 2 different forks

**Review by garyschulte — CHANGES_REQUESTED** [review]

File: consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java [hunk 3]
```diff
@@ -530,17 +530,24 @@ public boolean isDescendantOf(final BlockHeader ancestorBlock, final BlockHeader
         newBlock.getNumber(),
         newBlock.getBlockHash());
 
-    if (ancestorBlock.getBlockHash().equals(newBlock.getHash())) {
+    // start with self, because descending from yourself is valid
+    Optional<BlockHeader> parentOf = Optional.of(newBlock);
+
+    while (parentOf.isPresent()
+        && !parentOf.get().getBlockHash().equals(ancestorBlock.getBlockHash())) {
```
Comment (garyschulte) [inline consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java:537]: I think we can add one extra comparison here and short circuit unrelated forks: check that parentOf.getNumber() is not < ancestor.  That way we don't run all the way back to genesis if we are comparing hashes of blocks on 2 different forks

**Review by garyschulte — CHANGES_REQUESTED** [review]

**Review by garyschulte — APPROVED** [review]
🚢
