### PR TITLE
Fix: Timeouts are now indexed by both request code and protocol.

### LINKED ISSUE #6869: PeerReputation - timeouts are indexed by request code which does not take into account protocol
Fix - either index by protocol as well as message code - or don't track timeouts per request type at all (simplify) - what is it giving us to track them separately?

ie eth message code 1 and snap message code 1 would both end up counted together

```
  public Map<Integer, AtomicInteger> timeoutCounts() {
    return timeoutCountByRequestType;
  }
```

log does not mention protocol but this is snap

```
2024-04-02 14:47:51.725+10:00 | EthScheduler-Timer-0 | DEBUG | PeerReputation | Disconnection triggered by 3 repeated timeouts for requestCode 1
2024-04-02 14:47:51.725+10:00 | EthScheduler-Timer-0 | DEBUG | EthPeers | Disconnected EthPeer 0xcfe6f6424d1f2255...
```

### PR DESCRIPTION
**Pull request by ibondarev-gsu**
## Fixed Issue(s)
fixes #6869

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [x] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] spotless: `./gradlew spotlessApply`
- [x] unit tests: `./gradlew build`
- [x] acceptance tests: `./gradlew acceptanceTest`
- [x] integration tests: `./gradlew integrationTest`
- [x] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java [hunk 1]
```diff
@@ -56,6 +56,7 @@
 import javax.annotation.Nonnull;
 
 import com.google.common.annotations.VisibleForTesting;
+import org.apache.commons.lang3.tuple.ImmutablePair;
```
Comment (ibondarev-gsu) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java:59]: You can simply use `Pair`, but I thought it would be better to use `ImmutablePair`.

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputationTest.java [hunk 2]
```diff
@@ -39,33 +41,77 @@ public void shouldThrowOnInvalidInitialScore() {
...
+                EthProtocol.NAME, EthProtocolMessages.GET_BLOCK_HEADERS, mockEthPeer))
+        .contains(TIMEOUT);
+    assertThat(
+            reputation.recordRequestTimeout(
+                EthProtocol.NAME, EthProtocolMessages.GET_BLOCK_BODIES, mockEthPeer))
+        .contains(TIMEOUT);
+  }
+
+  @Test
+  public void shouldTrackTimeoutsSeparatelyForDifferentProtocols() {
```
Comment (ibondarev-gsu) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/PeerReputationTest.java:75]: New test, it would have failed before.

**Review by jflo — APPROVED** [review]
Thanks for the PR!

**Comment by macfarla** [comment]
@ibondarev-gsu there is a test failing 

PeerTaskExecutorTest > testExecuteWithPeerSwitchingAndSuccessFlow() FAILED
    org.mockito.exceptions.verification.opentest4j.ArgumentsAreDifferent at PeerTaskExecutorTest.java:322

**Comment by ibondarev-gsu** [comment]
@macfarla fixed
