### PR TITLE
Fix for backward sync wrongly thinking it is done after a restart

### LINKED ISSUE #5053: Internal error, backward sync completed but failed to import finalized block
execution_1                  | Setting logging level to INFO
execution_1                  | 2023-02-04 19:54:23.830+00:00 | main | INFO  | Besu | Starting Besu
execution_1                  | 2023-02-04 19:54:24.516+00:00 | main | WARN  | Besu | --graphql-http-host has been ignored because --graphql-http-enabled was not defined on the command line.
execution_1                  | 2023-02-04 19:54:24.693+00:00 | main | INFO  | Besu | 
execution_1                  | ####################################################################################################
execution_1                  | #                                                                                                  #
execution_1                  | # Besu 23.1.0-dev-e7150102                                                                         #
execution_1                  | #                                                                                                  #
execution_1                  | # Configuration:                                                                                   #
execution_1                  | # Network: Mainnet                                                                                 #
execution_1                  | # Network Id: 1                                                                                    #
execution_1                  | # Data storage: Bonsai                                                                             #
execution_1                  | # Sync mode: Snap                                                                                  #
execution_1                  | # RPC HTTP APIs: WEB3,ETH,NET                                                                      #
execution_1                  | # RPC HTTP port: 8545                                                                              #
execution_1                  | # Engine APIs: ENGINE,ETH                                                                          #
execution_1                  | # Engine port: 8551                                                                                #
execution_1                  | #                                                                                                  #
execution_1                  | # Host:                                                                                            #
execution_1                  | # Java: openjdk-java-17                                                                            #
execution_1                  | # Maximum heap size: 64.00 GB                                                                      #
execution_1                  | # OS: linux-x86_64                                                                                 #
execution_1                  | # glibc: 2.31                                                                                      #
execution_1                  | # Total memory: 503.87 GB                                                                          #
execution_1                  | # CPU cores: 80                                                                                    #
execution_1                  | #                                                                                                  #
execution_1                  | ####################################################################################################
execution_1                  | 2023-02-04 19:54:24.694+00:00 | main | INFO  | Besu | Connecting to 0 static nodes.
execution_1                  | 2023-02-04 19:54:24.694+00:00 | main | INFO  | Besu | Security Module: localfile
execution_1                  | 2023-02-04 19:54:24.756+00:00 | main | INFO  | Besu | Using the native implementation of alt bn128
execution_1                  | 2023-02-04 19:54:24.808+00:00 | main | INFO  | Besu | Using the native implementation of modexp
execution_1                  | 2023-02-04 19:54:24.808+00:00 | main | INFO  | Besu | Using the native implementation of the signature algorithm
execution_1                  | 2023-02-04 19:54:24.814+00:00 | main | INFO  | Besu | Using the native implementation of the blake2bf algorithm
execution_1                  | 2023-02-04 19:54:24.840+00:00 | main | INFO  | DatabaseMetadata | Lookup database metadata file in data directory: /var/lib/besu
execution_1                  | 2023-02-04 19:54:24.910+00:00 | main | INFO  | RocksDBKeyValueStorageFactory | Existing database detected at /var/lib/besu. Version 2
execution_1                  | 2023-02-04 19:54:30.154+00:00 | main | INFO  | KeyPairUtil | Loaded public key 0xba5cb5928621f5ef140f8182dde0c6f0c0447562b2b4d7763b72da5c9ce3df41fd872a26687466e7b711ef53d74526bf724b12fe6217504a76268d815c951cd0 from /var/lib/besu/key
execution_1                  | 2023-02-04 19:54:30.353+00:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: [Frontier: 0, Homestead: 1150000, DaoRecoveryInit: 1920000, DaoRecoveryTransition: 1920001, Homestead: 1920010, TangerineWhistle: 2463000, SpuriousDragon: 2675000, Byzantium: 4370000, Petersburg: 7280000, Istanbul: 9069000, MuirGlacier: 9200000, Berlin: 12244000, London: 12965000, ArrowGlacier: 13773000, GrayGlacier: 15050000]
execution_1                  | 2023-02-04 19:54:30.392+00:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: [Frontier: 0, Homestead: 1150000, DaoRecoveryInit: 1920000, DaoRecoveryTransition: 1920001, Homestead: 1920010, TangerineWhistle: 2463000, SpuriousDragon: 2675000, Byzantium: 4370000, Petersburg: 7280000, Istanbul: 9069000, MuirGlacier: 9200000, Berlin: 12244000, London: 12965000, ArrowGlacier: 13773000, GrayGlacier: 15050000]
execution_1                  | 2023-02-04 19:54:30.401+00:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: []
execution_1                  | 2023-02-04 19:54:31.232+00:00 | main | INFO  | TransactionPoolFactory | Enabling transaction pool
execution_1                  | 2023-02-04 19:54:31.233+00:00 | main | INFO  | TransactionPoolFactory | Disabling transaction handling during initial sync
execution_1                  | 2023-02-04 19:54:31.236+00:00 | main | INFO  | EthPeers | Updating the default best peer comparator
execution_1                  | 2023-02-04 19:54:31.260+00:00 | main | INFO  | BesuControllerBuilder | TTD difficulty is present, creating initial sync for PoS
execution_1                  | 2023-02-04 19:54:31.276+00:00 | main | INFO  | SnapDownloaderFactory | Snap sync was requested, but cannot be enabled because the local blockchain is not empty.
execution_1                  | 2023-02-04 19:54:31.278+00:00 | main | INFO  | TransitionBesuControllerBuilder | TTD present, creating DefaultSynchronizer that stops propagating after finalization
execution_1                  | 2023-02-04 19:54:31.308+00:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
execution_1                  | 2023-02-04 19:54:31.474+00:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: []
execution_1                  | 2023-02-04 19:54:31.537+00:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: []
execution_1                  | 2023-02-04 19:54:31.768+00:00 | main | INFO  | AbstractProtocolScheduleBuilder | Protocol schedule created with milestones: []
execution_1                  | 2023-02-04 19:54:31.785+00:00 | main | INFO  | Runner | Starting external services ... 
execution_1                  | 2023-02-04 19:54:31.786+00:00 | main | INFO  | MetricsHttpService | Starting metrics http service on 0.0.0.0:6060
execution_1                  | 2023-02-04 19:54:31.889+00:00 | vert.x-eventloop-thread-1 | INFO  | MetricsHttpService | Metrics service started and listening on 0.0.0.0:6060
execution_1                  | 2023-02-04 19:54:31.889+00:00 | main | INFO  | JsonRpcHttpService | Starting JSON-RPC service on 0.0.0.0:8545
execution_1                  | 2023-02-04 19:54:31.905+00:00 | vert.x-eventloop-thread-1 | INFO  | JsonRpcHttpService | JSON-RPC service started and listening on 0.0.0.0:8545
execution_1                  | 2023-02-04 19:54:31.905+00:00 | main | INFO  | EngineJsonRpcService | Starting JSON-RPC service on 0.0.0.0:8551
execution_1                  | 2023-02-04 19:54:31.911+00:00 | vert.x-eventloop-thread-1 | INFO  | EngineJsonRpcService | JSON-RPC service started and listening on 0.0.0.0:8551
execution_1                  | 2023-02-04 19:54:31.912+00:00 | main | INFO  | WebSocketService | Starting Websocket service on 0.0.0.0:8546
execution_1                  | 2023-02-04 19:54:31.915+00:00 | vert.x-eventloop-thread-1 | INFO  | WebSocketService | Websocket service started and listening on 0.0.0.0:8546
execution_1                  | 2023-02-04 19:54:31.918+00:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
execution_1                  | 2023-02-04 19:54:31.919+00:00 | main | INFO  | LogBloomCacheMetadata | Lookup cache metadata file in data directory: /var/lib/besu/caches
execution_1                  | 2023-02-04 19:54:31.928+00:00 | main | INFO  | Runner | Starting Ethereum main loop ... 
execution_1                  | 2023-02-04 19:54:31.928+00:00 | main | INFO  | DockerNatManager | Starting docker NAT manager.
execution_1                  | 2023-02-04 19:54:31.937+00:00 | main | INFO  | NetworkRunner | Starting Network.
execution_1                  | 2023-02-04 19:54:31.940+00:00 | main | INFO  | DefaultP2PNetwork | Starting DNS discovery with URL enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
execution_1                  | 2023-02-04 19:54:32.010+00:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0.0.0.0:30303.
execution_1                  | 2023-02-04 19:54:32.011+00:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
execution_1                  | 2023-02-04 19:54:32.054+00:00 | vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0.0.0.0 and port=30303
execution_1                  | 2023-02-04 19:54:32.055+00:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0.0.0.0:30303
execution_1                  | 2023-02-04 19:54:32.108+00:00 | vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | Writing node record to disk. NodeRecord{seq=83, publicKey=0x02ba5cb5928621f5ef140f8182dde0c6f0c0447562b2b4d7763b72da5c9ce3df41, udpAddress=Optional[/127.0.0.1:30303], tcpAddress=Optional[/127.0.0.1:30303], asBase64=-Je4QFFXzeqiZb2EpXqAagdzEjnpXxq90PzI95N7LoRAxSRWULLBJzCv-OzLzUZWApHzyrurQLxpqvSHPyh4a_b9s0hTg2V0aMfGhPCv0OOAgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQK6XLWShiH17xQPgYLd4MbwwER1YrK013Y7ctpcnOPfQYN0Y3CCdl-DdWRwgnZf, nodeId=0x191631e5043602531ea9c04190dd41bbc6f07a2a368438865f39dea4bdce1e33, customFields={tcp=30303, udp=30303, ip=0x7f000001, eth=[[0xf0afd0e3, 0x]], id=V4, secp256k1=0x02ba5cb5928621f5ef140f8182dde0c6f0c0447562b2b4d7763b72da5c9ce3df41}}
execution_1                  | 2023-02-04 19:54:32.181+00:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://ba5cb5928621f5ef140f8182dde0c6f0c0447562b2b4d7763b72da5c9ce3df41fd872a26687466e7b711ef53d74526bf724b12fe6217504a76268d815c951cd0@127.0.0.1:30303
execution_1                  | 2023-02-04 19:54:32.183+00:00 | main | INFO  | DefaultP2PNetwork | Node address 0x90dd41bbc6f07a2a368438865f39dea4bdce1e33
execution_1                  | 2023-02-04 19:54:32.189+00:00 | main | INFO  | NetworkRunner | Supported capabilities: [eth/63, eth/64, eth/65, eth/66, eth/67, eth/68], [snap/1]
execution_1                  | 2023-02-04 19:54:32.189+00:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
execution_1                  | 2023-02-04 19:54:32.192+00:00 | main | INFO  | TransactionPoolFactory | Enabling transaction handling following initial sync
execution_1                  | 2023-02-04 19:54:32.196+00:00 | main | INFO  | DefaultSynchronizer | Stopping block propagation.
execution_1                  | 2023-02-04 19:54:32.197+00:00 | main | INFO  | DefaultSynchronizer | Stopping the pruner.
execution_1                  | 2023-02-04 19:54:32.198+00:00 | main | INFO  | Runner | Ethereum main loop is up.
execution_1                  | 2023-02-04 19:54:54.203+00:00 | Timer-0 | INFO  | DNSResolver | Resolved 2409 nodes
execution_1                  | 2023-02-04 19:56:06.947+00:00 | vert.x-worker-thread-0 | INFO  | BackwardSyncContext | Starting a new backward sync session
execution_1                  | 2023-02-04 19:56:06.955+00:00 | vert.x-worker-thread-0 | INFO  | BackwardsSyncAlgorithm | Current backward sync session is done
execution_1                  | 2023-02-04 19:56:08.179+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964
execution_1                  | 2023-02-04 19:56:08.196+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964

execution_1                  | 2023-02-04 19:56:36.760+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964
execution_1                  | 2023-02-04 19:56:38.094+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964
execution_1                  | 2023-02-04 19:56:38.320+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964
execution_1                  | 2023-02-04 19:56:43.985+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964
execution_1                  | 2023-02-04 19:56:49.107+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964
execution_1                  | 2023-02-04 19:57:00.682+00:00 | vert.x-worker-thread-0 | WARN  | MergeCoordinator | Internal error, backward sync completed but failed to import finalized block 0xe8f33c4587ca5e19d441139e1d45ba19bb58450b89e1e4e5e21d179b858ab964

### PR DESCRIPTION
**Pull request by fab-10**
## PR description

There is an issue when restarting Besu when a backward sync session is running, since after the restart it is possible that the Consensus client sends a FcU or a NewPayload for a block that is present in the backward sync storage, but not yet imported, so not on the main chain, but still the backward sync thinks it should not do anything with that block, so it returns like it has completed the sync, but since the sync is not done actually then the internal error that the finalize block is not present.

The solution is to persist the backward sync status, so in case of a restart, it can resume from where it was interrupted.

## Fixed Issue(s)

fixes #5053 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Acceptance Tests (Non Mainnet)

- [x] I have considered running `./gradlew acceptanceTestNonMainnet` locally if my PR affects non-mainnet modules.

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by siladu** [comment]
Hi @fab-10 can you add details of any testing you've done to the description please.

**Comment by fab-10** [comment]
To test I have used a mainnet Lighthouse-Besu, with a long backward sync (days), that was experiencing the problem, and after applying this fix, I have restarted it many times, this issue was not reported anymore and the sync eventually finished.

Note: in case you apply this fix to an instance that is currently doing a backward sync, of course on the first start it still does not have the stored state, so it could still report the issue, so the workaround is: delete the CL data and let it checkpoint sync (it only takes seconds) and restart Besu, so the CL could send a fresh hash that is not in the backward sync storage

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 1]
```diff
@@ -86,22 +120,43 @@ public synchronized List<BlockHeader> getFirstNAncestorHeaders(final int size) {
...
+  }
+
+  private void updateFirstStoredAncestor(final Optional<BlockHeader> maybeHeader) {
+    maybeHeader.ifPresentOrElse(
+        header -> variablesStorage.put(FIRST_STORED_ANCESTOR_KEY, header),
+        () -> variablesStorage.drop(FIRST_STORED_ANCESTOR_KEY));
+    firstStoredAncestor = maybeHeader;
+  }
+
+  private void updateLastStorePivot(final Optional<BlockHeader> maybeHeader) {
```
Comment (siladu) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:155]:
```suggestion
  private void updateLastStoredPivot(final Optional<BlockHeader> maybeHeader) {
```

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 2]
```diff
@@ -86,22 +120,43 @@ public synchronized List<BlockHeader> getFirstNAncestorHeaders(final int size) {
...
-    firstStoredAncestor = Optional.of(blockHeader);
-    LOG.atDebug()
-        .setMessage("Added header {} to backward chain led by pivot {} on height {}")
-        .addArgument(blockHeader::toLogString)
-        .addArgument(() -> lastStoredPivot.orElseThrow().toLogString())
-        .addArgument(firstHeader::getNumber)
-        .log();
+
+    if (firstStoredAncestor.isEmpty()) {
+      updateLastStorePivot(Optional.of(blockHeader));
```
Comment (siladu) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:133]: Why don't we add the blockHeader to the chainStorage here as well?

Does firstStoredAncestor.isEmpty represent the first BWS block that we've received?

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgorithm.java [hunk 3]
```diff
@@ -64,7 +64,10 @@ public CompletableFuture<Void> pickNextStep() {
       return executeSyncStep(firstHash.get())
           .thenAccept(
               result -> {
-                LOG.info("Backward sync target block is {}", result.toLogString());
+                LOG.atDebug()
```
Comment (siladu) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgorithm.java:67]: Was this intentionally moved from info to debug?

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 4]
```diff
@@ -118,9 +173,9 @@ public synchronized void dropFirstHeader() {
     headers.drop(firstStoredAncestor.get().getHash());
     final Optional<Hash> hash = chainStorage.get(firstStoredAncestor.get().getHash());
     chainStorage.drop(firstStoredAncestor.get().getHash());
-    firstStoredAncestor = hash.flatMap(headers::get);
+    updateFirstStoredAncestor(hash.flatMap(headers::get));
     if (firstStoredAncestor.isEmpty()) {
-      lastStoredPivot = Optional.empty();
+      updateLastStorePivot(Optional.empty());
```
Comment (siladu) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:178]: Don't think this is covered by a test? I can comment out whole condition and nothing breaks

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 5]
```diff
@@ -86,22 +120,43 @@ public synchronized List<BlockHeader> getFirstNAncestorHeaders(final int size) {
...
   public synchronized void prependAncestorsHeader(final BlockHeader blockHeader) {
-    if (firstStoredAncestor.isEmpty()) {
-      firstStoredAncestor = Optional.of(blockHeader);
-      lastStoredPivot = Optional.of(blockHeader);
+    prependAncestorsHeader(blockHeader, false);
+  }
+
+  public synchronized void prependAncestorsHeader(
+      final BlockHeader blockHeader, final boolean alreadyStored) {
+    if (!alreadyStored) {
```
Comment (siladu) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:128]: Don't think this condition is covered by tests - if you always call headers.put everything still passes.

**Review by siladu — COMMENTED** [review]
I don't know this code well enough to approve, trying to learn it hence the questions!

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 6]
```diff
@@ -35,20 +36,48 @@
...
+  private Optional<BlockHeader> firstStoredAncestor;
+  private Optional<BlockHeader> lastStoredPivot;
   private final Queue<Hash> hashesToAppend = new ArrayDeque<>();
 
   public BackwardChain(
       final GenericKeyValueStorageFacade<Hash, BlockHeader> headersStorage,
       final GenericKeyValueStorageFacade<Hash, Block> blocksStorage,
-      final GenericKeyValueStorageFacade<Hash, Hash> chainStorage) {
+      final GenericKeyValueStorageFacade<Hash, Hash> chainStorage,
+      final GenericKeyValueStorageFacade<String, BlockHeader> variablesStorage) {
```
[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:54]: Bws uses the db to keep some data during the sync, for the primary purpose that it could fairly large and not fit in memory. 
But I think that supporting resuming after the restart was not the intent of the storage, because some info were missing to fully support resuming, specifically 2 variables that point to the current status of the bws session.
So this `variablesStorage` is used to store the status of the current bws session, so resuming is fully supported.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 7]
```diff
@@ -67,6 +96,11 @@ public static BackwardChain from(
         new GenericKeyValueStorageFacade<>(
             Hash::toArrayUnsafe,
             new HashConvertor(),
+            storageProvider.getStorageBySegmentIdentifier(
+                KeyValueSegmentIdentifier.BACKWARD_SYNC_CHAIN)),
+        new GenericKeyValueStorageFacade<>(
+            key -> key.getBytes(StandardCharsets.UTF_8),
+            BlocksHeadersConvertor.of(blockHeaderFunctions),
             storageProvider.getStorageBySegmentIdentifier(
                 KeyValueSegmentIdentifier.BACKWARD_SYNC_CHAIN)));
```
[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:105]: I didn't want to create another column family only to store 2 variables, so I used one of the existing, and chosen `BACKWARD_SYNC_CHAIN` because it is where the sequence of the tasks to do is stored, and where the variables point. Said that it could be also stored in the other column family, I just thought this was more related

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java (hunk 5 above)
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:128]: this is only a for performance, in the case we already know that the header is already present, because we just read it, so we can avoid writing to the db

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 8]
```diff
@@ -86,22 +120,43 @@ public synchronized List<BlockHeader> getFirstNAncestorHeaders(final int size) {
   }
 
   public synchronized void prependAncestorsHeader(final BlockHeader blockHeader) {
-    if (firstStoredAncestor.isEmpty()) {
-      firstStoredAncestor = Optional.of(blockHeader);
-      lastStoredPivot = Optional.of(blockHeader);
+    prependAncestorsHeader(blockHeader, false);
+  }
+
+  public synchronized void prependAncestorsHeader(
```
[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:126]: yes a lot of methods could be changed to be package-private, will when refactoring to use the standard pipeline

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java (hunk 2 above)
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:133]: > Why don't we add the blockHeader to the chainStorage here as well?

`chainStorage` is the sequence of the blocks to import, each entry is blockHash -> nextBlockHash, so you know what block to import next, while the block headers are saved in another table.

> Does firstStoredAncestor.isEmpty represent the first BWS block that we've received?

it is empty at the beginning of the bws, and then it is updated when going backward/forward to point to the current block, and this is one of the variables that was not stored, but is required for to resume the session

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java (hunk 4 above)
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:178]: probably there is a lot yet to cover 😅

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgorithm.java (hunk 3 above)
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncAlgorithm.java:67]: Yes, the bws progress log is still not perfect and this could be noisy and not clear sometimes

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (siladu) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:54]: Got it. Maybe sessionDataStorage is a clearer name? Variables seems quite generic to me.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (siladu) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:105]: makes sense - worth a comment in the code to explain?

[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java:108]: done

**Review by macfarla — COMMENTED** [review]
looks ok to me - one minor comment

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java [hunk 9]
```diff
@@ -48,7 +48,7 @@ protected Hash possibleRestoreOldNodes(final BlockHeader firstAncestor) {
     Hash lastHash = firstAncestor.getParentHash();
     Optional<BlockHeader> iterator = backwardChain.getHeader(lastHash);
     while (iterator.isPresent()) {
-      backwardChain.prependAncestorsHeader(iterator.get());
+      backwardChain.prependAncestorsHeader(iterator.get(), true);
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java:51]: How do we know for certain that the header has already been stored?

Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java:51]: Because we just got the header at line 49
