### PR TITLE
Fix txpool dump/restore race condition

### LINKED ISSUE #6664: Race condition in txpool dump/restore
Since the txpool can be disabled/enabled according to the sync status it could happens that a restore and a dump tasks overlaps, causing the exception below. 

```

2024-02-29 14:05:05.532+00:00 | nioEventLoopGroup-3-5 | INFO  | TransactionPoolFactory | Node out of sync, disabling transaction handling
2024-02-29 14:05:05.534+00:00 | ForkJoinPool.commonPool-worker-2 | INFO  | TransactionPool | Saving 5605 transactions to file /data/linea/txpool.dump
2024-02-29 14:05:05.586+00:00 | ForkJoinPool.commonPool-worker-2 | INFO  | TransactionPool | Saved 5605 transactions to file /data/linea/txpool.dump
2024-02-29 14:05:33.520+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | TransactionPoolFactory | Node is in sync, enabling transaction handling
2024-02-29 14:05:33.521+00:00 | ForkJoinPool.commonPool-worker-1 | INFO  | TransactionPool | Loading transaction pool content from file /data/linea/txpool.dump
2024-02-29 14:05:33.539+00:00 | nioEventLoopGroup-3-5 | INFO  | TransactionPoolFactory | Node out of sync, disabling transaction handling
2024-02-29 14:05:33.543+00:00 | ForkJoinPool.commonPool-worker-2 | INFO  | TransactionPool | Saving 64 transactions to file /data/linea/txpool.dump
2024-02-29 14:05:33.546+00:00 | ForkJoinPool.commonPool-worker-2 | INFO  | TransactionPool | Saved 64 transactions to file /data/linea/txpool.dump
2024-02-29 14:05:33.547+00:00 | ForkJoinPool.commonPool-worker-1 | ERROR | TransactionPool | Error while restoring transaction pool from disk
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Last unit does not have enough valid bits
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) [?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) [?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
Caused by: java.lang.IllegalArgumentException: Last unit does not have enough valid bits
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:868) ~[?:?]
        at java.base/java.util.Base64$Decoder.decode(Base64.java:566) ~[?:?]
        at java.base/java.util.Base64$Decoder.decode(Base64.java:589) ~[?:?]
        at org.apache.tuweni.bytes.Bytes.fromBase64String(Bytes.java:583) ~[tuweni-bytes-2.4.2.jar:2.4.2]
        at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool$SaveRestoreManager.lambda$executeLoadFromDisk$5(TransactionPool.java:778) ~[besu-eth-24.2.0-SNAPSHOT.jar:24.2.0-dev-c6f8cf22]
        at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
        at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1932) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.IntPipeline.collect(IntPipeline.java:532) ~[?:?]
        at java.base/java.util.stream.IntPipeline.summaryStatistics(IntPipeline.java:509) ~[?:?]
        at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool$SaveRestoreManager.executeLoadFromDisk(TransactionPool.java:785) ~[besu-eth-24.2.0-SNAPSHOT.jar:24.2.0-dev-c6f8cf22]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        ... 6 more
2024-02-29 14:05:33.636+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | TransactionPoolFactory | Node is in sync, enabling transaction handling
2024-02-29 14:05:33.637+00:00 | ForkJoinPool.commonPool-worker-3 | INFO  | TransactionPool | Loading transaction pool content from file /data/linea/txpool.dump
2024-02-29 14:05:33.655+00:00 | ForkJoinPool.commonPool-worker-3 | INFO  | TransactionPool | Added 64 transactions of 64 loaded from file /data/linea/txpool.dump
```

### PR DESCRIPTION
**Pull request by fab-10**
### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Most advanced CI tests are deferred until PR approval, but you could:

- [ ] locally run all unit tests via: `./gradlew build`
- [ ] locally run all acceptance tests via: `./gradlew acceptanceTest`
- [ ] locally run all integration tests via: `./gradlew integrationTest`
- [ ] locally run all reference tests via: `./gradlew ethereum:referenceTests:referenceTests`

## PR description

The disk access was not properly guarded against overlapping dump/restore tasks

## Fixed Issue(s)

fixes #6664

### CODE REVIEW

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java [hunk 1]
```diff
@@ -692,25 +691,20 @@ private CompletableFuture<Void> serializeAndDedupOperation(
...
+                // nothing to do
               }
-
-              isCancelled.set(false);
-              operationInProgress.set(CompletableFuture.runAsync(operation));
-              return operationInProgress.get();
-            } catch (InterruptedException ie) {
-              isCancelled.set(false);
-            } finally {
-              diskAccessLock.unlock();
```
Comment (macfarla) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java:712]: do we not need the equivalent of releasing in finally

Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java:712]: no and this was the error, since the operation is run async, we can't know here when it is done, and so it is not up to us to release the lock, but the lock must be release after the async operation is done with this code `CompletableFuture.runAsync(operation).thenRun(diskAccessLock::release));`

**Review by macfarla — APPROVED** [review]
