### PR TITLE
Fix restoring txpool from disk when blob transactions are present

### LINKED ISSUE #8449: Regression in txpool dump and restore on v25.3.0
### Steps to Reproduce
1. Run Besu on Ethereum mainnet with `--tx-pool=layered --tx-pool-enable-save-restore=true` with no txpool dump file present
2. Leave Besu running for about 5 minutes to saturate the transaction pool and quit Besu
3. Run Besu again with the same arguments

**Expected behavior:** See "Added X transactions of Y loaded from file Z, before operation was cancelled" reported within the logs

**Actual behavior:** An non-fatal error is reported as originating from the component TransactionPool "Error while restoring transaction pool from disk" with a stacktrace

**Frequency:** Almost every single restart of Besu on Ethereum mainnet since updating to v23.5.0

### Logs
```
2025-03-21 04:32:45.062+00:00 | main | INFO  | NetworkRunner | Supported capabilities: [eth/63, eth/64, eth/65, eth/66, eth/67, eth/68], [snap/1]
2025-03-21 04:32:45.062+00:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2025-03-21 04:32:45.073+00:00 | main | INFO  | TransactionPoolFactory | Enabling transaction handling following initial sync
2025-03-21 04:32:45.084+00:00 | ForkJoinPool.commonPool-worker-7 | INFO  | TransactionPool | Loading transaction pool content from file /var/lib/besu/txpool.dump
2025-03-21 04:32:45.085+00:00 | main | INFO  | DefaultSynchronizer | Stopping block propagation.
2025-03-21 04:32:45.085+00:00 | main | INFO  | DefaultSynchronizer | Stopping the pruner.
2025-03-21 04:32:45.086+00:00 | main | INFO  | Runner | Ethereum main loop is up.
2025-03-21 04:32:47.803+00:00 | ForkJoinPool.commonPool-worker-7 | ERROR | TransactionPool | Error while restoring transaction pool from disk
java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.rlp.RLPException: Cannot read a arbitrary precision scalar, current item is a list (at bytes 4-1348: fa06067a[f9053d01...b4b9b664]fa06000c...)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: org.hyperledger.besu.ethereum.rlp.RLPException: Cannot read a arbitrary precision scalar, current item is a list (at bytes 4-1348: fa06067a[f9053d01...b4b9b664]fa06000c...)
	at org.hyperledger.besu.ethereum.rlp.AbstractRLPInput.error(AbstractRLPInput.java:205)
	at org.hyperledger.besu.ethereum.rlp.AbstractRLPInput.checkElt(AbstractRLPInput.java:250)
	at org.hyperledger.besu.ethereum.rlp.AbstractRLPInput.checkScalar(AbstractRLPInput.java:263)
	at org.hyperledger.besu.ethereum.rlp.AbstractRLPInput.readBigIntegerScalar(AbstractRLPInput.java:337)
	at org.hyperledger.besu.ethereum.rlp.BytesValueRLPInput.readBigIntegerScalar(BytesValueRLPInput.java:24)
	at org.hyperledger.besu.ethereum.core.encoding.BlobTransactionDecoder.readTransactionPayloadInner(BlobTransactionDecoder.java:70)
	at org.hyperledger.besu.ethereum.core.encoding.BlobTransactionDecoder.readTransactionPayload(BlobTransactionDecoder.java:53)
	at org.hyperledger.besu.ethereum.core.encoding.BlobTransactionDecoder.decode(BlobTransactionDecoder.java:47)
	at org.hyperledger.besu.ethereum.core.encoding.TransactionDecoder.decodeTypedTransaction(TransactionDecoder.java:102)
	at org.hyperledger.besu.ethereum.core.encoding.TransactionDecoder.decodeTypedTransaction(TransactionDecoder.java:82)
	at org.hyperledger.besu.ethereum.core.encoding.TransactionDecoder.decodeRLP(TransactionDecoder.java:60)
	at org.hyperledger.besu.ethereum.core.Transaction.readFrom(Transaction.java:140)
	at org.hyperledger.besu.ethereum.core.Transaction.readFrom(Transaction.java:136)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool$SaveRestoreManager.lambda$executeLoadFromDisk$6(TransactionPool.java:883)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool$SaveRestoreManager.executeLoadFromDisk(TransactionPool.java:890)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more
```

### Versions (Add all that apply)
* Software version: `besu/v25.3.0/linux-x86_64/openjdk-java-21` (Docker image)
* Java version:
```
openjdk version "21.0.6" 2025-01-21
OpenJDK Runtime Environment (build 21.0.6+7-Ubuntu-124.04.1)
OpenJDK 64-Bit Server VM (build 21.0.6+7-Ubuntu-124.04.1, mixed mode, sharing)
```
* OS Name & Version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
* Kernel Version: 
```
Linux [redacted] 6.13.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 13 Mar 2025 18:12:00 +0000 x86_64 x86_64 x86_64 GNU/Linux
```
(Arch Linux as Podman container host)
* Virtual Machine software & version: `N/A`
* Docker Version:
```
Client:       Podman Engine
Version:      5.4.1
API Version:  5.4.1
Go Version:   go1.24.1
Git Commit:   b79bc8afe796cba51dd906270a7e1056ccdfcf9e
Built:        Wed Mar 12 07:07:00 2025
OS/Arch:      linux/amd64
```
* Cloud VM, type, size: `N/A / Bare metal`
* Consensus Client & Version if using Proof of Stake: Teku 25.3.0

### Additional Information
My best guess from poking around, is that this was introduced in [74a1d8a1ea7f... (Support pending transaction score when saving and restoring txpool (#8363))](https://github.com/hyperledger/besu/commit/74a1d8a1ea7f6cf29fee0ee60b260160f0c17473).

This PR attempts to let `org.hyperledger.besu.ethereum.eth.transactions.TransactionPool` make use of the [POOLED_TRANSACTION encoding context when saving the dump file under executeSaveToDisk()](https://github.com/hyperledger/besu/blob/74a1d8a1ea7f6cf29fee0ee60b260160f0c17473/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java#L829). While decoding is still being performed under executeLoadFromDisk() through the `org.hyperledger.besu.ethereum.core.Transaction.readFrom()` wrapper, which [assumes a BLOCK_BODY context](https://github.com/hyperledger/besu/blob/2412586d06c2c0d1424fbfacbbababa62f2a5a74/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java#L140).

Unrelated, but TransactionPool.executeLoadFromDisk() appears to report the wrong error message [when throwing an IOException](https://github.com/hyperledger/besu/blob/74a1d8a1ea7f6cf29fee0ee60b260160f0c17473/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java#L915).

### PR DESCRIPTION
**Pull request by fab-10**
## PR description

Fix to use the POOLED_TRANSACTION format also when reading from disk to fix the issue related to saving blob tx with that format but reading them with the BLOCK_BODY format.

Writing a test for this, I found that we where not correctly supporting the enable/disable feature in the unit tests, so that required a bit of refactoring on the test code.

## Fixed Issue(s)

fixes #8449

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by macfarla — APPROVED** [review]

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTest.java [hunk 1]
```diff
@@ -384,10 +386,19 @@ public void shouldAllowSequenceOfTransactionsWithIncreasingNonceFromSameSender(
...
-    doReturn(true).when(transactions).containsTransaction(transaction0);
-    transactionPool.addRemoteTransactions(singletonList(transaction0));
+    givenTransactionIsValid(transaction0);
+    addAndAssertRemoteTransactionsValid(transaction0);
+
+    verify(transactionValidatorFactory, atLeastOnce()).get();
+
+    clearInvocations(transactionValidatorFactory);
+
+    // trying to readd the same tx should return transaction already known and no
```
Comment (pinges) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTest.java:396]:
```suggestion
    // trying to read the same tx should return transaction already known and no
```

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolSaveRestoreTest.java [hunk 2]
```diff
@@ -162,54 +183,22 @@ public void localTransactionIsSavedAndRestored(final boolean noLocalPriority)
...
     final var savedContent = Files.readString(saveFilePath, StandardCharsets.US_ASCII);
 
-    assertThat(savedContent).isEqualToIgnoringNewLines("127l" + transaction2Base64(transaction));
+    assertThat(savedContent)
+        .isEqualToIgnoringNewLines(
+            "127" + ((isLocal) ? "l" : "r") + transaction2Base64(transaction));
 
     // re-enabling the txpool restores from file
-    transactionPool.setEnabled().get(10, TimeUnit.SECONDS);
+    transactionPool.setEnabled().get(10000, TimeUnit.SECONDS);
```
Comment (pinges) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolSaveRestoreTest.java:191]: 10000 seconds?

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTest.java (hunk 1 above)
Comment (fab-10) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/AbstractTransactionPoolTest.java]: it is _re-add_, done

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolSaveRestoreTest.java (hunk 2 above)
Comment (fab-10) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolSaveRestoreTest.java]: good catch, debug left over reverted
