### PR TITLE
for fcu v2 use correct invalid params error code

### LINKED ISSUE #6757: engine-withdrawals hive failures
There's 10 hive tests failing in engine-withdrawals suite - should be an easy fix - error codes are incorrect - similar to what was fixed here - https://github.com/hyperledger/besu/issues/6554

`Expected error code on EngineForkchoiceUpdatedV2: want=-32602, got=-38003`

https://hivetests2.ethdevops.io/suite.html?suiteid=1710782804-a490cec1139ae0b6ace72dc87b8c2f20.json&suitename=engine-withdrawals#test-144

### PR DESCRIPTION
**Pull request by macfarla**
## PR description
fcuV2 should return invalid params not invalid payload attributes.

Fixes #6757 
fixes 10 engine-withdrawals tests (hive)

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [x] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Most advanced CI tests are deferred until PR approval, but you could:

- [x] locally run all unit tests via: `./gradlew build`
- [ ] locally run all acceptance tests via: `./gradlew acceptanceTest`
- [ ] locally run all integration tests via: `./gradlew integrationTest`
- [ ] locally run all reference tests via: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java [hunk 1]
```diff
@@ -71,6 +71,6 @@ protected Optional<JsonRpcErrorResponse> isPayloadAttributesValid(
 
   @Override
   protected RpcErrorType getInvalidPayloadError() {
```
Comment (jflo) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java:73]: methods should be renamed, this is confusing/misleading

Comment (macfarla) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java]: refactored this

**Comment by macfarla** [comment]
> just re-running hive tests

INFO[03-21|11:56:25] simulation ethereum/engine finished      suites=5 tests=404 failed=0

**Review by jflo — APPROVED** [review]
