### PR TITLE
JsonUtil.normalizeKeys should handle ArrayNodes

### LINKED ISSUE #2856: JsonUtil.normalizeKeys should handle ArrayNodes
### Description
As a besu user, I want the genesis file to be read correctly so that my transition config is not ignored if I forget to use lower case.

### Steps to Reproduce (Bug)
1. Start besu with a genesis file containing a transition with mixed case keys (see example below)
2. Mine blocks until the transition should occur
3. Verify the transition hasn't occurred

**Expected behavior:** Mixed case keys should be ignored (normalised) and the transition should work

**Actual behavior:** Transition isn't triggered
### Additional Information

Proposed solution is to make JsonUtil.normalizeKeys support ArrayNodes.

In the following example, `validatorSelectionMode` and `validatorContractAddress` should be normalized and therefore read into the configuration in memory.

```
{
  "config": {
    "chainid": 1337,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "qbft": {
      "epochlength": 30000,
      "blockperiodseconds": 15,
      "requesttimeoutseconds": 10
    },
    "transitions": {
      "qbft": [
        {
          "block": 1,
          "validatorSelectionMode": "contract",
          "validatorContractAddress": "0x0000000000000000000000000000000000008888"
        }
      ]
    }
  },
  "nonce": "0x0",
  "timestamp": "0x5b3d92d7",
  "extraData": "0xf83aa00000000000000000000000000000000000000000000000000000000000000000d59489abefc83377592802c8e001e41143a7aed15347c080c0",
  "gasLimit": "0x29b92700",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "fe3b557e8fb62b89f4916b721be55ceb828dbd73" : {
      "privateKey" : "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "0xad78ebc5ac6200000"
    },
    "627306090abaB3A6e1400e9345bC60c78a8BEf57" : {
      "privateKey" : "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "90000000000000000000000"
    },
    "f17f52151EbEF6C7334FAD080c5704D77216b732" : {
      "privateKey" : "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "90000000000000000000000"
    },
    "0x0000000000000000000000000000000000008888": {
      "comment": "validator smart contract. This is compiled from validator_contract.sol using solc --evm-version byzantium --bin-runtime validator_contract.sol",
      "balance": "0",
      "code": "608060405234801561001057600080fd5b5060043610610048576000357c010000000000000000000000000000000000000000000000000000000090048063b7ab4db51461004d575b600080fd5b61005561006b565b604051610062919061017e565b60405180910390f35b606060008054806020026020016040519081016040528092919081815260200182805480156100ef57602002820191906000526020600020905b8160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190600101908083116100a5575b5050505050905090565b60006101058383610111565b60208301905092915050565b61011a816101d9565b82525050565b600061012b826101b0565b61013581856101c8565b9350610140836101a0565b8060005b8381101561017157815161015888826100f9565b9750610163836101bb565b925050600181019050610144565b5085935050505092915050565b600060208201905081810360008301526101988184610120565b905092915050565b6000819050602082019050919050565b600081519050919050565b6000602082019050919050565b600082825260208201905092915050565b60006101e4826101eb565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff8216905091905056fea26469706673582212206d880cf012c1677c691bf6f2f0a0e4eadf57866ffe5cd2d9833d3cfdf27b15f664736f6c63430008060033",
      "storage": {
        "0000000000000000000000000000000000000000000000000000000000000000": "0000000000000000000000000000000000000000000000000000000000000001",
        "290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563": "00000000000000000000000089abefc83377592802c8e001e41143a7aed15347"
      }
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

### PR DESCRIPTION
**Pull request by lucassaldanha**
## PR description
- Updated JsonUtils to handle ArrayNode. This is important now that we have bft transitions that are specified in an array in the genesis file.

## Fixed Issue(s)
fixes #2856

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

File: config/src/main/java/org/hyperledger/besu/config/JsonUtil.java [hunk 1]
```diff
@@ -50,13 +50,28 @@ public static ObjectNode normalizeKeys(final ObjectNode objectNode) {
...
 
+  private static ArrayNode normalizeKeysInArray(final ArrayNode arrayNode) {
+    final ArrayNode normalizedArray = JsonUtil.createEmptyArrayNode();
+    arrayNode.forEach(
+        value -> {
+          if (value instanceof ObjectNode) {
+            normalizedArray.add(normalizeKeys((ObjectNode) value));
+          } else if (value instanceof ArrayNode) {
+            normalizedArray.add(normalizeKeysInArray((ArrayNode) value));
+          }
```
Comment (siladu) [inline config/src/main/java/org/hyperledger/besu/config/JsonUtil.java:70]: I think this might be missing an else case? 
e.g. if you had a string value in an array, rather than an Object or Array, it would get ignored and so effectively stripped out.

e.g.
```
"configArray": [
  "I don't need normalising but I shouldn't be stripped out"
]
```

yields
```
"configarray": []
```

**Review by siladu — CHANGES_REQUESTED** [review]

File: config/src/main/java/org/hyperledger/besu/config/JsonUtil.java (hunk 1 above)
Comment (lucassaldanha) [reply config/src/main/java/org/hyperledger/besu/config/JsonUtil.java:70]: Nice catch!

**Review by siladu — APPROVED** [review]
LGTM - you'll need someone with maintainer status to fully approve :)

**Review by usmansaleem — APPROVED** [review]
LGTM

**Review by jframe — APPROVED** [review]
LGTM
