### PR TITLE
Fix block value calculation

### LINKED ISSUE #5040: Block value calculation may be incorrect in getPayloadV2
Some WIP hive tests have picked up an issue...

> Besu is returning value, e.g. in one of the blocks, of 54089155500000000, but the expected value by the test (and returned by other clients) is 6224737500000000, which 8 times lower, and this is because, during the calculation, the "cumulative gas used" of the transaction is used to get the fee, instead of the "gas used"
> If i swap the "gas used" by "cumulative gas used" while computing the expected value in the test, I get the exact same value as Besu

### PR DESCRIPTION
**Pull request by gfukushima**
## PR description
This PR fix the block value calculation mechanism by using gasUsed instead of the cumulativeGas to calculate the block value.

This change has been tested against the hive test(GetPayloadV2 Block Value) for this feature.

## Fixed Issue(s)

Fixes #5040
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Acceptance Tests (Non Mainnet)

- [x] I have considered running `./gradlew acceptanceTestNonMainnet` locally if my PR affects non-mainnet modules.

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java [hunk 1]
```diff
@@ -27,7 +27,13 @@ public Wei calculateBlockValue(final BlockWithReceipts blockWithReceipts) {
     Wei totalFee = Wei.ZERO;
     for (int i = 0; i < txs.size(); i++) {
       final Wei minerFee = txs.get(i).getEffectivePriorityFeePerGas(block.getHeader().getBaseFee());
-      totalFee = totalFee.add(minerFee.multiply(receipts.get(i).getCumulativeGasUsed()));
+      // we don't store gasUsed and need to calculate that on the fly
+      // receipts are fetched in ascendant sorted by cumulativeGasUsed
```
Comment (siladu) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java:31]:
```suggestion
      // we don't store gasUsed per transaction and need to calculate that on the fly
      // receipts are fetched in ascending sorted by cumulativeGasUsed
```

**Review by siladu — APPROVED** [review]
LGTM!

I was wondering if we could/should store gasUsed in an object somewhere, but I don't think it's worth it given that getPayload is called relatively rarely.

**Review by jframe — DISMISSED** [review]
LGTM

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java (hunk 1 above)
Comment (gfukushima) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java:31]: Had the same thought, did a bit of digging into the code, and even the BlockchainQuery does this same calculation to create instances of TransactionReceiptWithMetadata

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java [hunk 2]
```diff
@@ -27,7 +27,13 @@ public Wei calculateBlockValue(final BlockWithReceipts blockWithReceipts) {
     Wei totalFee = Wei.ZERO;
     for (int i = 0; i < txs.size(); i++) {
       final Wei minerFee = txs.get(i).getEffectivePriorityFeePerGas(block.getHeader().getBaseFee());
-      totalFee = totalFee.add(minerFee.multiply(receipts.get(i).getCumulativeGasUsed()));
+      // we don't store gasUsed and need to calculate that on the fly
```
Comment (jframe) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java:30]: Can the TransactionWithMetadata type be used here? If we can use that then there is getGasUsed method that can be used instead to avoid duplicating this logic. Should be able to use the BlockchainQueries.blockByHash from the EngineGetPayloadV2 method I think.

Comment (jframe) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java:30]: After some discussion, the BlockchainQueries can't be used as these blocks aren't appended yet. So this approach isn't possible

**Review by jframe — APPROVED** [review]
LGTM
