### PR TITLE
fix: prevent infinite loop in clearStorage with >256 storage slots

### LINKED ISSUE #9963: Bonsai `clearStorage()` causes full sync to hang indefinitely at block 347,481
### Steps to Reproduce

1. Start Besu with default Bonsai storage in full sync mode:
   ```bash
   besu --network=mainnet --sync-mode=FULL --data-storage-format=BONSAI
   ```
2. Start a consensus client (e.g., Teku with checkpoint sync) pointed at Besu's engine API.
3. Wait for sync to reach block 347,481.

**Expected behavior:** Block 347,481 imports normally and sync continues.

**Actual behavior:** The `importBlock` thread hangs indefinitely in `BonsaiWorldState.clearStorage()`, consuming 100% CPU on one core. Sync never progresses past block 347,480.

**Frequency:** 100% — deterministic on every full sync attempt with Bonsai storage.

### Root Cause

Block 347,481 contains a single transaction (`0xcb7651c116af69ebcc4e1a0d4e1741d6085773efadb189423b3707a0f9f63409`) that calls `kill()` on contract `0x5ee4861cDA18C9f5288391d209A2C4Ecab92dfD8`, which executes `SELFDESTRUCT`.

This contract has **297 storage slots** (confirmed via `trace_replayTransaction` stateDiff on all 24 transactions to the contract).

Since this is a Frontier-era block (pre-Byzantium), `FrontierTransactionReceiptFactory.create()` calls `frontierRootHash()`, which triggers `calculateRootHash()` → `clearStorage()`.

`clearStorage()` iterates entries in batches of 256 via `storageTrie.entriesFrom(Bytes32.ZERO, 256)`. With 297 slots:

1. **Batch 1**: Removes 256 entries from the trie (fast).
2. **Batch 2**: Re-traverses the heavily rebalanced trie from `ZERO` to find the remaining 41 entries. This re-traversal is extremely expensive because the trie structure has been severely mutated by removing 256 of 297 nodes.

The performance cliff is sharp:
- **200 slots** (1 batch): completes in **~28ms**
- **257 slots** (2 batches): hangs for **>10 minutes** in-memory

### Thread Dump

```
"EthScheduler-Services-8 (importBlock)" #9087 prio=5 cpu=596552.90ms RUNNABLE
  at org.apache.tuweni.bytes.Bytes.compareTo(Bytes.java:1711)
  at java.util.TreeMap.put(TreeMap.java:849)
  at o.h.b.ethereum.trie.StorageEntriesCollector.lambda$onLeaf$0(StorageEntriesCollector.java:49)
  at o.h.b.ethereum.trie.TrieIterator.visit(TrieIterator.java:98)
  at o.h.b.ethereum.trie.patricia.LeafNode.accept(LeafNode.java:75)
  at o.h.b.ethereum.trie.StoredNode.accept(StoredNode.java:67)
  at o.h.b.ethereum.trie.TrieIterator.visit(TrieIterator.java:82)
  at o.h.b.ethereum.trie.patricia.BranchNode.accept(BranchNode.java:85)
  [... more BranchNode/StoredNode traversal ...]
  at o.h.b.ethereum.trie.StoredMerkleTrie.entriesFrom(StoredMerkleTrie.java:164)
  at o.h.b.ethereum.trie.pathbased.bonsai.worldview.BonsaiWorldState.clearStorage(BonsaiWorldState.java:355)
  at o.h.b.ethereum.trie.pathbased.bonsai.worldview.BonsaiWorldState.internalCalculateRootHash(BonsaiWorldState.java:132)
  at o.h.b.ethereum.trie.pathbased.bonsai.worldview.BonsaiWorldState.calculateRootHash(BonsaiWorldState.java:123)
  at o.h.b.ethereum.trie.pathbased.bonsai.worldview.BonsaiWorldState.frontierRootHash(BonsaiWorldState.java:370)
  at o.h.b.ethereum.mainnet.MainnetProtocolSpecs$FrontierTransactionReceiptFactory.create(MainnetProtocolSpecs.java:1304)
  at o.h.b.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:360)
  at o.h.b.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:58)
  - locked <0x0000007001a181a8> (a MainnetBlockImporter)
```

### Minimal Reproducer (Unit Test)

The following test demonstrates the performance cliff without needing to sync:

```java
@ExtendWith(MockitoExtension.class)
class BonsaiClearStoragePerformanceTest {

  @Mock Blockchain blockchain;

  private static final Address CONTRACT =
      Address.fromHexString("0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef");

  /** 200 slots (single batch) — completes in ~28ms */
  @Test
  void frontierRootHash_singleBatch_completesQuickly() {
    MutableWorldState ws = createWorldStateWithStorage(200);
    ws.updater().getAccount(CONTRACT).clearStorage();
    ws.updater().commit();

    long start = System.nanoTime();
    Hash root = ws.frontierRootHash();
    long ms = (System.nanoTime() - start) / 1_000_000;

    assertThat(root).isNotNull();
    assertThat(ms).isLessThan(5_000);
    // Actual: ~28ms
  }

  /** 257 slots (2 batches) — does NOT complete within 10 seconds */
  @Test
  void frontierRootHash_multiBatch_hangs() {
    MutableWorldState ws = createWorldStateWithStorage(257);
    ws.updater().getAccount(CONTRACT).clearStorage();
    ws.updater().commit();

    CompletableFuture<Hash> future = CompletableFuture.supplyAsync(
        ws::frontierRootHash,
        r -> { Thread t = new Thread(r); t.setDaemon(true); t.start(); });

    Hash result = null;
    try { result = future.get(10, TimeUnit.SECONDS); }
    catch (Exception e) { /* Expected: TimeoutException */ }

    assertThat(result).as("257 slots should complete in 10s").isNull();
    // 200 slots: 28ms. 257 slots: >10 minutes. Same code path.
  }

  private MutableWorldState createWorldStateWithStorage(int slots) {
    var archive = InMemoryKeyValueStorageProvider
        .createBonsaiInMemoryWorldStateArchive(blockchain);
    MutableWorldState ws = archive.getWorldState();
    WorldUpdater setup = ws.updater();
    MutableAccount acct = setup.createAccount(CONTRACT);
    acct.setBalance(Wei.of(1));
    for (int i = 0; i < slots; i++)
      acct.setStorageValue(UInt256.valueOf(i), UInt256.valueOf(i + 1));
    setup.commit();
    ws.persist(null);
    return ws;
  }
}
```

### Verified On

| Version | Branch/Tag | Hangs? | Thread dump confirms same stack? |
|---------|-----------|--------|----------------------------------|
| 26.3-develop (`a8b8f4ee09`) | `main` | Yes | Yes |
| 26.1.0 | release tag | Yes | Yes |

Both tests were run on macOS with the same ETH mainnet DB synced up to block ~347,400. Both stalled at exactly block 347,480 (attempting to import 347,481).

### Versions

* **Software version:** Besu 26.1.0 and main (`a8b8f4ee09`)
* **Java version:** OpenJDK Temurin 21.0.9
* **OS:** macOS Darwin 25.3.0 (aarch64)
* **Consensus Client:** Teku 26.2.0 (with checkpoint sync)

### Contract Analysis

The contract at `0x5ee4861cDA18C9f5288391d209A2C4Ecab92dfD8` is an unverified early Ethereum tile game (Oct 2015). It had only 24 transactions and 297 storage slots. Full storage slot analysis via `trace_replayTransaction` stateDiff:

| TX | Function | New Slots | Total Unique |
|----|----------|-----------|--------------|
| 0 | CREATE | 2 | 2 |
| 1 | 0x5f264591 | 18 | 20 |
| 2 | buyTile | 0 | 20 |
| 3 | farmTile | 4 | 24 |
| 4-21 | 0x5f264591 (×18) | ~17 each | 280 |
| 22 | 0x6f366805 | 0 | 280 |
| 23 | kill() | 0 | **~297** |

297 slots is just 41 over the 256 batch boundary — enough to trigger the catastrophic second batch.

### Additional Information

* **Impact:** Makes `besu --sync-mode=FULL --data-storage-format=BONSAI` impossible on any Ethereum-derived network that includes block 347,481 (ETH mainnet, ETC, etc.).
* **Severity:** While SELFDESTRUCT was deprecated in Cancun (EIP-6780), this bug blocks full sync of **all historical blocks** on mainnet with the default Bonsai storage format. Any node operator attempting a full sync from genesis will be permanently stuck.

### PR DESCRIPTION
**Pull request by diega**
## PR description

`clearStorage()` iterates storage entries in batches of 256. After each batch, the original code always restarted from `Bytes32.ZERO`:

```java
entriesToDelete = storageTrie.entriesFrom(Bytes32.ZERO, 256);
```

Since removals are only applied to the in-memory trie (the persisted storage is unchanged), `entriesFrom(ZERO, 256)` keeps returning the same 256 entries indefinitely — infinite loop for any contract with >256 storage slots.

The fix advances the cursor past the last processed key:

```java
nextKeyHash = incrementBytes32(lastKeyHash);
entriesToDelete = storageTrie.entriesFrom(nextKeyHash, 256);
```

### Trace evidence

Instrumented `NodeLoader` to count trie node reads for both algorithms on the same world state (cap=100 restarts to prevent hang):

```
slots=200 | fix:      272 node loads | original:      272 node loads | ratio:   1.0x
slots=256 | fix:      349 node loads | original:   35,249 node loads | ratio: 101.0x  ← cliff
slots=257 | fix:      350 node loads | original:   35,350 node loads | ratio: 101.0x
slots=300 | fix:      413 node loads | original:   35,653 node loads | ratio:  86.3x
slots=512 | fix:      703 node loads | original:   35,754 node loads | ratio:  50.9x
```

Without the cap, the original algorithm loops forever — the ratio grows linearly with iterations (10 restarts → 11x, 100 → 101x, ∞ → hang).

<details>
<summary>Trace comparison test (not committed — for reviewer reference)</summary>

```java
@ParameterizedTest(name = "{1} — {0} slots")
@MethodSource("storageSlotCounts")
void compareNodeLoadsBetweenAlgorithms(int slotCount, String label) {
    long fixNodeLoads = measureNodeLoads_cursorAdvancement(slotCount);
    long originalNodeLoads = measureNodeLoads_restartFromZero(slotCount);

    System.out.printf("slots=%3d | fix: %,8d | original: %,8d | ratio: %.1fx%n",
        slotCount, fixNodeLoads, originalNodeLoads,
        (double) originalNodeLoads / fixNodeLoads);

    if (slotCount >= 256) {
        assertThat(originalNodeLoads).isGreaterThan(fixNodeLoads * 10);
    }
}

// Fixed algorithm: single trie, cursor advances via incrementBytes32
private long measureNodeLoads_cursorAdvancement(int slotCount) {
    // ... create world state with slotCount storage slots ...
    // Uses counting NodeLoader wrapper
    // Loop: entriesFrom(nextKeyHash, 256) → remove → advance cursor
}

// Original algorithm: re-creates trie from persisted root each iteration
private long measureNodeLoads_restartFromZero(int slotCount) {
    // ... same setup ...
    // Loop: new trie from persisted root → entriesFrom(ZERO, 256) → remove
    // Capped at 100 iterations to prevent hang
}
```

</details>

## Fixed Issue(s)

fixes #9963

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/besu-eth/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [x] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] spotless: `./gradlew spotlessApply`
- [x] unit tests: `./gradlew build`
- [x] acceptance tests: `./gradlew acceptanceTest`
- [x] integration tests: `./gradlew integrationTest`
- [x] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

**Comment by matkt** [comment]
I will take a look, please wait for my review

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiWorldState.java [hunk 1]
```diff
@@ -378,6 +389,21 @@ private void clearStorage(
     }
   }
 
+  private Optional<Bytes32> incrementBytes32(final Bytes32 value) {
```
Comment (matkt) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiWorldState.java]: is it possible to use something more cleaner

```java   
final UInt256 incremented = UInt256.fromBytes(value).add(UInt256.ONE);
    return incremented.isZero() ? Optional.empty() : Optional.of(incremented);
 ```

and maybe add test to verify the behavior when the last key is 0xff..ff (last batch size >= 256)

Comment (diega) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiWorldState.java]: Thanks for the review! It looks much cleaner now. Also added tests for both the normal case and the `0xFF...FF` overflow in `BonsaiWorldStateTest`. Amended the commit.

File: ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiClearStorageTest.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+    final CompletableFuture<Hash> future =
+        CompletableFuture.supplyAsync(
+            ws::frontierRootHash,
+            r -> {
+              final Thread t = new Thread(r);
+              t.setDaemon(true);
+              t.start();
+            });
+
+    final Hash root = future.get(10, TimeUnit.SECONDS);
```
Comment (matkt) [inline ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiClearStorageTest.java:92]: could you add a check in the keyvalue storage to be sure all the slot are really deleted ?

Comment (diega) [reply ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiClearStorageTest.java:92]: Done! Please take a look and let me know if it works for you.
