### PR TITLE
Fix eth/69 receipt encoding for Frontier tx

### LINKED ISSUE #10027: snap - client disconnecting server for Invalid response RESULTS_DO_NOT_MATCH_QUERY
it's the client that is disconnecting. server has this - so the disconnect is inbound

```
{"@timestamp":"2026-03-10T04:58:53,421","level":"DEBUG","thread":"nioEventLoopGroup-3-2","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 20 peers left","throwable":""}
```

client has
```
{"@timestamp":"2026-03-10T04:57:52,776","level":"DEBUG","thread":"EthScheduler-Services-58","class":"PeerTaskExecutor","message":"Invalid response RESULTS_DO_NOT_MATCH_QUERY found for GetSyncReceiptsFromPeerTask from peer 0x5b58ceb27c1ed7cb...","throwable":""}
{"@timestamp":"2026-03-10T04:57:52,777","level":"DEBUG","thread":"EthScheduler-Services-58","class":"PeerReputation","message":"Disconnection triggered by exceeding useless response threshold for peer 0x5b58ceb27c1ed7cb...","throwable":""}
{"@timestamp":"2026-03-10T04:57:52,777","level":"DEBUG","thread":"EthScheduler-Services-58","class":"AbstractPeerConnection","message":"Disconnecting connection -1866872816, peer 0x5b58ceb27c1ed7cb... reason 0x03 USELESS_PEER_USELESS_RESPONSES Useless responses: exceeded threshold","throwable":""}
{"@timestamp":"2026-03-10T04:57:52,777","level":"DEBUG","thread":"EthScheduler-Services-58","class":"EthPeers","message":"Disconnected USEFUL peer PeerId: 0x5b58ceb27c1ed7cb... PeerReputation score: 125, timeouts: {}, useless: 5, validated? true, disconnected? true, client: besu/v26.2.0/linux-aarch_64/openjdk-java-21, [Connection with hashCode -1866872816 inboundInitiated? true initAt 1773118671680], enode://5b58ceb27c1ed7cbcf6a41165a62c938f1f07421e2c1bd8cad16b717e51b463f823f6df1ae15feae17506a516f15f688eb63fc82d8a3f72df45460a95fa824e0@34.205.103.75:30303?discport=0, isServingSnap true, has height 2387951, connected for 1097 ms, capabilities: [eth/69, snap/1]","throwable":""}
{"@timestamp":"2026-03-10T04:57:52,777","level":"DEBUG","thread":"EthScheduler-Services-58","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Outbound - 0x03 USELESS_PEER_USELESS_RESPONSES Useless responses: exceeded threshold - 0x5b58ceb27c1ed7cb... besu/v26.2.0/linux-aarch_64/openjdk-java-21 - 0 peers left","throwable":""}
```

I just set up server 5b58ce
and client 70a1b
as static nodes. can see the disconnect is happening repeatedly.

recent server disconnects, grepping for the client:
```
{"@timestamp":"2026-03-10T05:06:54,335","level":"DEBUG","thread":"nioEventLoopGroup-3-9","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:07:49,550","level":"DEBUG","thread":"nioEventLoopGroup-3-8","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:07:53,520","level":"DEBUG","thread":"nioEventLoopGroup-3-7","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:08:48,536","level":"DEBUG","thread":"nioEventLoopGroup-3-5","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:08:53,726","level":"DEBUG","thread":"nioEventLoopGroup-3-1","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:09:48,833","level":"DEBUG","thread":"nioEventLoopGroup-3-4","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:09:52,790","level":"DEBUG","thread":"nioEventLoopGroup-3-6","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:10:50,133","level":"DEBUG","thread":"nioEventLoopGroup-3-7","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
{"@timestamp":"2026-03-10T05:10:53,173","level":"DEBUG","thread":"nioEventLoopGroup-3-10","class":"EthProtocolManager","message":"Disconnect - active Connection? true - Inbound - 0x03 USELESS_PEER Useless peer - 0x70a1b815cbd2bbdd... besu/v26.3-develop-db8af46/linux-aarch_64/openjdk-java-21 - 24 peers left","throwable":""}
```
grep "Disconnect - " /var/log/besu/besu.log | grep 70a1b
server is running besu/v26.2.0/linux-aarch_64/openjdk-java-21 so that's the most recent release

client

```
{"@timestamp":"2026-03-10T05:44:47,161","level":"DEBUG","thread":"EthScheduler-Services-116","class":"PeerTaskExecutor","message":"Invalid response RESULTS_DO_NOT_MATCH_QUERY found for GetSyncReceiptsFromPeerTask from peer 0x5b58ceb27c1ed7cb...","throwable":""}
{"@timestamp":"2026-03-10T05:44:47,161","level":"DEBUG","thread":"EthScheduler-Services-116","class":"PeerTaskExecutor","message":"Executed peer task GetSyncReceiptsFromPeerTask against 0x5b58ceb27c1ed7cb..., response code INVALID_RESPONSE, retries remaining 5","throwable":""}
{"@timestamp":"2026-03-10T05:44:47,167","level":"DEBUG","thread":"EthScheduler-Services-40","class":"PeerTaskExecutor","message":"Invalid response RESULTS_DO_NOT_MATCH_QUERY found for GetSyncReceiptsFromPeerTask from peer 0x5b58ceb27c1ed7cb...","throwable":""}
{"@timestamp":"2026-03-10T05:44:47,167","level":"DEBUG","thread":"EthScheduler-Services-40","class":"PeerTaskExecutor","message":"Executed peer task GetSyncReceiptsFromPeerTask against 0x5b58ceb27c1ed7cb..., response code INVALID_RESPONSE, retries remaining 5","throwable":""}
{"@timestamp":"2026-03-10T05:44:47,170","level":"DEBUG","thread":"EthScheduler-Services-117","class":"PeerTaskExecutor","message":"Invalid response RESULTS_DO_NOT_MATCH_QUERY found for GetSyncReceiptsFromPeerTask from peer 0x5b58ceb27c1ed7cb...","throwable":""}
{"@timestamp":"2026-03-10T05:44:47,171","level":"DEBUG","thread":"EthScheduler-Services-117","class":"PeerTaskExecutor","message":"Executed peer task GetSyncReceiptsFromPeerTask against 0x5b58ceb27c1ed7cb..., response code INVALID_RESPONSE, retries remaining 5","throwable":""}
{"@timestamp":"2026-03-10T05:44:47,209","level":"DEBUG","thread":"EthScheduler-Services-53","class":"PeerTaskExecutor","message":"Invalid response RESULTS_DO_NOT_MATCH_QUERY found for GetSyncReceiptsFromPeerTask from peer 0x5b58ceb27c1ed7cb...","throwable":""}
```

### PR DESCRIPTION
**Pull request by macfarla**
## PR description
  The Problem

  Besu-to-Besu snap sync was failing for small networks. The CliqueToPoSTest acceptance test (snap sync section) would hang and never complete because receipt downloads kept failing with RECEIPTS_ROOT_MISMATCH.

  Root Cause

  A bug in SyncTransactionReceiptEncoder.encodeForRootCalculation() when using eth/69 protocol.

  eth/69 sends receipts without bloom filters. The receiving node must re-encode them with bloom for receipt root calculation. The encoder checked if a receipt was Frontier type using:
  TransactionType.FRONTIER.getSerializedType()  // returns 0xf8
  But eth/69's decoder stores Frontier type code as 0x00 (getEthSerializedType()). So Frontier receipts were never detected as Frontier, causing them to be incorrectly prefixed with 0x00 during encoding, producing a wrong receipt
  trie root.

  The Fix (SyncTransactionReceiptEncoder.java)

```
  Changed the isFrontier check to handle both representations:
  final boolean isFrontier =
      receipt.getTransactionTypeCode().isEmpty()
          || receipt.getTransactionTypeCode().get(0)
              == TransactionType.FRONTIER.getEthSerializedType()   // 0x00
          || receipt.getTransactionTypeCode().get(0)
              == TransactionType.FRONTIER.getSerializedType();     // 0xf8
```

  Additional Fix (RequestManager.java)

  Found and fixed an outstanding request capacity leak - both dispatchResponse() and close() could decrement the counter for the same request. Fixed with a CAS-based AtomicBoolean to ensure exactly-once release semantics.

  Other Changes

  - ProcessBesuNodeRunner.java - Added --Xsynchronizer-pivot-distance CLI passthrough so acceptance tests can configure pivot distance
  - CliqueToPoSTest.java - The acceptance test with snap sync validation
  - RequestManagerTest.java - Unit tests for the CAS fix

  Why It Was Hard to Find

  - The symptom (peer disconnections after ~5 second gaps) was misleading - it was a consequence of receipt validation failures exhausting retry limits, not a networking issue
  - Subprocess logs don't appear in gradle console output; they're captured in JUnit XML test result files
  - The TransactionType.FRONTIER has confusingly named methods: getSerializedType() returns 0xf8 (the typeValue), while getEthSerializedType() returns 0x00 (the serializedType)

## Fixed Issue(s)
fixes #10027
note this PR also includes the rlp logging change from #10038 which was needed to diagnose #10044 

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] spotless: `./gradlew spotlessApply`
- [x] unit tests: `./gradlew build`
- [x] acceptance tests: `./gradlew acceptanceTest`
- [x] integration tests: `./gradlew integrationTest`
- [x] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: acceptance-tests/tests/src/acceptanceTest/java/org/hyperledger/besu/tests/acceptance/clique/CliqueToPoSTest.java [hunk 1]
```diff
@@ -0,0 +1,390 @@
...
+    cluster.addNode(syncNodeSnap);
+
+    syncNodeSnap.awaitPeerDiscovery(net.awaitPeerCount(2));
+
+    // A single forkchoiceUpdatedV1 pointing at head kicks off snap sync to pivot;
+    // syncNodeSnap does not have the block yet so it responds SYNCING and begins downloading
+    triggerSyncViaForkchoiceUpdate(syncNodeSnap, headHash);
+
+    // Wait for snap sync to complete and verify the full chain is present
+    syncNodeSnap.verify(blockchain.minimumHeight(10, 300));
```
Comment (pinges) [inline acceptance-tests/tests/src/acceptanceTest/java/org/hyperledger/besu/tests/acceptance/clique/CliqueToPoSTest.java]: 300 seconds is 5 minutes. Does it take that long, or is that only very conservative?

File: acceptance-tests/tests/src/acceptanceTest/resources/clique/clique_to_pos.json [hunk 2]
```diff
@@ -0,0 +1,48 @@
+{
+  "config": {
+    "chainId": 4,
```
Comment (pinges) [inline acceptance-tests/tests/src/acceptanceTest/resources/clique/clique_to_pos.json:3]: Isn't that one of the testnet chain ids?

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/receipt/SyncTransactionReceiptEncoder.java [hunk 3]
```diff
@@ -33,8 +33,10 @@ public SyncTransactionReceiptEncoder(final SimpleNoCopyRlpEncoder rlpEncoder) {
 
   public Bytes encodeForRootCalculation(final SyncTransactionReceipt receipt) {
     final boolean isFrontier =
-        !receipt.getTransactionTypeCode().isEmpty()
-            && receipt.getTransactionTypeCode().get(0)
+        receipt.getTransactionTypeCode().isEmpty()
+            || receipt.getTransactionTypeCode().get(0)
+                == TransactionType.FRONTIER.getEthSerializedType()
```
Comment (pinges) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/receipt/SyncTransactionReceiptEncoder.java]: I think that it would be enough to check the getEthSerializedType here ...

File: acceptance-tests/tests/src/acceptanceTest/resources/clique/clique_to_pos.json (hunk 2 above)
Comment (macfarla) [reply acceptance-tests/tests/src/acceptanceTest/resources/clique/clique_to_pos.json:3]: yes it is rinkeby. However this can't be changed without regenerating the clique.blocks file since chain ID 4 is baked into the pre-built block data.

File: acceptance-tests/tests/src/acceptanceTest/java/org/hyperledger/besu/tests/acceptance/clique/CliqueToPoSTest.java (hunk 1 above)
Comment (macfarla) [reply acceptance-tests/tests/src/acceptanceTest/java/org/hyperledger/besu/tests/acceptance/clique/CliqueToPoSTest.java]: reduced to 120 but it normally completes within 90

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/receipt/SyncTransactionReceiptEncoder.java (hunk 3 above)
Comment (macfarla) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/receipt/SyncTransactionReceiptEncoder.java]: changing this

**Comment by macfarla** [comment]
SyncTransactionReceiptEncoder was introduced in #9621

**Comment by macfarla** [comment]
Tested on Hoodi testnet with a two-node setup (client + server), both running v26.3-develop.

  Before (client without #9900, server with or without #9900)

  The client repeatedly rejects receipts from the server as RESULTS_DO_NOT_MATCH_QUERY — the receipt trie root computed locally doesn't match the block header, due to incorrect handling of Frontier-type receipts in encodeForRootCalculation. After 5 failures the peer is disconnected as "useless", and the cycle repeats on reconnect.

  Observed against both a 26.2.0 server and a 26.3-develop server with #9900:

```
  PeerTaskExecutor: Invalid response RESULTS_DO_NOT_MATCH_QUERY found for GetSyncReceiptsFromPeerTask from peer 0x13812e3c...
  PeerTaskExecutor: Executed peer task GetSyncReceiptsFromPeerTask against 0x13812e3c..., response code INVALID_RESPONSE, retries remaining 4
  PeerTaskExecutor: Invalid response RESULTS_DO_NOT_MATCH_QUERY found for GetSyncReceiptsFromPeerTask from peer 0x13812e3c...
  PeerReputation: Disconnection triggered by exceeding useless response threshold for peer 0x13812e3c...
  AbstractPeerConnection: Disconnecting connection -481815964, peer 0x13812e3c... reason 0x03 USELESS_PEER_USELESS_RESPONSES Useless responses: exceeded threshold
  EthPeers: Disconnected EthPeer 0x13812e3c...
  EthProtocolManager: Disconnect - active Connection? true - Outbound - 0x03 USELESS_PEER_USELESS_RESPONSES - besu/v26.2.0/linux-aarch_64/openjdk-java-21 - 0 peers left
```

  The node cannot make sync progress — it disconnects every peer serving blocks with legacy transactions.

  After (client with #9900)

  The client correctly validates receipts, stays connected, and snap sync progresses steadily:

```
  PeerTaskExecutor: Executed peer task GetSyncReceiptsFromPeerTask against 0xbfae3dad..., response code SUCCESS, retries remaining 5
  SnapSyncMetricsManager: Worldstate download progress: 18.09%, Peer count: 1
  SnapSyncMetricsManager: Worldstate download progress: 19.83%, Peer count: 1
  SnapSyncMetricsManager: Worldstate download progress: 21.57%, Peer count: 1
```

  No RESULTS_DO_NOT_MATCH_QUERY, no peer disconnections. Worldstate advancing ~1.7%/min with a single peer.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java [hunk 4]
```diff
@@ -439,7 +439,17 @@ public Optional<DisconnectReason> gatePeerConnection(final Peer peer, final bool
     }
 
     final Bytes id = peer.getId();
-    if (alreadyConnectedOrConnecting(inbound, id)) {
+    final EthPeer existingPeer = activeConnections.get(id);
```
Comment (pinges) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java]: I'm not sure about this.  The logic in the `else if()` does the opposite, it disconnects the newer connection, and that is what we have done for a while now and that seems to work. 
I think we should leave it as it was, or we should at least analyze which approach works better.

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/peertask/task/GetSyncReceiptsFromPeerTaskTest.java [hunk 5]
```diff
@@ -424,6 +426,46 @@ public void validateResultFailsReceiptRootDoesNotMatch() {
                 List.of())));
   }
 
+  @Test
+  public void validateResultPassesForFrontierReceiptsAfterDecoderRoundTrip() {
+    // Regression test: Frontier receipts received over eth/69 were decoded by
+    // SyncTransactionReceiptDecoder into SyncTransactionReceipt with transactionTypeCode=0x00
+    // (getEthSerializedType). SyncTransactionReceiptEncoder.encodeForRootCalculation only checked
+    // for 0xf8 (getSerializedType) as the Frontier marker, so 0x00 was treated as a non-Frontier
```
Comment (pinges) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/peertask/task/GetSyncReceiptsFromPeerTaskTest.java]: Not sure we want to have that information about the bug here in the test

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/peertask/task/GetSyncReceiptsFromPeerTaskTest.java [hunk 6]
```diff
@@ -424,6 +426,46 @@ public void validateResultFailsReceiptRootDoesNotMatch() {
...
+    // toResponseReceipt() uses the single-arg constructor (rlpBytes only), so all existing tests
+    // bypass encodeForRootCalculation entirely. This test exercises the real eth/69 decode path.
+    final MockedBlock block = mockBlock(1, 2);
+
+    final GetSyncReceiptsFromPeerTask task =
+        createTask(new Request(List.of(block.block), List.of()), protocolSchedule);
+
+    // Encode in eth/69 format: [typeCode(0x00), status, cumulativeGas, logs] (no bloom filter).
+    // The decoder routes this to decodeEth69Receipt, stores typeCode=Bytes.of(0x00), and sets
+    // isFormattedForRootCalculation=false — so encodeForRootCalculation is invoked.
```
Comment (pinges) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/peertask/task/GetSyncReceiptsFromPeerTaskTest.java]: s.a.

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeersTest.java [hunk 7]
```diff
@@ -487,4 +488,44 @@ private void assertNotDone(final PendingPeerRequest pendingRequest) {
...
+
+    // New inbound connection should be allowed
+    assertThat(result).isEmpty();
+    // Stale existing connection should have been disconnected
+    assertThat(oldConnection.isDisconnected()).isTrue();
+  }
+
+  @Test
+  public void shouldRejectOutboundConnectionWhenAlreadyConnected() {
+    // When WE try to connect outbound to a peer we already have in activeConnections,
```
Comment (pinges) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeersTest.java]: I don't think that comment makes sense here in the test.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java (hunk 4 above)
Comment (macfarla) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java]: this is PR #10041 so no longer in this for review

**Review by pinges — APPROVED** [review]
LGTM
