### PR TITLE
fix issue because parent world state is not available

### LINKED ISSUE #4052: Unable to process block because parent world state is not available
I ran into this error with ropsten-lodestar-besu, with besu on a commit from the main branch pushed within the last few days, and besu was unable to recover until I deleted the besu database and resynced.

```
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:214)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:256)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:277)
        at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:137)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:185)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:62)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-07-03 06:46:59.794-04:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Unable to process block because parent world state 0xea0a5af970e850f4760cd610a4bc1f741654f37cee92b9b630a7a733338dbb53 is not available. Block 12515901 (0x59c7b67917e9cc703e2887c03b1228f0f8b41da634f2a61b35df0219309990d0)
2022-07-03 06:46:59.795-04:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Invalid new payload: number: 12515901, hash: 0x59c7b67917e9cc703e2887c03b1228f0f8b41da634f2a61b35df0219309990d0, parentHash: 0xc628202a04d296e51193571a60d786614014daaa4f30c492e9c2d1fd01d0f879, latestValidHash: 0xc628202a04d296e51193571a60d786614014daaa4f30c492e9c2d1fd01d0f879, status: INVALID, validationError: Unable to process block because parent world state 0xea0a5af970e850f4760cd610a4bc1f741654f37cee92b9b630a7a733338dbb53 is not available
```

### LINKED ISSUE #4068: Prior Value in Rolling Change: nonces differ
Seeing this IllegalStateException on latest besu 22.7.0-RC1 on goerli canary (fast sync, bonsai, from scratch)

LOGS
```{"@timestamp":"2022-07-06T16:01:56,567","level":"INFO","thread":"EthScheduler-Workers-0","class":"BlockPropagationManager","message":"Imported 1 pending blocks","throwable":""}
{"@timestamp":"2022-07-06T16:02:01,016","level":"INFO","thread":"Timer-0","class":"DNSTimerTask","message":"Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.goerli.ethdisco.net","throwable":""}
{"@timestamp":"2022-07-06T16:02:06,309","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #7,180,290 / 9 tx / 0 om / 4,224,326 (14.1%) gas / (0xb70f501043b17794d75447fb9996030647151f1fc7c0a28a1ab0a5dcf02c212b) in 0.153s. Peers
: 72","throwable":""}
java.lang.RuntimeException: java.lang.IllegalStateException: Address=0xa550511f2093dbef0e277ec1b216849d4d73bf1a Prior Value in Rolling Change: nonces differ
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:254)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:71)
        at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:44)
        at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
        at org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask.executeTask(PersistBlockTask.java:201)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:150)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.run(AbstractEthTask.java:75)
        at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.runImportTask(BlockPropagationManager.java:487)
        at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.validateAndProcessPendingBlock(BlockPropagationManager.java:468)
        at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.lambda$importOrSavePendingBlock$17(BlockPropagationManager.java:456)
        at org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:97)
        at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleSyncWorkerTask$0(EthScheduler.java:108)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Address=0xa550511f2093dbef0e277ec1b216849d4d73bf1a Prior Value in Rolling Change: nonces differ
        at org.hyperledger.besu.ethereum.bonsai.BonsaiAccount.assertCloseEnoughForDiffing(BonsaiAccount.java:303)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollAccountChange(BonsaiWorldStateUpdater.java:497)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.lambda$rollBack$13(BonsaiWorldStateUpdater.java:447)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollBack(BonsaiWorldStateUpdater.java:445)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:239)
        ... 17 more
{"@timestamp":"2022-07-06T16:02:06,684","level":"ERROR","thread":"EthScheduler-Workers-0","class":"MainnetBlockValidator","message":"Unable to process block because parent world state 0x3c111c8df49432fbcb5cc316548a1178410c521f7806d099eabe35b5920e7ac5 is not available. Block 7180287 (0x651751749dad691a615d650461944b2696a9e7059216266967399792752dd0b1)","throwable":""}
{"@timestamp":"2022-07-06T16:02:06,685","level":"WARN","thread":"EthScheduler-Workers-0","class":"BlockPropagationManager","message":"Failed to import announced block 7180287 (0x651751749dad691a615d650461944b2696a9e7059216266967399792752dd0b1)","throwable":""}
java.lang.RuntimeException: java.lang.IllegalStateException: Address=0xa550511f2093dbef0e277ec1b216849d4d73bf1a Prior Value in Rolling Change: nonces differ
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:254)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:71)
        at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:44)
        at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
        at org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask.executeTask(PersistBlockTask.java:201)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:150)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.run(AbstractEthTask.java:75)
        at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.runImportTask(BlockPropagationManager.java:487)
        at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.validateAndProcessPendingBlock(BlockPropagationManager.java:468)
        at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.lambda$importOrSavePendingBlock$17(BlockPropagationManager.java:456)
        at org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:97)
        at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleSyncWorkerTask$0(EthScheduler.java:108)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Node does not recover
```
        ... 17 more
{"@timestamp":"2022-07-06T16:02:16,063","level":"ERROR","thread":"EthScheduler-Workers-3","class":"MainnetBlockValidator","message":"Unable to process block because parent world state 0xe80ffa90064b2135e93a06afaefba7ffae7554e77ce3d5f4e64150f7f5f320af is not available. Blo
ck 7180285 (0x0868c83578e6eac93e138f6ba27bbbb88fa295fe2f0efb9534308332d581fbda)","throwable":""}
{"@timestamp":"2022-07-06T16:02:16,063","level":"WARN","thread":"EthScheduler-Workers-3","class":"BlockPropagationManager","message":"Failed to import announced block 7180285 (0x0868c83578e6eac93e138f6ba27bbbb88fa295fe2f0efb9534308332d581fbda)","throwable":""}
java.lang.RuntimeException: java.lang.IllegalStateException: Address=0xa550511f2093dbef0e277ec1b216849d4d73bf1a Prior Value in Rolling Change: nonces differ
```
And eventually there's an invalid block
```

        ... 13 more
{"@timestamp":"2022-07-07T05:01:51,989","level":"ERROR","thread":"EthScheduler-Services-183 (importBlock)","class":"MainnetBlockValidator","message":"Unable to process block because parent world state 0x0ef0262e5aca01ca9dbf1281a1e189a25dca4af1ad8d390a5ca197cd9ec5e0e9 is not available. Block 7180291 (0xc9efc909fcf9ba5a34653cb0e2e07bbaaf4d61b539fd1cb9287bb1ae759f1c39)","throwable":""}
{"@timestamp":"2022-07-07T05:01:51,990","level":"WARN","thread":"EthScheduler-Services-183 (importBlock)","class":"PipelineChainDownloader","message":"Invalid block detected. Disconnecting from sync target. Failed to import block: Invalid block at #7180291 (0xc9efc909fcf9ba5a34653cb0e2e07bbaaf4d61b539fd1cb9287bb1ae759f1c39)","throwable":""}
{"@timestamp":"2022-07-07T05:01:51,990","level":"WARN","thread":"EthScheduler-Services-183 (importBlock)","class":"PipelineChainDownloader","message":"Chain download failed. Restarting after short delay.","throwable":" java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #7180291 (0xc9efc909fcf9ba5a34653cb0e2e07bbaaf4d61b539fd1cb9287bb1ae759f1c39)\n\tat java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)\n\tat java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)\n\tat java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)\n\tat org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)\n\tat org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #7180291 (0xc9efc909fcf9ba5a34653cb0e2e07bbaaf4d61b539fd1cb9287bb1ae759f1c39)\n\tat org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:62)\n\tat org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)\n\tat org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)\n\tat org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)\n\t... 5 more\n"}
```

### PR DESCRIPTION
**Pull request by matkt**
Signed-off-by: Karim TAAM <karim.t2am@gmail.com>

## PR description

We have this issue because we are replacing valid trielog by invalid trielog during a reorg. 

Can explain this strange trie log layer

>  : 0xd77f7f8868f20835fdfc8c7e851f6f23ce9f651d
   - StateTrieAccountValue{nonce=859, balance=0x00000000000000000000000000000000000000000000000006d141b0befb39fe, storageRoot=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, codeHash=0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470}
   + StateTrieAccountValue{nonce=858, balance=0x00000000000000000000000000000000000000000000000006e96a274881e7b6, storageRoot=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, codeHash=0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470}

The nonce comes from 859 to 858 and it’s not possible in a normal use case. 

### How to reproduce it (it's an example)

- We import block 5. we create a trie log for this block (4->5). A trie log it’s a diff between the previous block and the last one
- We import block 6 bis. we create a trie log for this block (5->6bis)
- We import block 7 bis. we create a trie log for this block (6bis->7bis)
- We detect a reorg with 6third with a common ancestor == 4. Rollback to 4 and we persist block 4. But in this issue we replace the valid trie log layer (3-4) with an invalid trie log (7bis->4)
- We import block 5 third. we create a trie log for this block (5 third ->6 third)
- We import block 6 third. we create a trie log for this block (6 third ->7 third)
- We detect a reorg with 6 with a common ancestor == 3. Rollback to 3 is failing because of the trie log == (7bis->4). 

In the code the problem is here

We persist after a rollback/rollfoward https://github.com/hyperledger/besu/blob/main/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchive.java#L247

We replace the trie log 
https://github.com/hyperledger/besu/blob/e79cf0e50724d7b5203708bf6b7abc24524f3dcb/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiPersistedWorldState.java#L257

⚠️ if we have this issue we need to resync besu . there is not way to recover

## Fixed Issue(s)

fixes #4068 
fixes #4052

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

File: ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java [hunk 1]
```diff
@@ -200,4 +201,58 @@ public void testGetMutableWithStorageConsistencyToRollbackAndRollForwardTheState
...
+    // fake trie log layer
+    final BytesValueRLPOutput rlpLogBlockA = new BytesValueRLPOutput();
+    final TrieLogLayer trieLogLayerBlockA = new TrieLogLayer();
+    trieLogLayerBlockA.setBlockHash(blockHeaderChainA.getHash());
+    trieLogLayerBlockA.writeTo(rlpLogBlockA);
+    final BytesValueRLPOutput rlpLogBlockB = new BytesValueRLPOutput();
+    final TrieLogLayer trieLogLayerBlockB = new TrieLogLayer();
+    trieLogLayerBlockB.setBlockHash(blockHeaderChainB.getHash());
+    trieLogLayerBlockB.writeTo(rlpLogBlockB);
+    when(keyValueStorage.get(blockHeaderChainA.getHash().toArrayUnsafe()))
```
Comment (macfarla) [inline ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java:240]: unit test failure is unnecessary mockito stubbings here

**Review by macfarla — APPROVED** [review]
Looks ok to me although I'm not a bonsai expert!

File: ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java (hunk 1 above)
Comment (matkt) [reply ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java]: fixed thanks

File: CHANGELOG.md [hunk 2]
```diff
@@ -20,6 +19,7 @@
 - Support free gas networks in the London fee market [#4003](https://github.com/hyperledger/besu/pull/4003)
 - Limit the size of outgoing eth subprotocol messages.  [#4034](https://github.com/hyperledger/besu/pull/4034)
 - Fixed a state root mismatch issue on bonsai that may appear occasionally [#4041](https://github.com/hyperledger/besu/pull/4041)
+- Fixed a trie log layer issue on bonsai during reorg [#4069](https://github.com/hyperledger/besu/pull/4069)
```
[the remark this answers is not in the document]
Comment (matkt) [reply CHANGELOG.md]: done thanks
