### PR TITLE
attempt fix for flaky test

### LINKED ISSUE #7150: Flaky test - LondonFeeMarketBlockTransactionSelectorTest. invalidPendingTransactionsThatTakesTooLongToEvaluateIsDroppedFromThePool
Flaky test observed in one of the PRs

https://github.com/hyperledger/besu/actions/runs/9267287373/job/25493482107?pr=7129

```
> Task :ethereum:blockcreation:test

LondonFeeMarketBlockTransactionSelectorTest > invalidPendingTransactionsThatTakesTooLongToEvaluateIsDroppedFromThePool(boolean, boolean, boolean, boolean) > [1] false, true, false, false FAILED
    org.opentest4j.AssertionFailedError at NativeConstructorAccessorImpl.java:-2
```

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
## PR description
Claude's reasoning is that this handles Race Conditions: Instead of immediately asserting that tecIsCancelled is true, we now wait up to 500ms for the cancellation state to propagate through the system

## Fixed Issue(s)
Fixes #7150 

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

**Comment by macfarla** [comment]
argh this has flaked on an ACCEPTANCE test https://github.com/hyperledger/besu/actions/runs/19559475736/job/56008879889?pr=9482

```
BesuEventsPluginTest > blockIsAdded() FAILED
    org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.hyperledger.besu.tests.acceptance.dsl.AcceptanceTestBase was not fulfilled within 30 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1129)
        at app//org.hyperledger.besu.tests.acceptance.dsl.AcceptanceTestBase.waitForFile(AcceptanceTestBase.java:205)
        at app//org.hyperledger.besu.tests.acceptance.plugins.BesuEventsPluginTest.blockIsAdded(BesuEventsPluginTest.java:46)
```

File: ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java [hunk 1]
```diff
@@ -1539,7 +1538,7 @@ private void internalBlockSelectionTimeoutSimulationInvalidTxs(
         .containsExactlyInAnyOrderEntriesOf(expectedEntries);
 
     assertThat(transactionPool.getTransactionByHash(lateTx.getHash()).isEmpty())
-        .isEqualTo(isLongProcessingTxDropped ? true : false);
+        .isEqualTo(isLongProcessingTxDropped);
```
Comment (jframe) [inline ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java:1541]: Don't understand why `.isEqualTo(isLongProcessingTxDropped ? true : false)` was changed to `.isEqualTo(isLongProcessingTxDropped)`.

Comment (macfarla) [reply ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockTransactionSelectorTest.java:1541]: that was just cleaning up - it's equivalent - if `x=true ? true : false` is the same as `if x`
