### PR TITLE
Fix banning (static peers) because of late response in eth/66

### LINKED ISSUE #4320: Do not ban (static) peers for late responses
## Usecase
(same backstory as #3801) I want to sync my Besu node against a single local (Geth) node, and not connect to the wider internet. The Besu node is in the `trusted-nodes.json` file of Geth, and the Geth node is in the `static-nodes.json` of Besu. 

For completeness sake, my command line is `./besu --data-storage-format=bonsai --p2p-port=30303 --sync-mode=FAST --fast-sync-min-peers=1 --discovery-enabled=false` (same behavior with `X_SNAP`)

## Issue
(Possibly related to #4294)
When using the command line above, I eventually get a situation where Geth takes _slightly_ too long to respond, e.g. 5.1 seconds. Besu has already considered the request to be timed out, and severely punishes the peer by disconnecting right away with `BREACH_OF_PROTOCOL`. It also never reconnects to it (which is unlike Geth/Nethermind, at least for static nodes).

The offending bit of code is https://github.com/hyperledger/besu/blob/113bd54c6b0ff748a3ed23f2e89fa31a4cb73795/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/RequestManager.java#L70-L93

I reproduced this issue on Besu/Geth/Nethermind by slightly [modifying Geth ](https://github.com/ethereum/go-ethereum/compare/master...pietjepuk2:go-ethereum:sometimes-delay-response-trusted-nodes) to delay the response to the Nth GetHeaders request.

## Other clients behavior
- Geth doesn't disconnect on late replies. It does requests sequentially it seems, and just waits with sending a new request until it gets a response (waits more than 10 seconds at least). If I delay the response with a minute, Geth just disconnects the peer after ~40-50 seconds before reconnecting to it a few seconds later.
- Nethermind is a bit weird in that it continuously disconnects and reconnects every minute or so. It doesn't punish a late response (>5 seconds), but either way always reconnects.
- (Not entirely sure). Late responses were probably not punished by Besu with Eth65 (i.e. no `RequestId`). I couldn't quite understand the code (or test it), but my gut feeling is that it just skipped processing the late response or handled it anyway.

## Suggested solutions
1. Just `LOG.debug("Request ID incorrect (BREACH_OF_PROTOCOL), disconnecting peer {}", peer);` but don't disconnect the peer. Maybe decrease peer reputation.
2. Keep track of timed-out request ids, and if response is in one of them -> ignore. If it's not -> disconnect.

## Sidenotes
- Even after disconnecting, whether it be "BREACH_OF_PROTOCOL" or because the reputation dropped too low, I would expect Besu to reconnect to static nodes regardless. Other clients seem to do so anyway.
- I have at least one logging of Besu receiving a response _barely_ within 5 seconds (in `RequestManager`), but `AbstractPeerRequestTask` still timing out on it ~200 ms later. The processing or delay on Besu's side surely shouldn't be part of the 5 seconds timeout window?

### PR DESCRIPTION
**Pull request by pietjepuk2**
## PR description

- The RequestManager commit that lessens the penalty should be somewhat straightforward. A late response is typically already punished with a timeout before (too many of which and we disconnect). Instead of immediately considering a late response a breach of protocol, we just consider it useless (again, too many of which and we disconnect).

- The not banning of maintained/static peers was a bit more difficult. I'm not sure if this is the right^TM way to do it, but a Peer object has no notion of it being static/maintained. And static nodes are also not instantiated in a single call, they are combined with bootnodes. So adding a `isStatic` field to EthPeer also seemed more trouble than it was worth. Therefore I settled on this solution, but there might be a better/simpler/more elegant one.

Feedback more than welcome!

## Fixed Issue(s)

Fixes #4320
Related to #4294

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

## TODO before merging
- [x] Elaborate RequestManager commit message
- [x] Elaborate in PeerDenylistManager commit message
- [x] Fix test cases PeerDenylistManager 
- [x] Add test case (with maintained/static peer) for PeerDenylistManager 
- [x] run spotlessApply to fix formatting issues

### CODE REVIEW

File: ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/PeerDenylistManager.java [hunk 1]
```diff
@@ -46,8 +50,12 @@ public void onDisconnect(
       final DisconnectReason reason,
       final boolean initiatedByPeer) {
     if (shouldBlock(reason, initiatedByPeer)) {
-      LOG.debug("Added peer {} to peer denylist for reason {}", connection, reason.name());
-      denylist.add(connection.getPeer());
+      if (maintainedPeers.contains(connection.getPeer())) {
+        LOG.debug("Skip adding maintained peer {} to denylist for reason {}", connection, reason.name());
```
Comment (pietjepuk2) [inline ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/PeerDenylistManager.java:54]: the other log message has "to _peer_ denylist", not "to denylist". Or just different wording in general, as this is a bit awkward.

Comment (jflo) [reply ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/PeerDenylistManager.java:54]: I don't see anywhere that maintainedPeers gets called outside of a test class. It is possible this is dead code. You seem to be under the impression that this is where static peers are maintained, which seems reasonable to me... I just don't see any way to prove it.

**Review by jflo — APPROVED** [review]
This looks good, and should help non-static peers as well.

**Comment by macfarla** [comment]
@jflo one place maintainedPeers is used is in RlpxAgent - maintained peers are allowed to push the number of connections over maxPeers https://github.com/hyperledger/besu/blob/16922cac83f27327c4979bd8def12679086074a8/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/RlpxAgent.java#L239

**Comment by macfarla** [comment]
and @pietjepuk2 you'll need to run spotlessApply to fix some formatting issues :)
