### PR TITLE
Promote segmented storage

### LINKED ISSUE #5362: Clean shutdown
### Description
Shutdowns with SEGFAULT and OOM can cause corrupted databases and rocksDB BUSY/LOCK. 

Need to gather information on what areas of improvement are available to us. 

To-Do:
- [ ] Look into rocksDB shut-down with atomic transactions for flatDB and trie **OR**
- [ ] Determine if we can commit some/all column families at the same time (see [here](https://github.com/hyperledger/besu/issues/5362#issuecomment-1594812509))

### PR DESCRIPTION
**Pull request by garyschulte**
## PR description
At a high level, this PR promotes SegmentedKeyValueStorage into the plugin-api for storage.  

The primary benefit of this besides addressing tech debt is that we can directly use segmented storage and atomically commit across multiple segments.  This is mainly beneficial for bonsai worldstate, which comprises four separate key value store segments.  

This is motivated by "unclean" worldstate storage that can result from besu app or the host machine crashing for a variety of reasons.  RocksDB handles unclean shutdowns very well, but if the besu application was in the midst of a worldstate commit, each of the individual worldstate storages might be in different states of commit/rollback at the time of the crash.  By having composed storage, we can rely on the guarantees of rocksdb to atomically commit or rollback changes in the event of a crash or halt, like what resulted in #5576 

## Fixed Issue(s)

fixes #5362 #5576

### CODE REVIEW

File: ethereum/core/src/test/java/org/hyperledger/besu/ethereum/worldstate/MarkSweepPrunerTest.java [hunk 1]
```diff
@@ -147,7 +147,8 @@ public void sweepBefore_shouldSweepStateRootFirst() {
     stateRoots.forEach(
         stateRoot -> {
           final InOrder thisRootsOrdering = inOrder(hashValueStore, worldStateStorage);
-          thisRootsOrdering.verify(hashValueStore).remove(stateRoot);
+          // disable this validation since the underlying storage no longer directly uses .remove()
+          // thisRootsOrdering.verify(hashValueStore).remove(stateRoot);
```
Comment (garyschulte) [inline ethereum/core/src/test/java/org/hyperledger/besu/ethereum/worldstate/MarkSweepPrunerTest.java:151]: looking for feedback here - do we care to jump through hoops to keep the pruning tests passing when pruning is a deprecated feature?

File: plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBTransaction.java [hunk 2]
```diff
@@ -0,0 +1,121 @@
+/*
+ * Copyright ConsenSys AG.
```
Comment (daniellehrner) [inline plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBTransaction.java:2]: The copyright should be changed to Hyperledger Contributors

File: ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java [hunk 3]
```diff
@@ -15,272 +15,279 @@
...
-import org.junit.Before;
-import org.junit.Ignore;
-import org.junit.Test;
-import org.junit.runner.RunWith;
-import org.mockito.Mock;
-import org.mockito.Mockito;
-import org.mockito.junit.MockitoJUnitRunner;
-
-@RunWith(MockitoJUnitRunner.class)
+// import static org.assertj.core.api.Assertions.assertThat;
```
Comment (daniellehrner) [inline ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java:18]: Everything is this file is commented out. So it should be safe to delete it. Or are those tests only temporarily commented out?

**Review by daniellehrner — CHANGES_REQUESTED** [review]

File: ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java (hunk 3 above)
Comment (garyschulte) [reply ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateArchiveTest.java:18]: Thanks, I missed this one since it was collapsed in the default view.  refactored and re-added.

**Review by daniellehrner — APPROVED** [review]
