### PR TITLE
Layered txpool reconcile sender

### LINKED ISSUE #5447: Layered TxPool: IndexOutOfBoundsException: Index 275 out of bounds for length 100
### Description

There is a corner case is the new Layered TxPool that triggers an `IndexOutOfBoundsException`, that happens when a block is being imported and an account nonce is updated in the world state, before the imported block is processed by the txpool, that could cause a nonce discrepancy for txs that arrive during that short period of time with a sender that also has confirmed txs in the imported block.
The effect of this exception is to leave the txpool for that sender in an inconsistent state.

Recorded sequence of txs that triggered the error on Goerli
```
T,64677,1682707682626,0xf7445f4b8a07921bf882175470dc8f7221c53996,176,522,EIP1559,0x3638ea9a81f58e85f8b78119fbf3a571af06360703c9b28c5c4b7be368ccaed0,0xb8b402f8b10582020a833254608527fe069c99829cd99402a1427a63049ab9aead45e3348549cd192d4b3880b844a9059cbb0000000000000000000000007e42e11099b32207166c480ac9ceb544247f4f7200000000000000000000000000000000000000000000000002c7410578e52020c001a06f7811aa8031831c9334db4af5e6b5e8233d09a5d8b54cc903c4829cfcaf2db7a015fc65e59845cea4f51c390654f69f366b7797947c2465ac8871e09db326b8fc
T,64680,1682707682681,0xf7445f4b8a07921bf882175470dc8f7221c53996,521,523,EIP1559,0x5d2c344a7e60485f1ebc993fe5a008169cf62cf0a80d1e50d5dac26f2be8b6f9,0xb8b402f8b10582020b83325460852668231ade829ccd9402a1427a63049ab9aead45e3348549cd192d4b3880b844a9059cbb00000000000000000000000075d06e4e13a2686f6b6382f0469bb1a90207d5f9000000000000000000000000000000000000000000000000fcd41cf1f9726800c001a07a83a3f23c6a5711b12b094a9c1f5eb1566085af3cae7ce8ef7de2bf9b01f98ca020a579c6809e549fecd6cf7fa625c61d004a38e7c9dd0240e7b57eeddaa29920
T,64681,1682707682683,0xf7445f4b8a07921bf882175470dc8f7221c53996,521,524,EIP1559,0xec145da032e0cad4949354d04b4003b3f1d251d848961c9a8bb8006f773c88f2,0xb8b402f8b10582020c833254608527663f90b5829ccd9402a1427a63049ab9aead45e3348549cd192d4b3880b844a9059cbb000000000000000000000000996bad5b1910678cb5d0cf9a99e41bfe683cc5c90000000000000000000000000000000000000000000000000e16d0dff9357100c001a0755e97dc7f75de52421f9aad46920a4b731657e1a4b1814b23d73813b80e3554a01f1f18d8a0788e3d7e16b449ce40bed027ef89f02593279194d0608018aae121
T,64682,1682707682683,0xf7445f4b8a07921bf882175470dc8f7221c53996,521,525,EIP1559,0x6fb6172a35f4e768a46a41e9cd6eb2f604c00af7f3d95d8c68dfadb305235765,0xb8b402f8b10582020d83325460851f96ef4d16829ccd9402a1427a63049ab9aead45e3348549cd192d4b3880b844a9059cbb000000000000000000000000996bad5b1910678cb5d0cf9a99e41bfe683cc5c90000000000000000000000000000000000000000000000000e16d0dff9357100c001a0dddec6ba77da421491cc86f2817a427280c3570287b14660c8360db2010ea34ea00ff0588e8ffecfede061bc411132149875d8c54381d870a2735b25f10d9d9bb9
B,8907615,0xfab545f848990be13d1b2c283a579a36c95175a3615409d418980fc447042e8a,0x673e7c987d1255e979b169970d0c9ebf48ce83dc,3,0xb8ff877ed78ba520ece21b1de7843a8a57ca47cb,36768,0xdf816589e9098136c7a9377230fbd2702d0a4f42,49,0x3c8f564e42327b2da1dcddaabf14d361afc1c9f4,6,0xcf48eeab4a29afe1eff29b479723271673dfcd14,156396,0xd7fcefa6922622709d8a6b92ffd920a2ad814bad,672,0x412972bab5a49c3cfd5024fa63c88f02d031fa4b,1,0x7915ec065b644568155c4772a286addad3864c1b,634528,0xfd66f9b31d0242a6935f6b6abb680247fb1d40e7,1618,0xee1eebd9eaa6040a3274a0905c4995c67b29f07d,15,0xe80b6467863ebf8865092544f441da8fd3cf6074,362457,0xc62ead0235f2b98caecfc509fda0235c5c4e7b51,62,0xe319f378192409ee86def8f08a0870b78aa2dfc2,3952,0x168f6dec26cbbb3749654e0e3cc4fc29314fdf6c,144104,0x1234912ac7c626f737884720584e1e92c34778a2,540659,0x886c0bf953fbed7d3b60f96c677b88efb105904f,56,0xe93685f3bba03016f02bd1828badd6195988d950,580937,0x3812de8a5e6bfdc18e5da9c9044f1817491d9a26,16,0x1b7aa44088a0ea95bdc65fef6e5071e946bf7d8f,260297,0xe86c0fb64477b16a7c4e66352d8f2d1ac497b72b,11,0x981b87db14731a2dad571446e5d0956db8a38adf,10,0x7a21fe7e1815ad187af746acc2b2e7196a8aee40,426455,0xf5e8a439c599205c1ab06b535de46681aed1007a,520785,0xfbc826951894ffa276b405b7ab3f5fd48bca7393,10,0x3925a01896d3b1ccc1aef1b688afa592e90b933b,178958,0xd996b7770d6ac8191ba25e9432f43cc8e8eeccb7,1,0xf7445f4b8a07921bf882175470dc8f7221c53996,520,0xbe7707f5ce404db142e1379ea8ba646d150ebfd7,4081,0x5f28d7b183709d18b337795920f041ac4dea0e5c,6,R,,0xf9023ba006f162aa3ddb37814d753147b4c264487fb3cca95ab129769912d61ced7567eaa01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794455e5aa18469bc6ccef49594645666c587a3a71ba07d535451d5d90bb741f69766c832fe536052307d7ac060599e6747dfee3f1d2ea09d62c43d24e6b953c03ad7593c1622f295ffe913b8aa513ba9c43096037cf68ea051040a1d0c9dbc5b4bf6ada5e0ded00bc1c91257479fcdd2b317aad04c884b8db9010024e50a560020506e74d5047ec79f50f5300fd1423940487e31c78c12f811791f44eace401bbdb1641410006e970e90c4cef11132ba0037648124562813aea2229452e93c9c65782e5dae50cec06ad2a4664ff240cbd7ab408558d1ca80240029506da184d302a0c0244a10e6ec39cf0d100cdbc448a865dbe4a0401e0d8b3b441b2a20fe1a2eadaa2cc308248b320124444d427369179288300581ea14c2df4c164d8d5a7860265750b45206a41da60a3ec88603ac961b6c99b0a9aee1e2007b95b75267314488286803b2c10d27648ce4e89404a082c292708773b30886e9d71cf41571b1628255b13c432c62c53134844508900b5b265604c3e283bf906792808387eb5e8401c9c3808401c9b33d84644c14d499d883010b05846765746888676f312e32302e32856c696e7578a0269f1c8842dd2ce7802359f7d46215e4ee3dceb17367b2da08230582ee9b144f880000000000000000843006a467a01593d0a468f07e55ec32cfc478f2c42c2edb48d3a8f2cc6b403e769787cd20ea
```

Stack trace
```
{"@timestamp":"2023-04-28T18:48:02,751","level":"WARN","thread":"vert.x-worker-thread-0","class":"LayeredPendingTransactions","message":"Stack trace","throwable":" java.lang.IndexOutOfBoundsException: Index 275 out of bounds for length 100\n\tat java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)\n\tat java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)\n\tat java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)\n\tat java.base/java.util.Objects.checkIndex(Objects.java:359)\n\tat java.base/java.util.ArrayList.get(ArrayList.java:427)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.SparseTransactions.updateGap(SparseTransactions.java:335)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.SparseTransactions.internalRemove(SparseTransactions.java:231)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.AbstractTransactionsLayer.processRemove(AbstractTransactionsLayer.java:371)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.AbstractTransactionsLayer.confirmed(AbstractTransactionsLayer.java:435)\n\tat java.base/java.util.HashMap.forEach(HashMap.java:1421)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.AbstractTransactionsLayer.blockAdded(AbstractTransactionsLayer.java:402)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.AbstractTransactionsLayer.blockAdded(AbstractTransactionsLayer.java:401)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.AbstractTransactionsLayer.blockAdded(AbstractTransactionsLayer.java:401)\n\tat org.hyperledger.besu.ethereum.eth.transactions.layered.LayeredPendingTransactions.manageBlockAdded(LayeredPendingTransactions.java:379)\n\tat org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.onBlockAdded(TransactionPool.java:266)\n\tat org.hyperledger.besu.ethereum.chain.DefaultBlockchain.lambda$forwardToBlock$18(DefaultBlockchain.java:608)\n\tat org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:131)\n\tat java.base/java.lang.Iterable.forEach(Iterable.java:75)\n\tat org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:128)\n\tat org.hyperledger.besu.ethereum.chain.DefaultBlockchain.forwardToBlock(DefaultBlockchain.java:608)\n\tat org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.setNewHead(MergeCoordinator.java:618)\n\tat org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.updateForkChoice(MergeCoordinator.java:579)\n\tat org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.updateForkChoice(TransitionCoordinator.java:168)\n\tat org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.AbstractEngineForkchoiceUpdated.syncResponse(AbstractEngineForkchoiceUpdated.java:147)\n\tat org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:73)\n\tat io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)\n\tat io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)\n\tat io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n"}
```

### PR DESCRIPTION
**Pull request by fab-10**
## PR description

Added a general way to detect nonce discrepancies between world state and the txpool view for a sender, that could happen during the small amount of time during block import when the world state is update while the txpool still does not process the confirmed txs, or when there is a reorg and the sender nonce goes back, and if a nonce discrepancy is detected the txs for the sender are reconciled according with the world state nonce.

The new solution replace the solution that was in place to handle reorg, since it is general and covers all the cases of nonce discrepancies.

## Fixed Issue(s)

fixes #5447

### CODE REVIEW

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java [hunk 1]
```diff
@@ -95,66 +95,116 @@ public synchronized TransactionAddedResult addLocalTransaction(
...
+      final long stateSenderNonce,
+      final int nonceDistance,
+      final Throwable throwable) {
+    // in case something unexpected happened, log this sender txs and force a reorg of his txs
+    LOG.warn(
+        "Unexpected error {} when adding transaction {}, current sender status {}",
+        throwable,
+        pendingTransaction.toTraceLog(),
+        prioritizedTransactions.logSender(pendingTransaction.getSender()));
+    LOG.warn("Stack trace", throwable);
```
Comment (macfarla) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java:133]: warn seems high for a stack trace

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/ReplayTest.java [hunk 2]
```diff
@@ -67,7 +67,7 @@ public class ReplayTest {
   private final TransactionPoolMetrics txPoolMetrics = new TransactionPoolMetrics(metricsSystem);
 
   private final Address senderToLog =
-      Address.fromHexString("0x1a8ed0d3ad42c9019cc141aace7e5fb6e576b917");
+      Address.fromHexString("0xf7445f4b8a07921bf882175470dc8f7221c53996");
```
Comment (macfarla) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/ReplayTest.java:70]: was this changed for a reason?

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java [hunk 3]
```diff
@@ -95,66 +95,116 @@ public synchronized TransactionAddedResult addLocalTransaction(
...
+  private boolean nonceSkewDetected(
+      final PendingTransaction pendingTransaction, final long stateSenderNonce) {
+    final OptionalLong maybeTxPoolSenderNonce =
+        prioritizedTransactions.getCurrentNonceFor(pendingTransaction.getSender());
+    if (maybeTxPoolSenderNonce.isPresent()) {
+      final long txPoolSenderNonce = maybeTxPoolSenderNonce.getAsLong();
+      if (stateSenderNonce != txPoolSenderNonce) {
+        LOG.atDebug()
+            .setMessage(
+                "Nonce skew detected when adding pending transaction {}. Account nonce from world state is {} while current txpool nonce is {}")
```
Comment (macfarla) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java:157]: elsewhere are we calling this "nonce gap"?

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java (hunk 1 above)
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java:133]: this at `WARN` while the new txpool is in preview, since it helps me a lot to understand the source of any unexpected exception, will add a ToDo to demote it when the layered txpool will be enabled by default

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java (hunk 3 above)
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java:157]: this is a different scenario than "nonce gap", since "nonce gap" is the difference between the account nonce and the pending transaction, while "nonce skew" is the difference between the account nonce from the world state, and the account nonce as seen from the txpool point of view. Will add some doc to explain this better.

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/ReplayTest.java (hunk 2 above)
Comment (fab-10) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/layered/ReplayTest.java:70]: yes, since I was debugging a different account

**Review by garyschulte — APPROVED** [review]
LGTM, just a few nitpicks.  

Question: are we seeing a lot of concurrency issues with the layered transaction pool approach?  I am noticing none of the collections are the concurrent varieties, and given the nature of tx propagation and block import/production, it wouldn't surprise me to see frequent inconsistencies between the different collections tracking nonce, gap, and transactions.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/SparseTransactions.java [hunk 4]
```diff
@@ -273,6 +273,16 @@ public OptionalLong getNextNonceFor(final Address sender) {
     return OptionalLong.empty();
   }
 
+  @Override
+  public OptionalLong getCurrentNonceFor(final Address sender) {
+    final var senderTxs = txsBySender.get(sender);
+    if (senderTxs != null) {
+      final var gap = gapBySender.get(sender);
```
[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/SparseTransactions.java:280]: This is on purpose, since the data structures must be always aligned on consistent, `txsBySender` is the reference one, and if a tx is there, the it must be also in any other related data structure, and so any inconsistency should triggers an error, and fail fast, because it means there is a bug, and that helped to spot many edge cases during the development.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java [hunk 5]
```diff
@@ -95,66 +95,139 @@ public synchronized TransactionAddedResult addLocalTransaction(
...
+   * happen during the small amount of time during block import when the world state is updated
+   * while the txpool still does not process the confirmed txs, or when there is a reorg and the
+   * sender nonce goes back.
+   *
+   * @param pendingTransaction the incoming transaction to check
+   * @param stateSenderNonce account nonce from the world state
+   * @return false if the nonce for the sender has seen by the txpool matches the value of the
+   *     account nonce in the world state, true if they differ
+   */
+  private boolean accountNonceDisparityDetected(
```
[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java:160]: will rename

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java [hunk 6]
```diff
@@ -95,66 +95,139 @@ public synchronized TransactionAddedResult addLocalTransaction(
...
+      }
+    }
+    return false;
+  }
+
+  /**
+   * Rebuild the txpool for a sender according to the specified nonce. This is used in case the
+   * account nonce has seen by the txpool is not the correct one (see {@link
+   * LayeredPendingTransactions#accountNonceDisparityDetected(PendingTransaction, long)} for when
+   * this could happen). It works by removing all the txs for the sender and readding them using the
```
[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java:185]: thanks, I always appreciate suggestions like this from a mother tongue!

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java [hunk 7]
```diff
@@ -95,66 +95,139 @@ public synchronized TransactionAddedResult addLocalTransaction(
...
+          pendingTransaction, stateSenderNonce, (int) nonceDistance, throwable);
+    }
+  }
+
+  private TransactionAddedResult reconcileAndRetryAdd(
+      final PendingTransaction pendingTransaction,
+      final long stateSenderNonce,
+      final int nonceDistance,
+      final Throwable throwable) {
+    // in case something unexpected happened, log this sender txs and force a reorg of his txs
```
[the remark this answers is not in the document]
Comment (fab-10) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/layered/LayeredPendingTransactions.java:127]: we are forcing a reconcile, I have reworded and adjusted the comment

**Comment by fab-10** [comment]
> LGTM, just a few nitpicks.
> 
> Question: are we seeing a lot of concurrency issues with the layered transaction pool approach? I am noticing none of the collections are the concurrent varieties, and given the nature of tx propagation and block import/production, it wouldn't surprise me to see frequent inconsistencies between the different collections tracking nonce, gap, and transactions.

All the synchronization is done at the `LayeredPendingTransactions` point, which is the entry point for every operation and shield the layers from concurrency issues, so there is no need to make them thread safe, since they cannot be access directly.
