### PR TITLE
[1404] Fixed NPE when executing eth_estimateGas with privacy enabled.

### LINKED ISSUE #1404: NPE in privacy code
A user on rocketchat has observed the following NPE, starting in 1.5.4 - https://chat.hyperledger.org/channel/besu?msg=JLGTq9xLA5uExXpLe

```
java.lang.NullPointerException
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.privacy.PrivateStateRootResolver.resolveLastStateRoot(PrivateStateRootResolver.java:40)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.precompiles.privacy.PrivacyPrecompiledContract.compute(PrivacyPrecompiledContract.java:157)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.executePrecompile(MainnetMessageCallProcessor.java:133)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.start(MainnetMessageCallProcessor.java:61)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.process(AbstractMessageProcessor.java:163)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:426)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:339)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:49)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.TransactionProcessor.processTransaction(TransactionProcessor.java:253)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.mainnet.TransactionProcessor.processTransaction(TransactionProcessor.java:183)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.transaction.TransactionSimulator.process(TransactionSimulator.java:131)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.transaction.TransactionSimulator.process(TransactionSimulator.java:84)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthEstimateGas.response(EthEstimateGas.java:71)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:602)
validator1-bootnode_1  | 	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:473)
validator1-bootnode_1  | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
validator1-bootnode_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
validator1-bootnode_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
validator1-bootnode_1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
validator1-bootnode_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by mark-terry**
Signed-off-by: Mark Terry <mark.terry@consensys.net>

## PR description
Addresses a bug where an NPE could be encountered when `eth_estimateGas` is executed when privacy is enabled.

## Fixed Issue(s)

Fixes #1404 

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by macfarla — APPROVED** [review]
LGTM

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java [hunk 1]
```diff
@@ -242,6 +242,16 @@ ReceiveResponse getReceiveResponse(final String key) {
     return receiveResponse;
   }
 
+  boolean skipContractExecution(final MessageFrame messageFrame) {
+    return isReadOnly(messageFrame) || isMining(messageFrame);
+  }
+
+  boolean isReadOnly(final MessageFrame messageFrame) {
+    // If there's no PrivateMetadataUpdater, the precompile has likely been called as part of a
```
Comment (pinges) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java:250]: I don't like the "is likely" :-) We should know!

Is that correct? :  "If there's no PrivateMetadataUpdater, that means that the precompile has not been called through the PrivacyBlockProcessor. That means that the precompile has been called because a PMT is being simulated. The execution of the precompile has no influence on the outcome of that simulation."

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java [hunk 2]
```diff
@@ -242,6 +242,16 @@ ReceiveResponse getReceiveResponse(final String key) {
     return receiveResponse;
   }
 
+  boolean skipContractExecution(final MessageFrame messageFrame) {
+    return isReadOnly(messageFrame) || isMining(messageFrame);
+  }
+
+  boolean isReadOnly(final MessageFrame messageFrame) {
```
Comment (pinges) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContract.java:249]: maybe isSimulatingPMT() ?

**Review by pinges — COMMENTED** [review]
Please have a look at my comments.
