### PR TITLE
Investigate chain halts when syncing

### LINKED ISSUE #6884: Chain Download Halt
Seen on 24.3.0 and 24.4.0-RC2

On fresh SNAP/CHECKPOINT sync on a variety of networks, block import sometimes halts and requires a restart, despite having a full set of peers and world state downloading finishing.

Example:
```
{"@timestamp":"2024-04-04T05:48:35,877","level":"INFO","thread":"EthScheduler-Services-37 (importBlock)","class":"ImportBlocksStep","message":"Block import progress: 4030400 of 5625239 (71%)","throwable":""}
{"@timestamp":"2024-04-04T05:48:39,175","level":"INFO","thread":"EthScheduler-Services-26 (batchPersistTrieNodeData)","class":"SnapSyncMetricsManager","message":"Healed 221585 world state trie nodes, Peer count: 6","throwable":""}
{"@timestamp":"2024-04-04T05:49:42,821","level":"INFO","thread":"EthScheduler-Services-36 (requestCompleteTask)","class":"SnapWorldDownloadState","message":"Pausing world state download while waiting for sync to complete","throwable":""}

// and then nothing until restart
```

### LINKED ISSUE #7109: Could not confirm best peer had pivot block
latest besu from this commit https://github.com/hyperledger/besu/commit/27e5a649d74757330a6cd22094ae06d7251d0cc4
1 of 6 Azure nodes stuck with this recurring error

`{"@timestamp":"2024-05-16T03:45:24,313","level":"DEBUG","thread":"EthScheduler-Timer-0","class":"SyncTargetManager","message":"Could not confirm best peer had pivot block","throwable":" java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Timeout after 5000 MILLISECONDS\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)\n\tat java.base/java.util.concurrent.CompletableFuture$OrApply.tryFire(CompletableFuture.java:1576)\n\tat java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)\n\tat org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$failAfterTimeout$11(EthScheduler.java:301)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.util.concurrent.TimeoutException: Timeout after 5000 MILLISECONDS\n\tat org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$failAfterTimeout$11(EthScheduler.java:300)\n\t... 5 more\n"}`

looks like a chain halt - nothing in INFO logs for 3h after this:

`{"@timestamp":"2024-05-15T23:14:08,234","level":"INFO","thread":"EthScheduler-Services-36 (requestCompleteTask)","class":"SnapWorldDownloadState","message":"Pausing world state download while waiting for sync to complete","throwable":""}
{"@timestamp":"2024-05-15T23:14:45,654","level":"INFO","thread":"EthScheduler-Services-279 (importBlock)","class":"ImportBlocksStep","message":"Block import progress: 12582224 of 19878555 (63%), Peer count: 25","throwable":""}
{"@timestamp":"2024-05-15T23:22:41,709","level":"INFO","thread":"EthScheduler-Services-225 (importBlock)","class":"ImportBlocksStep","message":"Block import progress: 12606638 of 19878555 (63%), Peer count: 24","throwable":""}
{"@timestamp":"2024-05-15T23:24:47,420","level":"INFO","thread":"EthScheduler-Services-258 (importBlock)","class":"ImportBlocksStep","message":"Block import progress: 12614838 of 19878555 (63%), Peer count: 25","throwable":""}
{"@timestamp":"2024-05-15T23:32:05,457","level":"INFO","thread":"EthScheduler-Services-283","class":"SnapWorldDownloadState","message":"Running world state heal process from peers with pivot block 19878650","throwable":""}
{"@timestamp":"2024-05-15T23:34:06,377","level":"INFO","thread":"EthScheduler-Services-283 (importBlock)","class":"ImportBlocksStep","message":"Block import progress: 12639013 of 19878650 (63%), Peer count: 25","throwable":""}`

### PR DESCRIPTION
**Pull request by pinges**
## PR description
While investigating the chain download halts a few different causes for halts were identified and fixed.

The fix was tested with 19 nodes on mainnet:
ChainDownload

## Fixed Issue(s)
fixes #7109 
fixes #6884

### CODE REVIEW

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/RetryingGetAccountRangeFromPeerTask.java [hunk 1]
```diff
@@ -30,6 +30,7 @@
 public class RetryingGetAccountRangeFromPeerTask
     extends AbstractRetryingPeerTask<AccountRangeMessage.AccountRangeData> {
 
+  public static final int MAX_RETRIES = 5;
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/RetryingGetAccountRangeFromPeerTask.java:33]: Does it also make sense to increase the max retries to 5 for the other snap tasks? i.e. `RetryingGetBytecodeFromPeerTask`, `RetryingGetStorageRangeFromPeerTask` and `RetryingGetTrieNodeFromPeerTask`

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/SyncTargetManager.java [hunk 2]
```diff
@@ -121,7 +124,8 @@ private CompletableFuture<Optional<EthPeer>> confirmPivotBlockHeader(final EthPe
     task.assignPeer(bestPeer);
     return ethContext
         .getScheduler()
-        .timeout(task)
+        .timeout(task, Duration.ofSeconds(MAX_QUERY_RETRIES_PER_PEER * 5 + 1))
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/SyncTargetManager.java:127]: Is the 5 that is referred to here coming from the timeout in `AbstractRetryingPeerTask`? It would be nicer to create a constant there and use it here instead of having a magic value.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/range/SyncTargetRangeSource.java [hunk 3]
```diff
@@ -40,6 +40,7 @@
 public class SyncTargetRangeSource implements Iterator<SyncTargetRange> {
   private static final Logger LOG = LoggerFactory.getLogger(SyncTargetRangeSource.class);
   private static final Duration RETRY_DELAY_DURATION = Duration.ofSeconds(2);
+  public static final int DEFAULT_TIME_TO_WAIT_IN_SECONDS = 6;
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/range/SyncTargetRangeSource.java:43]: Why does increasing this to 6 seconds from 5 help? Looks like to only place where the timeout is increased

File: ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java [hunk 4]
```diff
@@ -185,15 +185,18 @@ public void terminateConnection(final DisconnectReason reason, final boolean pee
...
-      doSend(null, DisconnectMessage.create(reason));
-      LOG.atDebug()
-          .setMessage("Disconnecting connection {}, peer {} reason {}")
-          .addArgument(this.hashCode())
-          .addArgument(peer.getLoggableId())
-          .addArgument(reason)
-          .log();
-      closeConnection();
+      try {
+        doSend(null, DisconnectMessage.create(reason));
```
Comment (jframe) [inline ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java:189]: What's the significance of changing the order of the statements here?

Comment (jframe) [inline ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/AbstractPeerConnection.java:189]: It would be nice to add a comment saying that we need to do the doSend first because the dispatchDisconnect could fail with an exception

**Review by jframe — APPROVED** [review]
