### PR TITLE
fix TransactionLocation in DefaultBlockchain unsafeImportBlock() 

### LINKED ISSUE #7955: TransactionLocation uses transaction hash instead of block hash
In DefaultBlockBlockchain in the method unsafeImportBlock the TransactionLocation is supposed to use the block hash and not the transaction hash.

### PR DESCRIPTION
**Pull request by pinges**
## PR description
Fix the TransactionLocation in unsafeImportBlock()

fixes #7955

### CODE REVIEW

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java [hunk 1]
```diff
@@ -485,18 +485,18 @@ public synchronized void unsafeImportBlock(
...
-    updater.putBlockBody(hash, block.getBody());
+    final Hash blockHash = block.getHash();
+    updater.putBlockHeader(blockHash, block.getHeader());
+    updater.putBlockHash(block.getHeader().getNumber(), blockHash);
+    updater.putBlockBody(blockHash, block.getBody());
     final int nbTrx = block.getBody().getTransactions().size();
-    for (int i = 0; i < nbTrx; i++) {
-      final Hash transactionHash = block.getBody().getTransactions().get(i).getHash();
-      updater.putTransactionLocation(transactionHash, new TransactionLocation(transactionHash, i));
+    for (int index = 0; index < nbTrx; index++) {
```
Comment (jframe) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java:493]: The `indexTransactionForBlock` could be used here to remove some duplicated code

**Review by jframe — APPROVED** [review]
LGTM
