### PR TITLE
fix: eth_simulateV1 future blocks and validation error

### LINKED ISSUE #9829: Amsterdam: eth_simulateV1: fix revert err code
For bal-devnet-3 we need to update eth_simulateV1 to the latest spec: https://github.com/ethereum/execution-apis/pull/748

In general we need to investigate why the rpc-compat tests for it are not all passing: https://hive.ethpandaops.io/#/test/generic/1770961805-b00a60fa136bd8b91d91898c75260a8d?page=1&testnumber=138

### PR DESCRIPTION
**Pull request by macfarla**
## PR description
  - Return BLOCK_NOT_FOUND error instead of null success response when eth_simulateV1 is called with a future/unknown block number, per the execution-apis spec
  - Map UPFRONT_COST_EXCEEDS_BALANCE (-38014) error code to -32602 (invalid params) when validation is enabled, per the execution-apis spec. When validation is not enabled, the original -38014 code is preserved.

## Fixed Issue(s)
Ref #9636
fixes #9829

  Hive rpc-compat tests fixed (6)

  - eth_simulateV1/ethSimulate-empty-with-block-num-set-plus1
  - eth_simulateV1/ethSimulate-make-call-with-future-block
  - eth_simulateV1/ethSimulate-gas-fees-and-value-error-38014-with-validation
  - eth_simulateV1/ethSimulate-simple-no-funds-with-validation
  - eth_simulateV1/ethSimulate-simple-no-funds-with-validation-without-nonces
  - eth_simulateV1/ethSimulate-simple-send-from-contract-with-validation

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [x] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java [hunk 1]
```diff
@@ -110,10 +117,15 @@ protected Object resultByBlockHeader(
...
     } catch (final BlockStateCallException e) {
-      JsonRpcError error = new JsonRpcError(e.getError().getCode(), e.getMessage(), null);
+      int errorCode = e.getError().getCode();
+      // When validation is enabled, map simulation-specific error codes to -32602
+      // (invalid params) per the execution-apis spec.
+      if (simulateV1Parameter.isValidation()
+          && e.getError() == BlockStateCallError.UPFRONT_COST_EXCEEDS_BALANCE) {
+        errorCode = INVALID_PARAMS.getCode();
+      }
+      JsonRpcError error = new JsonRpcError(errorCode, e.getMessage(), null);
```
Comment (fab-10) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java:138]: it is worth to add tests for this new behavior

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java [hunk 2]
```diff
@@ -141,6 +153,25 @@ private SimulateV1Parameter getBlockStateCalls(final JsonRpcRequestContext reque
...
+      // Convert null success responses to BLOCK_NOT_FOUND errors for eth_simulateV1.
+      // The base class returns null for future/unknown blocks, but eth_simulateV1
+      // should return an error per the execution-apis spec.
+      if (response instanceof JsonRpcSuccessResponse successResponse
+          && successResponse.getResult() == null) {
+        return new JsonRpcErrorResponse(
+            requestContext.getRequest().getId(), new JsonRpcError(BLOCK_NOT_FOUND));
+      }
+      return (JsonRpcResponse) response;
+    }
```
Comment (fab-10) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java]: this works, but I would like if you consider an alternative implementation, that could more future proof?
Instead of overriding `response`, consider having new protected method `AbstractBlockParameterOrBlockHashMethod::blockNotFoundResponse` that by default returns success with null and it is overridden in this class to return the `BLOCK_NOT_FOUND` error.
As said this is a non blocking suggestion.

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java [hunk 3]
```diff
@@ -110,10 +117,15 @@ protected Object resultByBlockHeader(
...
       return process(header, simulateV1Parameter);
     } catch (final BlockStateCallException e) {
-      JsonRpcError error = new JsonRpcError(e.getError().getCode(), e.getMessage(), null);
+      int errorCode = e.getError().getCode();
+      // When validation is enabled, map simulation-specific error codes to -32602
+      // (invalid params) per the execution-apis spec.
+      if (simulateV1Parameter.isValidation()
+          && e.getError() == BlockStateCallError.UPFRONT_COST_EXCEEDS_BALANCE) {
+        errorCode = INVALID_PARAMS.getCode();
+      }
```
Comment (fab-10) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java:137]: this part does not seem covered by unit tests yet

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java [hunk 4]
```diff
@@ -96,8 +98,13 @@ protected Object resultByBlockHash(final JsonRpcRequestContext request, final Ha
   @Override
   protected Object resultByBlockHeader(
       final JsonRpcRequestContext request, final BlockHeader header) {
+    SimulateV1Parameter simulateV1Parameter;
+    try {
+      simulateV1Parameter = getBlockStateCalls(request);
+    } catch (final JsonRpcParameterException e) {
+      return errorResponse(request, INVALID_PARAMS);
+    }
```
Comment (fab-10) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java:117]: als this is not covered by unit tests

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java (hunk 2 above)
Comment (macfarla) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java]: good idea

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java (hunk 4 above)
Comment (macfarla) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java:117]: added test coverage

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java (hunk 1 above)
Comment (macfarla) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1.java:138]: added test coverage

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java [hunk 5]
```diff
@@ -110,7 +114,7 @@ protected Object handleParamTypes(final JsonRpcRequestContext requestContext) {
             requestContext.getRequest().getId(), RpcErrorType.INVALID_BLOCK_NUMBER_PARAMS);
       } else if (blockNumber.getAsLong() > getBlockchainQueries().headBlockNumber()) {
         // return null if a future block is requested
```
Comment (fab-10) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java]: nit: update comment

Comment (macfarla) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java]: fixed
