### PR TITLE
Fix for block import withdrawals

### LINKED ISSUE #5431: Investigate Besu Issue on Hive PR #764 - GraphQL Withdrawals
https://github.com/ethereum/hive/pull/764

https://discord.com/channels/905194001349627914/905205502940696607/1103324482610925598
> I'm writing a new Hive test and having difficulties with Besu... have a PoW chain and extended it with 1 Shanghai block. Besu errors on importing these blocks. I'm thinking it's a configuration error.

### PR DESCRIPTION
**Pull request by gfukushima**
## PR description
The initial intent of this PR was to fix the withdrawals field missing from the RawBlockIterator class used by the block import subcommand. Ended up introducing a refactor on some of the core methods of Block and BlockBody classes (readFrom and writeTo) aiming to remove duplicated code and reuse the existing logic defined in BlockBody.

## Fixed Issue(s)

Fixes #5431
It also fixes all the hive tests broken due to the impossibility of importing blocks (rpc-compat for example) that contained withdrawals via the `blocks import` subcommand.

### CODE REVIEW

**Review by jframe — APPROVED** [review]
LGTM

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java [hunk 1]
```diff
@@ -95,7 +95,7 @@ public Optional<BlockHeader> getBlockHeader(final Hash blockHash) {
   @Override
   public Optional<BlockBody> getBlockBody(final Hash blockHash) {
     return get(BLOCK_BODY_PREFIX, blockHash)
-        .map(bytes -> BlockBody.readFrom(RLP.input(bytes), blockHeaderFunctions));
+        .map(bytes -> BlockBody.readWrappedBodyFrom(RLP.input(bytes), blockHeaderFunctions));
```
Comment (siladu) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java:98]: I'm surprised we're using readWrapped here for an individual block - thought it was lists of blocks? Is it because that's how they are stored?

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/MessageWrapperTest.java [hunk 2]
```diff
@@ -231,6 +235,62 @@ public void PooledTransactions() throws IOException {
...
+            new BlockBody(
+                Collections.emptyList(),
+                Collections.emptyList(),
+                Optional.of(Collections.emptyList()),
+                Optional.empty()));
+  }
+
+  @Test
+  public void readBodyFieldsExpectsNoListWrappingBodyFields() {
+    // rlps of blocks contains block data in this format
```
Comment (siladu) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/MessageWrapperTest.java:259]: What does "rlps of blocks" mean? Isn't BodiesMessages rlps of blocks as well?

File: gradle/check-licenses.gradle [hunk 3]
```diff
@@ -151,6 +151,7 @@ downloadLicenses {
     // RocksDB is dual licensed under Apache v2.0 or GPL 2 licenses
     // Explicitly declare that we are using the Apache v2.0 license
     (group('org.rocksdb')) : apache,
+    (group('org.apache.tuweni')) : apache,
```
Comment (siladu) [inline gradle/check-licenses.gradle:154]: why did we need this?

**Review by siladu — COMMENTED** [review]
Good refactor, much clearer! Just some questions for clarification

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/MessageWrapperTest.java (hunk 2 above)
Comment (gfukushima) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/MessageWrapperTest.java:259]: think the input when using the block import feature is an rlp of blocks. BodiesMessages would be a rlp of Bodies only is my understand.

File: gradle/check-licenses.gradle (hunk 3 above)
Comment (gfukushima) [reply gradle/check-licenses.gradle:154]: Think I brought that from another branch I was testing. Have removed it.

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java (hunk 1 above)
Comment (gfukushima) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java:98]: Guess it all comes to how we initially write the bodies to the DB and we do it using the wrapper list.

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockBody.java [hunk 4]
```diff
@@ -125,21 +139,33 @@ public static BlockBody readFrom(
...
-                ? Optional.empty()
-                : Optional.of(input.readList(Deposit::readFrom)));
+    final BlockBody body = readFrom(input, blockHeaderFunctions);
     input.leaveList();
     return body;
   }
 
+  /**
+   * Read all fields from the block body expecting no list wrapping them. An example of a valid body
+   * would be: [txs],[ommers],[withdrawals] this method is called directly when importing a single
```
[the remark this answers is not in the document]
Comment (gfukushima) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockBody.java:149]: If I understood you question correctly, the answer is this method is used to READ a block body FROM a rlp.
The same applies to writeTo we write a body block to an rlp format.
Deposits included.

[the remark this answers is not in the document]
Comment (siladu) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockBody.java]: yep, understand it is used to read, just don't understand why we are reading in a block "import" context

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java (hunk 1 above)
Comment (siladu) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java:98]: OK, so this is internal to besu I guess. My mental model was wrapped === BlockBodiesMessage but I guess it's not that simple :)
