### PR TITLE
RPC - return null result if requested block not found

### LINKED ISSUE #9197: Inconsistent response of  JSON-RPC `eth_getBlockReceipts`
### Overview

Hello developers.

I'm running a separate Pectra PoS testnet chain for API testing. During testing, I observed discrepancies in the JSON-RPC responses from execution clients—geth, besu, nethermind, reth and erigon. Specifically, when calling `eth_getBlockReceipts` with invalid request, Besu returns an `Block not found` error with code `-32000`, while the other four clients respond with `null` as defined in the [exec-api spec](https://ethereum.github.io/execution-apis/api-documentation/).

```
# besu
{"error": {"code": -32000, "message": "Block not found"}, "id": 1, "jsonrpc": "2.0"}
# geth
{"id": 1, "jsonrpc": "2.0", "result": null}
# nethermind
{"id": 1, "jsonrpc": "2.0", "result": null}
# reth
{"id": 1, "jsonrpc": "2.0", "result": null}
# erigon
{"id": 1, "jsonrpc": "2.0", "result": null}
```

Spec definiton of the response:
```
"oneOf": [
	{
		"title": "Not Found (null)",
		"type": "null"
	},
	{
		"title": "Receipts information",
		"type": "array",
	...
```
Thanks for your attention!

### Steps to Reproduce

Call the `engine_newPayloadV4` with invalid block number:

```shell
curl POST http://127.0.0.1:10652 \
   -H "Content-Type: application/json" \
   -d '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getBlockReceipts",
  "params": [
    "0x1014083b159295235b6b84814f860e91d2a5105bf11c60f97ae8fb2b00cb7ff9"
  ]
}'
```

**Expected behavior:** Return `null` for not found.

**Actual behavior:** Return error.

**Frequency:** 100%

### Logs

```
# besu
{"error": {"code": -32000, "message": "Block not found"}, "id": 1, "jsonrpc": "2.0"}
# geth
{"id": 1, "jsonrpc": "2.0", "result": null}
# nethermind
{"id": 1, "jsonrpc": "2.0", "result": null}
# reth
{"id": 1, "jsonrpc": "2.0", "result": null}
# erigon
{"id": 1, "jsonrpc": "2.0", "result": null}
```

### Versions (Add all that apply)
* OS Name & Version: Ubuntu-20.04

Client versions

- besu/v25.8.0/linux-x86_64/openjdk-java-21
- Geth/v1.16.3-stable-d818a9af/linux-amd64/go1.24.6
- Nethermind/v1.33.1+cda59e5b/linux-x64/dotnet9.0.8
- reth/v1.7.0-9d56da5/x86_64-unknown-linux-gnu
- erigon/3.1.0/linux-amd64/go1.24.7

with 

- Prysm/v6.0.4 (linux amd64)

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
## PR description
If block not found, return a Success response with null result, NOT an Error response.

This affects all RPC methods that use `AbstractBlockParameterOrBlockHashMethod`
including
`debug_accountAt`, `debug_setHead`, `eth_call`, `eth_getBlockReceipts`, `eth_getProof`, `eth_simulateV1`, `eth_getBalance`, `eth_getCode`, `eth_getStorageAt`, `eth_getTransactionCount`

I've included this as a breaking change in the changelog since it is a change in behavior. However this is what the hive tests expect and it's moving towards being more consistent with other clients. 

## Fixed Issue(s)
Fixes #9197 

Fixes hive tests:
* eth_getBlockReceipts/get-block-receipts-empty
* eth_getBlockReceipts/get-block-receipts-future
* eth_getBlockReceipts/get-block-receipts-not-found

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

**Comment by macfarla** [comment]
draft bc this has unfortunately broken these hive tests:
eth_simulateV1/ethSimulate-empty-with-block-num-set-plus1 
eth_simulateV1/ethSimulate-make-call-with-future-block

**Comment by macfarla** [comment]
In Besu we have an abstract class AbstractBlockParameterOrBlockHashMethod that is used by several RPCs - so any RPC that gets a block by block number or hash will have the same error handling behavior. Including:
debug_accountAt, debug_setHead, eth_call, eth_getBlockReceipts, eth_getProof, eth_simulateV1, eth_getBalance, eth_getCode, eth_getStorageAt, eth_getTransactionCount

The spec, and the hive tests, are inconsistent with error handling expectations.

return null if block not found
so there’s hive tests for getBlockReceipts
but fixing those broke hive tests for eth_simulate that use a future block. Is it expected that we would want different behavior here or should eth_simulate also return null if the requested block is not found?
this PR fixes 3 hive tests and breaks 2

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java [hunk 1]
```diff
@@ -105,11 +105,12 @@ protected Object handleParamTypes(final JsonRpcRequestContext requestContext) {
     } else if (blockParameterOrBlockHash.isNumeric() || blockParameterOrBlockHash.isEarliest()) {
       final OptionalLong blockNumber = blockParameterOrBlockHash.getNumber();
       if (blockNumber.isEmpty() || blockNumber.getAsLong() < 0) {
+        // TODO should this be null result or invalid params?
```
Comment (jframe) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java:108]: I'm still not clear on this either even after going through https://github.com/hyperledger/besu/issues/9197. Looks like some clients return an error and some a null response. Think we should just leave this as is returning an error until we know otherwise.

**Review by jframe — APPROVED** [review]
