### PR TITLE
[Pruning Bugfix] Prevent race condition in key deletion.

### LINKED ISSUE #580: Error syncing with mainnet on Besu 1.3.7 node - MerkleTrieException
My node is raising a `MerkleTrieException` and is unable to sync to mainnet with pruning enabled.

 

Hardware specs: `Thinkpad T430 laptop, 8GB RAM 1TB SSD 4 cores i53320M 2.6GHz`

CLI arguments: `$ besu --data-path=/home/node/node --rpc-http-enabled --pruning-enabled`

 

Error log:

```
2019-12-16 19:21:02.825+01:00 | nioEventLoopGroup-3-1 | INFO  | SyncTargetManager | Found common ancestor with peer 0x9208aa710c44ca7220... at block 9696372019-12-16 19:21:02.825+01:00 | nioEventLoopGroup-3-1 | INFO  | SyncTargetManager | Found common ancestor with peer 0x9208aa710c44ca7220... at block 9696372019-12-16 19:21:04.032+01:00 | EthScheduler-Services-0 (importBlock) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0xdab2b5f035e693b4597a6c7d24abb3c0b675022a45a2262000fd29233016a0a4 at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?] at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?] at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019) ~[?:?] at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?] at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:152) ~[besu-pipeline-1.3.7.jar:1.3.7] at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:134) ~[besu-pipeline-1.3.7.jar:1.3.7] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?] at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] at java.lang.Thread.run(Thread.java:834) [?:?]Caused by: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0xdab2b5f035e693b4597a6c7d24abb3c0b675022a45a2262000fd29233016a0a4
```

Probability: Probable

Severity: Critical

--- 

Additional comments from the [original Jira issue:](https://jira.hyperledger.org/browse/BESU-160) 

>After deleting chain data and resyncing with pruning, I get the same error at another block. The following is an extract of the error:

```

2020-01-08 12:31:09.618+01:00 | nioEventLoopGroup-3-1 | INFO | SyncTargetManager | Found common ancestor with peer 0x58cf42ac9b3134a2ef... at block 2428314 2020-01-08 12:31:12.984+01:00 | EthScheduler-Services-48 (importBlock) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay. java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x498331f10b7c83bb32ef331f72296c4fed6d40cbcd1fba0ced59501a19b1bbfc at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?] at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?] at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019) ~[?:?] at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?] at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:152) ~[besu-pipeline-1.3.8.jar:1.3.8] at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:134) ~[besu-pipeline-1.3.8.jar:1.3.8] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?] at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] at java.lang.Thread.run(Thread.java:834) [?:?] Caused by: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x498331f10b7c83bb32ef331f72296c4fed6d40cbcd1fba0ced59501a19b1bbfc at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:107) ~[besu-trie-1.3.8.jar:1.3.8] at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?] at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:106) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:49) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:62) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:50) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:62) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:50) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:62) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:50) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:62) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:62) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:62) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:80) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:35) ~[besu-trie-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.worldstate.DefaultMutableWorldState.get(DefaultMutableWorldState.java:111) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.core.AbstractWorldUpdater.get(AbstractWorldUpdater.java:80) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.core.AbstractWorldUpdater.get(AbstractWorldUpdater.java:80) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.core.AbstractWorldUpdater.get(AbstractWorldUpdater.java:80) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.core.AbstractWorldUpdater.get(AbstractWorldUpdater.java:80) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.vm.operations.SelfDestructOperation.cost(SelfDestructOperation.java:42) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.vm.ehalt.InsufficientGasExceptionalHaltPredicate.exceptionalHaltCondition(InsufficientGasExceptionalHaltPredicate.java:35) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.vm.ehalt.ExceptionalHaltManager.evaluateAll(ExceptionalHaltManager.java:38) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.vm.EVM.evaluateExceptionalHaltReasons(EVM.java:89) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.vm.EVM.executeNextOperation(EVM.java:73) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.vm.EVM.runToHalt(EVM.java:51) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:156) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.process(AbstractMessageProcessor.java:170) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:345) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:291) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:42) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.TransactionProcessor.processTransaction(TransactionProcessor.java:133) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:132) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:36) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:59) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:88) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:46) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44) ~[besu-core-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:45) ~[besu-eth-1.3.8.jar:1.3.8] at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:29) ~[besu-eth-1.3.8.jar:1.3.8] at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37) ~[besu-pipeline-1.3.8.jar:1.3.8] at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.3.8.jar:1.3.8] ... 5 more 2020-01-08 12:31:15.083+01:00 | nioEventLoopGroup-3-1 | INFO | SyncTargetManager | Found common ancestor with peer 0x58cf42ac9b3134a2ef... at block 2428314 

```

> Possible cause of error might be found here: 

```
java.lang.Thread.run(Thread.java:834) [?:?] Caused by: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x498331f10b7c83bb32ef331f72296c4fed6d40cbcd1fba0ced59501a19b1bbfc at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:107) ~[besu-trie-1.3.8.jar:1.3.8] at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?] at
```

### PR DESCRIPTION
**Pull request by RatanRSur**
### The Bug
Account `A` has storage nodes become inaccessible from any of the recent state tries that we intend to keep.
Account `B`'s storage is currently being populated by the block importer and happens to have the some of the same contents of `A`'s storage.

Nodes in `A`'s storage are being swept while the nodes resulting from the processing of the block with `B` is about to be persisted to the `WorldStateKeyValueStorage`, which will trigger the marking listener.

If the thread running the method `removeAllKeysUnless` is taken off the cpu before it calls `delete`, there is an opportunity for a (higher priority) block-import thread to commit the same node that is about to be deleted. This commit will trigger the `markNodes` listener but at that point it's already too late. We already did the "in use check" when we looked at the node in `markStorage` and have committed to deleting the key.

### Burn-in testing
All (including full syncs with pruning - good for checking correctness)
https://grafana-metrics-ohio.ops.pegasys.tech/d/5S-6O8VZk/besu-overview?orgId=1&from=1588263154000&to=now&var-system=dev-besu-release-mainnet-nopruning-nofix&var-system=dev-besu-release-mainnet-nopruning-nofix-fast&var-system=dev-besu-release-mainnet-pruning-bugfix&var-system=dev-besu-release-mainnet-pruning-bugfix-fast&var-system=dev-besu-release-mainnet-pruning-nofix-fast&refresh=10s

Only fast syncs (for real use-case performance)
https://grafana-metrics-ohio.ops.pegasys.tech/d/5S-6O8VZk/besu-overview?orgId=1&from=1588262400000&to=now&var-system=dev-besu-release-mainnet-nopruning-nofix-fast&var-system=dev-besu-release-mainnet-pruning-bugfix-fast&var-system=dev-besu-release-mainnet-pruning-nofix-fast&refresh=10s

## Fixed Issue(s)
fixes #580

### CODE REVIEW

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/WorldStateKeyValueStorage.java [hunk 1]
```diff
@@ -86,9 +89,32 @@ public Updater updater() {
...
+              // thread interleaving from causing an erroneous deletion
+              doomedKeyRef
+                  .get()
+                  .ifPresent(
+                      doomedKey -> {
+                        keyValueStorage.delete(doomedKey);
+                        prunedKeys.incrementAndGet();
+                      });
+            }
+            doomedKeyRef.set(Optional.empty());
```
Comment (ajsutton) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/WorldStateKeyValueStorage.java:113]: I can't work out how this helps with the threading issue.  The bug would be a lot less likely to occur because there's now a second check done but I don't see what's guaranteeing the threading order to guarantee that a transaction isn't adding the key between when we do `doomedKeyReft.get().ifPresent` and the actual deletion of the key.

Is there some detail of RocksDB threading and locking I'm missing?

Comment (RatanRSur) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/WorldStateKeyValueStorage.java:113]: Nope, you're right. I just brain farted.

File: plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java [hunk 2]
```diff
@@ -112,39 +117,29 @@ public boolean containsKey(final byte[] key) throws StorageException {
...
-          removedNodeCounter++;
-          db.delete(key);
-        }
-      }
-    } catch (final RocksDBException e) {
-      throw new StorageException(e);
-    }
-    return removedNodeCounter;
+  public Set<byte[]> getAllKeysThat(final Predicate<byte[]> returnCondition) {
+    return streamKeys().filter(returnCondition).collect(toUnmodifiableSet());
```
Comment (mbaxter) [inline plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java:126]: We were previously using `Sets.newIdentityHashSet()` to create this set, which it looks like we were doing in order to make the equality checks more efficient.  We should probably keep that.

File: services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/LimitedInMemoryKeyValueStorage.java [hunk 3]
```diff
@@ -59,7 +62,13 @@ public void clear() {
 
   @Override
   public boolean containsKey(final byte[] key) throws StorageException {
-    return get(key).isPresent();
+    final Lock lock = rwLock.readLock();
+    lock.lock();
+    try {
+      return get(key).isPresent();
```
Comment (mbaxter) [inline services/kvstore/src/main/java/org/hyperledger/besu/services/kvstore/LimitedInMemoryKeyValueStorage.java:68]: `get()` already does the locking internally - I don't think you need this extra locking

File: plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java [hunk 4]
```diff
@@ -58,7 +60,7 @@
 import org.rocksdb.WriteOptions;
 
 public class RocksDBColumnarKeyValueStorage
-    implements SegmentedKeyValueStorage<ColumnFamilyHandle>, Closeable {
```
[the remark this answers is not in the document]
Comment (RatanRSur) [reply plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java:61]: It was redundant, the interface already extends it.

File: plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java (hunk 2 above)
Comment (RatanRSur) [reply plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java:126]: I thought that was already the case for `byte[]`.
```
 ~/wrk/besu pruning-bugfix-doomed-key ⁘ jshell
|  Welcome to JShell -- Version 11.0.6
|  For an introduction type: /help intro

jshell> new HashSet<byte[]>()
$1 ==> []

jshell> $1.add(new byte[] {1})
$2 ==> true

jshell> $1
$1 ==> [[B@5034c75a]

jshell> $1.contains(new byte[] {1})
$4 ==> false

jshell>
```

Comment (mbaxter) [reply plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/unsegmented/RocksDBKeyValueStorage.java:126]: Yeah - I think you're right.  Did some quick googling trying to figure out why we were using `newIdentityHashSet` and I misread an answer that referenced: https://docs.oracle.com/javase/6/docs/api/java/util/Arrays.html#equals%28byte%5B%5D,%20byte%5B%5D%29

File: plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java [hunk 5]
```diff
@@ -165,36 +167,25 @@ public ColumnFamilyHandle getSegmentIdentifierByName(final SegmentIdentifier seg
...
+    rocksIterator.seekToFirst();
+    return RocksDbKeyIterator.create(rocksIterator).toStream();
+  }
+
+  @Override
+  public void tryDelete(final ColumnFamilyHandle segmentHandle, final byte[] key) {
+    try {
+      db.delete(segmentHandle, tryDeleteOptions, key);
+    } catch (RocksDBException e) {
+      throw RocksDBExceptionAdapter.createStorageException(e);
```
[the remark this answers is not in the document]
Comment (RatanRSur) [reply plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/segmented/RocksDBColumnarKeyValueStorage.java:181]: You're right, that would be a lot cleaner.

File: plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java [hunk 6]
```diff
@@ -61,15 +63,23 @@
...
-   * @throws StorageException problem encountered when removing data.
+   * @return A stream of all keys in storage.
+   * @throws StorageException problem encountered during the retrieval attempt.
+   */
+  Stream<byte[]> streamKeys() throws StorageException;
+
+  /**
+   * Attempt to delete the value corresponding to the given key. For some storage mediums we want to
+   * be able to abandon the delete under certain circumstances. For example, to abandon the attempt
+   * if we can't acquire a lock on the underlying storage.
```
Comment (ajsutton) [inline plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java:76]: We probably need to make the requirements for this method clearer - is it allowed to wait for the lock to be available or must it always immediately fail if the lock is unavailable?  Otherwise we risk pruning not working or getting deadlocks with some storage plugins because they don't exhibit the behaviour we need here.

File: plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java [hunk 7]
```diff
@@ -61,15 +63,23 @@
...
+   *
+   * @param key The key to delete.
+   * @throws IncompleteOperationException the operation was incomplete and the key was not deleted
+   * @throws StorageException any other problem encountered during the deletion attempt.
    */
-  long removeAllKeysUnless(Predicate<byte[]> retainCondition) throws StorageException;
+  void tryDelete(byte[] key) throws IncompleteOperationException, StorageException;
```
Comment (ajsutton) [inline plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java:82]: We should make this return `boolean` rather than throwing an exception since not completing the operation is a "normal" outcome, we shouldn't model it as an exception.

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/WorldStateKeyValueStorage.java [hunk 8]
```diff
@@ -156,12 +184,18 @@ public Updater putAccountStorageTrieNode(final Bytes32 nodeHash, final Bytes nod
...
     public void commit() {
-      nodeAddedListeners.forEach(listener -> listener.onNodesAdded(addedNodes));
-      transaction.commit();
+      lock.lock();
+      try {
+        nodeAddedListeners.forEach(listener -> listener.onNodesAdded(addedNodes));
+        transaction.commit();
+      } finally {
+        lock.unlock();
+      }
```
[the remark this answers is not in the document]
Comment (RatanRSur) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/WorldStateKeyValueStorage.java:188]: Not so fast :) I'm going to start some fast syncs to see what it does with the full state because a longer sweeping phase means a larger storage spike caused by the snapshot of the column while we're iterating.

On the other hand, keeping up with head means rare commits to the world state database so a lot less contention there.

[the remark this answers is not in the document]
Comment (ajsutton) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/WorldStateKeyValueStorage.java:188]: Fortunately it's the mark phase that takes the vast majority of the time - the sweep phase IIRC was quite fast (it may not be so now).  Might still be an issue but it's still a much lower impact than I was first expecting when we started talking about needing a lock.

File: plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDbKeyIterator.java [hunk 9]
```diff
@@ -0,0 +1,93 @@
...
+                | Spliterator.DISTINCT
+                | Spliterator.NONNULL
+                | Spliterator.ORDERED
+                | Spliterator.SORTED);
+
+    return StreamSupport.stream(spliterator, false).onClose(this::close);
+  }
+
+  private void assertOpen() {
+    checkState(!closed.get(), "Attempt to update a closed transaction");
```
Comment (mbaxter) [inline plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDbKeyIterator.java:84]: Whoops - looks like copy/pasta
```suggestion
    checkState(!closed.get(), "Attempt to read from a closed " + getClass().getSimpleName());
```

File: plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java [hunk 10]
```diff
@@ -61,15 +62,23 @@
...
+  /**
+   * Delete the value corresponding to the given key if a write lock can be instantly acquired on
+   * the underlying storage. Do nothing otherwise.
+   *
+   * @param key The key to delete.
+   * @throws StorageException any problem encountered during the deletion attempt.
+   * @return false if the lock on the underlying storage could not be instantly acquired, true
+   *     otherwise
    */
-  long removeAllKeysUnless(Predicate<byte[]> retainCondition) throws StorageException;
```
Comment (mbaxter) [inline plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java:72]: Sanity check - I assume we've thought through the implications of removing this public API?

File: plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDbKeyIterator.java [hunk 11]
```diff
@@ -0,0 +1,93 @@
...
+    return rocksIterator.isValid();
+  }
+
+  @Override
+  public byte[] next() {
+    assertOpen();
+    try {
+      rocksIterator.status();
+    } catch (final RocksDBException e) {
+      LOG.error("RocksDbEntryIterator encountered a problem while iterating.", e);
```
Comment (mbaxter) [inline plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDbKeyIterator.java:59]:
```suggestion
      LOG.error(getClass().getSimpleName() + " encountered a problem while iterating.", e);
```

File: plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java (hunk 10 above)
Comment (RatanRSur) [reply plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java:72]: We added it just for pruning and I think the only dependency for the storage plugin api is PegaSys plus. I'll ask them if they still want it around.

**Comment by RatanRSur** [comment]
@MadelineMurray how does this look to you?
https://github.com/hyperledger/besu/pull/760/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by MadelineMurray** [comment]
@RatanRSur - LGTM

File: plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java (hunk 10 above)
Comment (mbaxter) [reply plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/KeyValueStorage.java:72]: Since this could be a breaking change if anyone depends on this API, might be worth moving this API clean-up into a separate PR, so we can be more careful about when / how exactly we release this.
