### PR TITLE
Fix eth_simulateV1 to accept both input and data fields with differen…

### LINKED ISSUE #9960: `eth_simulateV1` discrepancy
### Description
Hello developers, 

I am currently running differential testing (Geth, Besu, Nethermind, Reth, Erigon) using a separate testnet chain. During my testing of the `eth_simulateV1` method, I observed a discrepancy in how Besu handles the input/data compared to other EL clients.

Specifically, when the input and data are provided in the same time but different values are provided, besu return 
error while other EL clients could execute the request. BTW, I also test cases where input and data are provided with same values or only one of the them in the tests, these scenarios are good.

### Steps to Reproduce
Test case:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_simulateV1",
  "params": [
    {
      "blockStateCalls": [
        {
          "calls": [
            {
              "from": "0xc000000000000000000000000000000000000000",
              "to": "0xd000000000000000000000000000000000000000",
              "input": "0xDEADBEEF",
              "data": "0xCAFEBABE"
            }
          ]
        }
      ],
      "validation": false
    },
    "latest"
  ]
}
```

**Expected behavior:** Using input value.

**Actual behavior:** Return error.

**Frequency:** 100%
### Logs
```
# geth
{"id": 1, "jsonrpc": "2.0", "result": [{"baseFeePerGas": "0x0", "blobGasUsed": "0x0", "calls": [{"gasUsed": "0x52a8", "logs": [], "returnData": "0x", "status": "0x1"}], "difficulty": "0x0", "excessBlobGas": "0x0", "extraData": "0x", "gasLimit": "0x392a13c", "gasUsed": "0x52a8", "hash": "0xd7542931a40cf042965f59458114ccb4ff350d5d52010bb91016adef5080ab4e", "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner": "0x8943545177806ed17b9f23f0a21ee5948ecaa776", "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce": "0x0000000000000000", "number": "0x295", "parentBeaconBlockRoot": "0x0000000000000000000000000000000000000000000000000000000000000000", "parentHash": "0x846d666feb22d163597d8d132ca1df39ecc8a5ea2abb985fb9dbfc7b713c3e7c", "receiptsRoot": "0xb77f680a9de2f33cc2c460cc18ca6e5b282cfa603b6155c65db4b0019b005b94", "requestsHash": "0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size": "0x296", "stateRoot": "0xefaddfd587534c0b13b6c5a3db5c939166053c0d893395288af34dc17e674ee5", "timestamp": "0x69a80240", "transactions": ["0xb7ead76612289fb7002977ef4ca37790524af6d51f46027c522ee2fae2f590fa"], "transactionsRoot": "0xe6b8a1dcb3fde4fbb8ef04ea469a2ea3414bc5b5292b548f46aa5653911606d2", "uncles": [], "withdrawals": [], "withdrawalsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"}], "server": "http://127.0.0.1:45466"}
# besu
{"error": {"code": -32602, "message": "Invalid params"}, "id": 1, "jsonrpc": "2.0", "server": "http://127.0.0.1:44946"}
# neth
{"id": 1, "jsonrpc": "2.0", "result": [{"baseFeePerGas": "0x0", "blobGasUsed": "0x0", "calls": [{"gasUsed": "0x52a8", "logs": [], "returnData": "0x", "status": "0x1"}], "difficulty": "0x0", "excessBlobGas": "0x0", "extraData": "0x", "gasLimit": "0x392a13c", "gasUsed": "0x52a8", "hash": "0xdf44a812a34691a01f6acb9a410bf17e8b1a2038708f2c5a9fdbd71c9a9191d3", "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner": "0x8943545177806ed17b9f23f0a21ee5948ecaa776", "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce": "0x0000000000000000", "number": "0x295", "parentBeaconBlockRoot": "0x0000000000000000000000000000000000000000000000000000000000000000", "parentHash": "0x846d666feb22d163597d8d132ca1df39ecc8a5ea2abb985fb9dbfc7b713c3e7c", "receiptsRoot": "0xb77f680a9de2f33cc2c460cc18ca6e5b282cfa603b6155c65db4b0019b005b94", "requestsHash": "0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size": "0x296", "stateRoot": "0xefaddfd587534c0b13b6c5a3db5c939166053c0d893395288af34dc17e674ee5", "timestamp": "0x69a80240", "transactions": ["0xb2a78c65a368253f1ce5996bca673ad978d5cf4c57cf3e39e7713ebac2a7fe21"], "transactionsRoot": "0x2c2b19d4f8b36a05a0974dd0b0997925c91a742717ff411b3cbb11245f53c850", "uncles": [], "withdrawals": [], "withdrawalsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"}], "server": "http://127.0.0.1:46474"}
# reth
{"id": 1, "jsonrpc": "2.0", "result": [{"baseFeePerGas": "0x0", "blobGasUsed": "0x0", "calls": [{"gasUsed": "0x52a8", "logs": [], "returnData": "0x", "status": "0x1"}], "difficulty": "0x0", "excessBlobGas": "0x0", "extraData": "0x626573752032362e312e30", "gasLimit": "0x392a13c", "gasUsed": "0x52a8", "hash": "0xb525149b289f0a64e661284f097518043b499c5f2be8479aeef4117db9f64afa", "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner": "0x8943545177806ed17b9f23f0a21ee5948ecaa776", "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce": "0x0000000000000000", "number": "0x295", "parentBeaconBlockRoot": "0x4bd61a39baf5de5c7a1d917cbbe89ad567634790aeb47095a58e19284a0c80f9", "parentHash": "0x846d666feb22d163597d8d132ca1df39ecc8a5ea2abb985fb9dbfc7b713c3e7c", "receiptsRoot": "0xb77f680a9de2f33cc2c460cc18ca6e5b282cfa603b6155c65db4b0019b005b94", "requestsHash": "0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size": "0x2a1", "stateRoot": "0x0000000000000000000000000000000000000000000000000000000000000000", "timestamp": "0x69a80240", "transactions": ["0xb7ead76612289fb7002977ef4ca37790524af6d51f46027c522ee2fae2f590fa"], "transactionsRoot": "0xe6b8a1dcb3fde4fbb8ef04ea469a2ea3414bc5b5292b548f46aa5653911606d2", "uncles": [], "withdrawals": [], "withdrawalsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"}], "server": "http://127.0.0.1:45636"}
# erigon
{"id": 1, "jsonrpc": "2.0", "result": [{"baseFeePerGas": "0x0", "blobGasUsed": "0x0", "calls": [{"gasUsed": "0x52a8", "logs": [], "returnData": "0x", "status": "0x1"}], "difficulty": "0x0", "excessBlobGas": "0x0", "extraData": "0x", "gasLimit": "0x392a13c", "gasUsed": "0x52a8", "hash": "0xd7542931a40cf042965f59458114ccb4ff350d5d52010bb91016adef5080ab4e", "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "miner": "0x8943545177806ed17b9f23f0a21ee5948ecaa776", "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "nonce": "0x0000000000000000", "number": "0x295", "parentBeaconBlockRoot": "0x0000000000000000000000000000000000000000000000000000000000000000", "parentHash": "0x846d666feb22d163597d8d132ca1df39ecc8a5ea2abb985fb9dbfc7b713c3e7c", "receiptsRoot": "0xb77f680a9de2f33cc2c460cc18ca6e5b282cfa603b6155c65db4b0019b005b94", "requestsHash": "0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347", "size": "0x296", "stateRoot": "0xefaddfd587534c0b13b6c5a3db5c939166053c0d893395288af34dc17e674ee5", "timestamp": "0x69a80240", "transactions": ["0xb7ead76612289fb7002977ef4ca37790524af6d51f46027c522ee2fae2f590fa"], "transactionsRoot": "0xe6b8a1dcb3fde4fbb8ef04ea469a2ea3414bc5b5292b548f46aa5653911606d2", "uncles": [], "withdrawals": [], "withdrawalsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"}], "server": "http://127.0.0.1:45998"}
```

### Versions (Add all that apply)
* Software version: besu/v26.1.0
* Docker Version: 24.0.2
* Consensus Client & Version if using Proof of Stake: Lighthouse

### PR DESCRIPTION
**Pull request by kkaur01**
…t values

## PR description
`eth_simulateV1` was returning `-32602 Invalid params` when both `input`                                                                                                                      
  and `data` fields were provided with different values, while all other EL                                                                                                                     
  clients (Geth, Nethermind, Reth, Erigon) silently accept this and use                                                                                                                         
  `input`.

  This is fixed with a targeted deserializer (`SimulateCallParameterDeserializer`)
  applied only to calls within `eth_simulateV1`. When both fields are present
  with different values, `input` takes precedence and `data` is dropped before
  deserialization, matching the execution-apis spec where only `input` is
  defined in `GenericTransaction`.

  `eth_call`, `eth_estimateGas`, and other methods are unaffected — they
  retain the existing strict validation that errors when `input` and `data`
  conflict, matching Geth's behaviour for those methods.

## Fixed Issue(s)
fixes #9960

## Changelog
  - Bug fix: `eth_simulateV1` now accepts calls where both `input` and `data`
    are provided with different values, using `input` as per the execution-apis
    spec.

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1Test.java [hunk 1]
```diff
@@ -135,6 +136,33 @@ public void shouldReturnOriginalErrorCodeWhenUpfrontCostExceedsBalanceWithoutVal
...
+    final Map<String, Object> simulateParam =
+        Map.of("blockStateCalls", List.of(Map.of("calls", List.of(callObj))), "validation", false);
+
+    final JsonRpcRequestContext request =
+        new JsonRpcRequestContext(
+            new JsonRpcRequest("2.0", "eth_simulateV1", new Object[] {simulateParam, "latest"}));
+
+    final JsonRpcResponse response = method.response(request);
+
+    assertThat(response).isNotInstanceOf(JsonRpcErrorResponse.class);
```
Comment (macfarla) [inline ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSimulateV1Test.java:165]: assertThat(response).isNotInstanceOf(JsonRpcErrorResponse.class);
  This only proves it didn't error — it doesn't verify that 0xDEADBEEF (input) was actually passed to the simulator rather than 0xCAFEBABE (data). You could capture the List<BlockStateCall> argument to blockSimulator.process() and assert on the
  payload of the first call.

**Review by macfarla — COMMENTED** [review]
The scope is now correct. 

Can you update the PR description and add a changelog entry

**Comment by macfarla** [comment]
just needs a changelog entry
