### PR TITLE
jwt auth on websockets

### LINKED ISSUE #3990: JWT Authenticated RPC not working via Websockets
### Description
I've tried to use engine and `eth` api space on authenticated RPC via Websockets and Besu responds with following errors on any requests: `{"jsonrpc":"2.0","id":127,"error":{"code":-40100,"message":"Unauthorized"}}`. If I change it to `http://` on the same port, it works like a charm.

### Steps to Reproduce (Bug)
I use following settings to enable RPC API in test:
```
      configMap.put("rpc-ws-enabled", true);
      configMap.put("rpc-ws-api", {"ETH,NET,WEB3,ENGINE"});
      configMap.put("engine-jwt-enabled", Boolean.TRUE);
      configMap.put("engine-jwt-secret", JWT_SECRET_FILE_PATH);

      configMap.put("host-allowlist", new String[] {"*"});
      configMap.put("engine-rpc-port", "8550");
      configMap.put("engine-host-allowlist", new String[] {"*"});
```

**Expected behavior:** [What you expect to happen]
I could use Besu's `engine` and `eth` RPCs authenticated with JWT over Websockets

**Actual behavior:** [What actually happens]
I'm getting `Unauthorized`

**Frequency:** [What percentage of the time does it occur?]
Always

### Versions (Add all that apply)
Besu 22.4.3

### Additional Information (Add any of the following or anything else that may be relevant)
My JWT key is `0xdcc12520e177f253b3ddc02d00cce05096441eef2c0d0b769d317511c29d894f`
Related part of log. Notice that authorization is successful but all subsequent requests - not:

```
2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzOTQ4MjB9.77Gv3rMinFh4IFhGd-ryd6ox3wU0wU4LneX7s42aHUM

2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | Connection: Upgrade

2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | Host: besunode1:8550

2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | Sec-WebSocket-Key: JxpqT6RicaAuHeciUPOpTQ==

2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | Sec-WebSocket-Version: 13

2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | Upgrade: websocket

2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 

2022-06-16 19:53:40.293+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 

2022-06-16 19:53:40.296+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:53:40.296+00:00 | vert.x-eventloop-thread-1 | DEBUG | JsonRpcService | Opened connection from 192.168.0.3:35402. Total of active connections: 1/80

2022-06-16 19:53:40.328+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:53:40.327+00:00 | vert.x-eventloop-thread-1 | TRACE | JsonRpcService | Websocket authentication token eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzOTQ4MjB9.77Gv3rMinFh4IFhGd-ryd6ox3wU0wU4LneX7s42aHUM

2022-06-16 19:53:40.344+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:53:40.343+00:00 | vert.x-eventloop-thread-1 | DEBUG | JsonRpcService | Websocket Connected (host=192.168.0.3, port=35402)

2022-06-16 19:53:40.356+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:53:40.356+00:00 | vert.x-eventloop-thread-1 | DEBUG | WebSocketServerHandshaker | [id: 0xd6e65926, L:/192.168.0.2:8550 - R:/192.168.0.3:35402] WebSocket version V13 server handshake

2022-06-16 19:53:40.359+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:53:40.359+00:00 | vert.x-eventloop-thread-1 | DEBUG | WebSocketServerHandshaker | WebSocket version 13 server handshake key: JxpqT6RicaAuHeciUPOpTQ==, response: vOzv+QnhO0qgXVDnFJuq9cuvmRM=

2022-06-16 19:53:40.369+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:53:40.368 TRACE - process(129): (HTTP/1.1 101 Switching Protocols

2022-06-16 19:53:40.369+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | upgrade: websocket

2022-06-16 19:53:40.369+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | connection: upgrade

2022-06-16 19:53:40.369+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | sec-websocket-accept: vOzv+QnhO0qgXVDnFJuq9cuvmRM=

2022-06-16 19:53:40.369+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 

2022-06-16 19:53:40.369+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | )

[...some time passed, no disconnect, no requests during this...]

2022-06-16 19:54:19.700+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.695 TRACE - calling eth1GetPowChainHead()

2022-06-16 19:54:19.700+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.696 DEBUG - Sending request: {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":127}

2022-06-16 19:54:19.700+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.697 TRACE - send frame: Framedata{ opcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payload length:[pos:0, len:84], payload:{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":127}}

2022-06-16 19:54:19.700+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.697 TRACE - afterEnconding(84): {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":127}

2022-06-16 19:54:19.700+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.698 TRACE - write(90): ???<??????R????????????T??????T???H???_???r???Y??????]??????]???H???]???a???X?????

2022-06-16 19:54:19.701+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:54:19.700+00:00 | vert.x-eventloop-thread-1 | TRACE | WebSocket08FrameDecoder | Decoding WebSocket Frame opCode=1

2022-06-16 19:54:19.701+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:54:19.700+00:00 | vert.x-eventloop-thread-1 | TRACE | WebSocket08FrameDecoder | Decoding WebSocket Frame length=84

2022-06-16 19:54:19.703+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:54:19.703+00:00 | vert.x-eventloop-thread-1 | DEBUG | JsonRpcService | Received Websocket request (binary frame) {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":127} (host=192.168.0.3, port=35402)

2022-06-16 19:54:19.708+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:54:19.707+00:00 | vert.x-worker-thread-14 | DEBUG | JsonRpcExecutor | JSON-RPC request -> eth_getBlockByNumber [latest, false]

2022-06-16 19:54:19.713+04:00 | docker-java-stream-2016637102 | DEBUG | BesuNode | 2022-06-16 15:54:19.712+00:00 | vert.x-eventloop-thread-1 | TRACE | WebSocket08FrameEncoder | Encoding WebSocket Frame opCode=1 length=75

2022-06-16 19:54:19.713+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.713 TRACE - process(77): (?K{"jsonrpc":"2.0","id":127,"error":{"code":-40100,"message":"Unauthorized"}})

2022-06-16 19:54:19.714+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.714 TRACE - afterDecoding(75): {"jsonrpc":"2.0","id":127,"error":{"code":-40100,"message":"Unauthorized"}}

2022-06-16 19:54:19.714+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.714 TRACE - matched frame: Framedata{ opcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payload length:[pos:0, len:75], payload:{"jsonrpc":"2.0","id":127,"error":{"code":-40100,"message":"Unauthorized"}}}

2022-06-16 19:54:19.714+04:00 | docker-java-stream-20655709 | DEBUG | TekuNode | 2022-06-16 15:54:19.714 DEBUG - Received message {"jsonrpc":"2.0","id":127,"error":{"code":-40100,"message":"Unauthorized"}} from server ws://besunode1:8550
```

### PR DESCRIPTION
**Pull request by jflo**
fixes #3990

### CODE REVIEW

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/MutableJsonRpcSuccessResponse.java [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+
+import java.util.Objects;
+
+import com.fasterxml.jackson.annotation.JsonGetter;
+import com.fasterxml.jackson.annotation.JsonIgnore;
+import com.fasterxml.jackson.annotation.JsonPropertyOrder;
+import com.fasterxml.jackson.annotation.JsonSetter;
+
+@JsonPropertyOrder({"jsonrpc", "id", "result"})
+public class MutableJsonRpcSuccessResponse {
```
Comment (garyschulte) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/MutableJsonRpcSuccessResponse.java:25]: can this be moved to src/test ?  It looks like it is only used as a deserialization target in tests

**Review by garyschulte — COMMENTED** [review]
LGTM, just a question about test serialization class

**Review by garyschulte — APPROVED** [review]
:ship:
