### PR TITLE
JsonBlockImporter to use GenericBlockCreator instead of PoW

### LINKED ISSUE #9713: [PoW removal] decouple JsonBlockImporter
PoW removal - next thing to be unpicked from PoW is JsonBlockImporter
this uses PoW to create blocks, from Json, for testing. 
Naive removal of PoW causes JsonBlockImporter to fail, see PR #9528  

It might be overkill to use engineAPI for this, there is probably a better way to do it

### PR DESCRIPTION
**Pull request by macfarla**
## PR description

Note that of the 220 files changed, 206 are test changes resulting from:
  - Updates 206 trace spec files with new blockHash values resulting from nonce=0/difficulty=ZERO block headers which come from GenericBlockCreator, a minimal AbstractBlockCreator subclass that creates blocks with nonce=0 and difficulty=ZERO
  - Corrects trace_callMany spec values: SSTORE-to-dirty-storage cost is now 800 gas (Istanbul-correct) instead of 5000 (OpenEthereum bug documented in existing TODO) - this was ignored before, but regenerating the test files brought this up.

The code changes are:
  - Decouples JsonBlockImporter from MiningCoordinator by introducing GenericBlockCreator, a minimal AbstractBlockCreator subclass that creates blocks with nonce=0 and difficulty=ZERO
  - JsonBlockImporter now instantiates GenericBlockCreator directly instead of routing through MiningCoordinator.createBlock(), which returns Optional.empty() from NoOpMiningCoordinator
  - Exposes EthScheduler via BesuController.getEthScheduler() (required by AbstractBlockCreator)
  - Switches JsonBlockImporterTest from Clique to mainnet genesis (no consensus-specific coordinator needed)
  - Adds UPDATE_SPECS mechanism to AbstractJsonRpcHttpBySpecTest for maintaining spec files when block generation changes

  Context

  Part of PoW removal (#9455). With PoWMiningCoordinator replaced by NoOpMiningCoordinator (#9528), JsonBlockImporter breaks because it called MiningCoordinator.createBlock(). Rather
  than adding block creation to NoOpMiningCoordinator, this PR removes the dependency entirely — JsonBlockImporter only needs to assemble a block from transactions and a parent header,
  then import it with HeaderValidationMode.NONE.

  Test plan

  - ./gradlew :app:test --tests "*JsonBlockImporterTest*" — block import with mainnet genesis
  - ./gradlew :ethereum:api:test — all trace spec tests (forest + bonsai)

## Fixed Issue(s)
fixes #9713

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [x] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] spotless: `./gradlew spotlessApply`
- [x] unit tests: `./gradlew build`
- [x] acceptance tests: `./gradlew acceptanceTest`
- [x] integration tests: `./gradlew integrationTest`
- [x] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [x] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: app/src/main/java/org/hyperledger/besu/controller/BesuController.java [hunk 1]
```diff
@@ -117,7 +120,8 @@ public class BesuController implements java.io.Closeable {
       final EthPeers ethPeers,
       final StorageProvider storageProvider,
       final DataStorageConfiguration dataStorageConfiguration,
-      final TransactionSimulator transactionSimulator) {
+      final TransactionSimulator transactionSimulator,
+      final EthScheduler ethScheduler) {
```
Comment (fab-10) [inline app/src/main/java/org/hyperledger/besu/controller/BesuController.java]: you can have it indirectly from `EthProtocolManager`, w/o adding a new parameter

Comment (macfarla) [reply app/src/main/java/org/hyperledger/besu/controller/BesuController.java]: done
