### PR TITLE
Fix #1110: Privacy: Restart caused by insufficient memory can cause inconsistent private state

### LINKED ISSUE #1110: Privacy: Restart caused by insufficient memory can cause inconsistent private state
Tasks:
- [x] Deploy updated Orion and Besu to test network
- [ ] Rerun test scripts and validate changes

While running reorg testing with six besu/orion clients the following happened on two of the machines causing the state on that machine to become inconsistent with the rest of the members of the privacy group:

Besu Log:
{"timestamp":"2020-06-14T02:11:30,248","level":"INFO","thread":"EthScheduler-Workers-1","class":"BlockPropagationManager","message":"Imported #8,088,448 / 4 tx / 0 om / 4,475,388 (55.9%) gas / (0xa8f49cdc62fcf7de79b42d46ffcb89cbaafd8656dcc112fb9fd39c8b792c1373) in 0.903s. Peers: 39","throwable":""}
{"timestamp":"2020-06-14T02:13:18,932","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 8088450 (0x8ae8ca9866c1e626933fb4828ab9c8775afae74dc7c577e9e5b16a401178e839) for future import","throwable":""}
{"timestamp":"2020-06-14T02:15:05,908","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"BlockPropagationManager","message":"Saving announced block 8088451 
.
. <some log lines left out>
.
{"timestamp":"2020-06-14T02:15:09,286","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"BlockPropagationManager","message":"Saving announced block 8088463 (0x2352f8e831f2a2a13dcb4e70f3ffaefb05ff8e09cdafdc1de40d12affe80461a) for future import","throwable":""}
{"timestamp":"2020-06-14T02:15:09,300","level":"INFO","thread":"nioEventLoopGroup-3-5","class":"BlockPropagationManager","message":"Saving announced block 8088464 (0x207de6caace4575bb29e75b98801e53d321750a9e63b0f1d323938cbb708eab8) for future import","throwable":""}
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e6c00000, 90177536, 0) failed; error='Not enough space' (errno=12)
[thread 21178 also had an error]
[thread 21183 also had an error]
[thread 21192 also had an error]
[thread 21257 also had an error]
[thread 21127 also had an error]
[thread 21117 also had an error]
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 90177536 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid21038.log
[thread 21179 also had an error]
[thread 21181 also had an error]
Recording 1 scheduled to start in 15 s.

Use jcmd 30545 JFR.dump name=1 to copy recording data to file.
Setting logging level to INFO
{"timestamp":"2020-06-14T02:15:33,476","level":"INFO","thread":"main","class":"AltBN128PairingPrecompiledContract","message":"Using native alt bn128","throwable":""}
{"timestamp":"2020-06-14T02:15:34,447","level":"INFO","thread":"main","class":"SECP256K1","message":"Using native secp256k1","throwable":""}
.
. <some log lines left out>
.
{"timestamp":"2020-06-14T02:15:56,154","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 1","throwable":""}
{"timestamp":"2020-06-14T02:15:57,949","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"SyncTargetManager","message":"Found common ancestor with peer 0x936ac2bf0b816350eb... at block 8088448","throwable":""}
{"timestamp":"2020-06-14T02:16:07,093","level":"INFO","thread":"nioEventLoopGroup-3-4","class":"BlockPropagationManager","message":"Saving announced block 8088467 (0xd9c239e06ffedcc87005f3d4ac06513260baf3206a21a1585b9f38ef4c7da36f) for future import","throwable":""}
{"timestamp":"2020-06-14T02:16:08,486","level":"INFO","thread":"nioEventLoopGroup-3-6","class":"BlockPropagationManager","message":"Saving announced block 8088466 (0x11fa862f07df203a8a5e39b100ba21d80900f591c8a1c8930f5322fdeddc56e2) for future import","throwable":""}
**{"timestamp":"2020-06-14T02:16:12,404","level":"ERROR","thread":"EthScheduler-Services-5 (importBlock)","class":"PrivacyPrecompiledContract","message":"Failed to process private transaction 0x74c37eb6c8d172ca6a41420ffbb963f848ae92eb6aaa28e85bfcaffcb4b429d5: Private Transaction nonce 0, is lower than sender account nonce 1.","throwable":""}**
{"timestamp":"2020-06-14T02:16:41,452","level":"INFO","thread":"EthScheduler-Workers-1","class":"BlockPropagationManager","message":"Imported 1 pending blocks","throwable":""}

### PR DESCRIPTION
**Pull request by pinges**
Signed-off-by: Stefan Pingel <stefan.pingel@consensys.net>

## Fixed Issue(s)
https://github.com/hyperledger/besu/issues/1110

### CODE REVIEW

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateStateRootResolver.java [hunk 1]
```diff
@@ -33,6 +34,26 @@ public PrivateStateRootResolver(final PrivateStateStorage privateStateStorage) {
...
+    if (privateBlockMetadata != null) {
+      return privateBlockMetadata.getLatestStateRoot().get();
+    } else {
+      final Hash blockHashForLastBlockWithTx =
+          privateMetadataUpdater.getPrivacyGroupHeadBlockMap().get(privacyGroupId);
+      if (blockHashForLastBlockWithTx != null) {
+        return privateStateStorage
+            .getPrivateBlockMetadata(blockHashForLastBlockWithTx, privacyGroupId)
+            .flatMap(PrivateBlockMetadata::getLatestStateRoot)
+            .orElse(EMPTY_ROOT_HASH);
```
Comment (lucassaldanha) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateStateRootResolver.java:50]: Should this ever happen? If we have a hash on our `PrivacyGroupHeadBlockMap`, we should always find the state root for it, should we?

Maybe this should throw an error.

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java [hunk 2]
```diff
@@ -79,20 +80,23 @@ public Result processBlock(
       final MutableWorldState worldState,
       final BlockHeader blockHeader,
       final List<Transaction> transactions,
-      final List<BlockHeader> ommers) {
+      final List<BlockHeader> ommers,
+      final PrivateMetadataUpdater privateMetadataUpdater) {
+
+    if (privateMetadataUpdater != null) {
```
Comment (lucassaldanha) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java:86]: I don't think I understand why we need this if statement. Is this because for each new block we need a new PrivateMetadataUpdater, and not reuse a previous one?

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java [hunk 3]
```diff
@@ -79,20 +80,23 @@ public Result processBlock(
...
-        .putPrivacyGroupHeadBlockMap(blockHeader.getHash(), privacyGroupHeadBlockMap)
-        .commit();
-    return blockProcessor.processBlock(blockchain, worldState, blockHeader, transactions, ommers);
+    final PrivateMetadataUpdater metadataUpdater =
+        new PrivateMetadataUpdater(blockHeader, privateStateStorage);
+
+    final Result result =
+        blockProcessor.processBlock(
+            blockchain, worldState, blockHeader, transactions, ommers, metadataUpdater);
+    metadataUpdater.commit();
```
Comment (lucassaldanha) [inline ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java:98]: At this point, has Besu already commit the changes in public world state?

Comment (pinges) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java:98]: Yes, the public changes have been commited at the end of the wrapped block processor.

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java (hunk 2 above)
Comment (pinges) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java:86]: I wasn't hundred percent sure either. But for every block that we are processing we do need a new PrivateMetadataUpdater. We are instantiating one in this block processor that is wrapping the public block processor.
If there was an updater passed in I thought that something must have gone wrong ...

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateStateRootResolver.java (hunk 1 above)
Comment (pinges) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateStateRootResolver.java:50]: I think you are right. I think I have copied that from the original code and did not really question that. I will fix both!

Comment (pinges) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivateStateRootResolver.java:50]: You are right. Copied that from the original method without questioning it. Will fix both!

File: ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java (hunk 3 above)
Comment (pinges) [reply ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PrivacyBlockProcessor.java:98]: ... but the block has not been added to the chain yet. That is happening later.
