### PR TITLE
[2982] Handle operation not permitted exception (firewall)

### LINKED ISSUE #2982: java.net.SocketException: Operation not permitted
### Description
As a node operator, I want logging that it is not flooded by unnecessary error messages.

### Steps to Reproduce (Bug)
1. Add a firewall rule to block unroutable outgoing traffic like `ufw deny out to 100.64.0.0/10`.
2. Start Besu and wait till it tries to connect to a `100.64.0.0/10` ip.

**Expected behavior:** [What you expect to happen]
1. Less verbose or even no logging of this expected behaviour.

**Actual behavior:** [What actually happens]

```
Oct 31 23:45:19 dakara docker[807879]: 2021-10-31 22:45:19.561+00:00 | vert.x-eventloop-thread-1 | WARN  | PeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, enode=enode://3b8cde6fd28498b922c46fa340696a809cdba1f53d2830a90492edd60480fb57bd0a2b2c537fffaa6582b39ecc8d2732a54967da805f46740f0d0e46c32d7f35@100.64.229.95:10104, firstDiscovered=1635720310059, lastContacted=0, lastSeen=0} failed, packet: 0xbed75c82206fe0ce8d26e55e6d414cb7171017a8d206d333d7b32101ec2af0b25a2041718b5a0719d6c21b5547f9242ce633099e5550f0176e2741ef6156b2f65bef963ce1f1d33ad0d46baac84c82c4e2e688eafbeb1fe8a5455a89ec2da10b0101df05cb844115596382765f82765fcb846440e55f82277882277884617f1cbb0f
Oct 31 23:45:19 dakara docker[807879]: java.net.SocketException: Operation not permitted
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:296)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:949)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:913)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.datagram.impl.DatagramSocketImpl.doSend(DatagramSocketImpl.java:280)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$send$2(DatagramSocketImpl.java:268)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:88)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/java.lang.Thread.run(Thread.java:833)
```

**Frequency:** [What percentage of the time does it occur?]

100%

### Versions (Add all that apply)
* Software version: `besu/v21.10.0-RC4/linux-x86_64/oracle_openjdk-java-17`
* Docker Version: `20.10.5+dfsg1` (running with `--network host`)
* OS: Debian Bullseye

### Additional Information

Some hosting providers do not allow to send local and/or unrouteable traffic.

https://github.com/openethereum/parity-ethereum/issues/2478
https://github.com/ethereum/go-ethereum/issues/15957
https://community.hetzner.com/tutorials/block-outgoing-traffic-to-private-networks

### PR DESCRIPTION
**Pull request by frankisawesome**
Signed-off-by: Frank Li <b439988l@gmail.com>

## PR description
Hide these exceptions to DEBUG logging level as per https://github.com/hyperledger/besu/issues/2982

## Fixed Issue(s)

Fixes #2982

## Changelog

Don't need changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

File: ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java [hunk 1]
```diff
@@ -315,6 +315,12 @@ protected void handleOutgoingPacket(final DiscoveryPeer peer, final Packet packe
                 if (err instanceof SocketException && err.getMessage().contains("unreachable")) {
                   LOG.debug(
                       "Peer {} is unreachable, packet: {}", peer, wrapBuffer(packet.encode()), err);
+                } else if (err instanceof SocketException
+                    && err.getMessage().contains("permitted")) {
```
Comment (pinges) [inline ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java:319]: Can / should we make that a bit more precise than "permitted"?

**Review by pinges — APPROVED** [review]
Please have a look at the comment.

File: ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java (hunk 1 above)
Comment (frankisawesome) [reply ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java:319]: I'm going off the previous one which searches for "unreachable" 😛 but yeah I'll put in the whole message there

**Review by pinges — APPROVED** [review]
