### PR TITLE
Speed up backward sync phase 1 relinking after restart

### LINKED ISSUE #10103: Backward sync phase 1 slow relinking after restart
If Besu backward sync fails during phase 2, when we restart the backward sync we phase 1 takes lot of time to relink headers leaving phase 1 log at 0% for about 20 minutes. The main issue looks like `BackwardSyncStep.possibleRestoreOldNodes` ends up iterating over millions of headers and making rocksdb transactions.

### PR DESCRIPTION
**Pull request by veyron-kairo**
### PR description

Fixes #10103.

If a node restarts mid backward sync, phase 1 has to re-link every header that was saved in the previous session before it can resume downloading. On a chain where a couple of million headers are already on disk, this was taking roughly 20 minutes with the progress log stuck at 0%, which made it look like the sync was hung.

The culprit is `BackwardSyncStep.possibleRestoreOldNodes`. It walks the stored parent chain one header at a time and calls `BackwardChain.prependAncestorsHeader` for each one. Under the hood every call opens two separate RocksDB transactions (one for the chain-link write, one for the session-data update). So N headers produced ~2N transactions, and the per-transaction overhead dominated.

This PR keeps the walk, but buffers the headers into bounded batches of 1000 and hands each batch to a new `BackwardChain.prependRestoredAncestorsHeaders` helper. The helper builds all the parent-to-child links for that batch in a single `LinkedHashMap` and commits them to `chainStorage` with one `putAll`, then updates `firstStoredAncestor` once. The chunk size keeps memory bounded while still cutting transaction count by three orders of magnitude.

Restart relink time on a chain with ~10M already-stored headers drops from roughly 20 minutes to a few seconds in my local runs.

### Fixed Issue(s)

- fixes #10103

### Testing

Added `restoreOldNodesShouldPrependHeadersViaBatchedWrite` in `BackwardSyncStepTest`. It simulates a crashed previous session by writing a trail of ancestor headers into the headers KV store without any chain links, then runs `possibleRestoreOldNodes` and asserts:
- the walk terminates at the expected hash (genesis parent of block 1 in the fixture);
- `prependRestoredAncestorsHeaders` was invoked;
- `firstStoredAncestor` ends up at the lowest restored header;
- every restored header is actually linked to its child in `chainStorage` afterwards (i.e. the chain is intact, not just the bookkeeping).

The existing `shouldFindHashToSync` test continues to pass, so the non-restoring path is unchanged.

### Notes

- No protocol- or config-level changes; the batch size is an internal constant (`RESTORE_BATCH_SIZE = 1_000`).
- The new helper falls back to the same behaviour as the old loop if `firstStoredAncestor` is empty, so callers outside `possibleRestoreOldNodes` wouldn't see any semantic change either.

### CODE REVIEW

**Comment by sridhar-panigrahi** [comment]
@jframe this is the fix for #10103 — putting it up for your review whenever you have a moment. The per-header RocksDB transactions in possibleRestoreOldNodes were the root cause of the ~20 min phase-1 stall on restart; batching them brings it down to a few seconds locally. Happy to iterate on the batch size or the helper's shape if you'd prefer it structured differently.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java [hunk 1]
```diff
@@ -50,10 +52,18 @@ public CompletableFuture<Void> executeAsync(final BlockHeader firstHeader) {
   protected Hash possibleRestoreOldNodes(final BlockHeader firstAncestor) {
     Hash lastHash = firstAncestor.getParentHash();
     Optional<BlockHeader> iterator = backwardChain.getHeader(lastHash);
+    final List<BlockHeader> batch = new ArrayList<>(RESTORE_BATCH_SIZE);
     while (iterator.isPresent()) {
-      backwardChain.prependAncestorsHeader(iterator.get(), true);
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardSyncStep.java:54]: With this change `prependAncestorsHeader` now always gets called with false. So the true case be removed from that method.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 2]
```diff
@@ -147,6 +149,48 @@ public synchronized void prependAncestorsHeader(
...
+   */
+  public synchronized void prependRestoredAncestorsHeaders(
+      final List<BlockHeader> restoredHeaders) {
+    if (restoredHeaders.isEmpty()) {
+      return;
+    }
+
+    int firstIndex = 0;
+    if (firstStoredAncestor.isEmpty()) {
+      updateLastStoredPivot(Optional.of(restoredHeaders.get(0)));
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java]:
```suggestion
      updateLastStoredPivot(Optional.of(restoredHeaders.getFirst()));
```

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 3]
```diff
@@ -147,6 +149,48 @@ public synchronized void prependAncestorsHeader(
...
+      updateFirstStoredAncestor(Optional.of(restoredHeaders.get(0)));
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java]:
```suggestion
      updateFirstStoredAncestor(Optional.of(restoredHeaders.getFirst()));
```

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 4]
```diff
@@ -147,6 +149,48 @@ public synchronized void prependAncestorsHeader(
...
+      Hash childHash = firstStoredAncestor.orElseThrow().getHash();
+      for (int i = firstIndex; i < restoredHeaders.size(); i++) {
+        final Hash parentHash = restoredHeaders.get(i).getHash();
+        chainLinks.put(parentHash, childHash);
+        childHash = parentHash;
+      }
+      chainStorage.putAll(chainLinks);
+    }
+
+    final BlockHeader lowestRestored = restoredHeaders.get(restoredHeaders.size() - 1);
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java]:
```suggestion
    final BlockHeader lowestRestored = restoredHeaders.getLast();
```

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java [hunk 5]
```diff
@@ -147,6 +149,48 @@ public synchronized void prependAncestorsHeader(
...
+    if (firstStoredAncestor.isEmpty()) {
+      updateLastStoredPivot(Optional.of(restoredHeaders.get(0)));
+      updateFirstStoredAncestor(Optional.of(restoredHeaders.get(0)));
+      firstIndex = 1;
+    }
+
+    if (firstIndex < restoredHeaders.size()) {
+      final Map<Hash, Hash> chainLinks = new LinkedHashMap<>(restoredHeaders.size() - firstIndex);
+      Hash childHash = firstStoredAncestor.orElseThrow().getHash();
+      for (int i = firstIndex; i < restoredHeaders.size(); i++) {
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/BackwardChain.java]: I think this could replaced a for each i.e. doing this instead `for (final BlockHeader header: restoredHeaders) {`

**Comment by jframe** [comment]
> @jframe this is the fix for #10103 — putting it up for your review whenever you have a moment. The per-header RocksDB transactions in possibleRestoreOldNodes were the root cause of the ~20 min phase-1 stall on restart; batching them brings it down to a few seconds locally. Happy to iterate on the batch size or the helper's shape if you'd prefer it structured differently.

Did you test this on Hoodi or mainnet? And did it fix the backwards sync issue there? Not sure on the batch size either. But I think 1000 seems reasonable for now.

**Comment by veyron-kairo** [comment]
Thanks for taking a look, @jframe!

On the testing question — I've only been able to reproduce and verify this locally against a node with an interrupted backward sync session (restarted mid-phase-1). I haven't had a chance to run it on Hoodi or mainnet yet, though it does take a while on my end. If someone on the team has a convenient way to validate on a live network in the meantime, that'd be great too.

Applied all your inline suggestions — thanks for the catches:

- Removed the `alreadyStored` overload of `prependAncestorsHeader` since the `true` path was dead after the batch refactor. Collapsed it into the single-arg method.
- Updated `restoredHeaders.get(0)` → `getFirst()` and `get(size - 1)` → `getLast()`.
- Replaced the indexed for-loop with a for-each over `restoredHeaders.subList(firstIndex, restoredHeaders.size())` to keep the skip-first-element logic intact when `firstStoredAncestor` was empty on entry.

Let me know if anything else needs adjusting!

**Comment by jframe** [comment]
> Thanks for taking a look, @jframe!
> 
> On the testing question — I've only been able to reproduce and verify this locally against a node with an interrupted backward sync session (restarted mid-phase-1). I haven't had a chance to run it on Hoodi or mainnet yet, though it does take a while on my end. If someone on the team has a convenient way to validate on a live network in the meantime, that'd be great too.

No problem, Hoodi and mainnet sync is more for a sanity check. I'll do some syncs and let you know.

> Applied all your inline suggestions — thanks for the catches:
> 
> * Removed the `alreadyStored` overload of `prependAncestorsHeader` since the `true` path was dead after the batch refactor. Collapsed it into the single-arg method.
> * Updated `restoredHeaders.get(0)` → `getFirst()` and `get(size - 1)` → `getLast()`.
> * Replaced the indexed for-loop with a for-each over `restoredHeaders.subList(firstIndex, restoredHeaders.size())` to keep the skip-first-element logic intact when `firstStoredAncestor` was empty on entry.
> 
> Let me know if anything else needs adjusting!

**Comment by jframe** [comment]
It works well in my testing. Just need to fix that conflict on the changelog now so latest main can be merged in.

**Review by jframe — APPROVED** [review]

**Comment by veyron-kairo** [comment]
Hey @jframe, resolved the changelog conflict — merged in the latest main and kept both entries. Should be clean now, ready whenever you want to merge it!
