### PR TITLE
Reintroduce consortium network friendly EIP-2124 fork id management.

### LINKED ISSUE #1002: Ethereum Classic EIP-2124 fork id management is broken.
https://github.com/hyperledger/besu/pull/979 and https://github.com/hyperledger/besu/pull/981 pull requests broke fork id management on Ethereum Classic.
The problem seems to be located in `ForkIdManager.getLatestForkId` method. A quick test showed using `legacyForkAndHashList` instead of `forkAndHashList` makes it work. Should verify the impact on ETH.

### PR DESCRIPTION
**Pull request by abdelhamidbakhta**
## PR description
#979 and #981 pull requests broke fork id management on some networks.
Hence, the consortium network friendly has been disabled. This PR reintroduces it by fixing the edge cases.

### Testing

|   Network	| Status  	| 
|---	|---	|
|  mainnet 	|  OK 	| 
|  ropsten 	|  OK 	| 
|  goerli 	|  OK 	|
|  mordor 	|  OK 	|  
## Fixed Issue(s)
fixes #1002 

Signed-off-by: Abdelhamid Bakhta <abdelhamid.bakhta@consensys.net>

### CODE REVIEW

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 1]
```diff
@@ -30,22 +34,59 @@
...
+            genesisHash,
+            forks,
+            fs ->
+                fs.stream()
+                    .filter(fork -> fork > 0)
+                    .distinct()
+                    .collect(Collectors.toUnmodifiableList()),
+            forkAndHashList);
+    // if the fork list contains only zeros then we may be in a consortium/dev network
+    if (onlyZerosForkBlocks(forks)) {
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:58]: What happens if we have a few 0 forks but others greater than 0? Would we do the right thing?

Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:58]: Yes we would to the right thing. This is what happens on Goerli:
```json
{
  "config":{
    "chainId":5,
    "homesteadBlock":0,
    "eip150Block":0,
    "eip150Hash": "0xbf7e331f7f7c1dd2e05159666b3bf8bc7a8a3a9eb1d518969eab529dd9b88c1a",
    "eip155Block":0,
    "eip158Block":0,
    "eip160Block":0,
    "byzantiumBlock":0,
    "constantinopleBlock":0,
    "petersburgBlock":0,
    "istanbulBlock":1561651,
    "clique":{
      "blockperiodseconds":15,
      "epochlength":30000
    }
  }
```

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 2]
```diff
@@ -30,22 +34,59 @@
...
-  private long forkNext;
-  private final long highestKnownFork;
-  private List<ForkId> forkAndHashList;
+  private final List<ForkId> forkAndHashList;
+
+  private final List<ForkIDChecker> forkIDCheckers;
 
   public ForkIdManager(final Blockchain blockchain, final List<Long> forks) {
-    this.blockchain = blockchain;
+    assert blockchain != null && forks != null;
```
[the remark this answers is not in the document]
Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:43]: I have a unit test verifying this specific assertion error and it passes. I thought it was enabled by default on recent Java versions.
I will change with `Preconditions.checkNotNull` then

[the remark this answers is not in the document]
Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java]: Done

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 3]
```diff
@@ -257,4 +316,9 @@ private static void intToBigEndian(final int n, final byte[] bs, int off) {
     bs[++off] = (byte) (n >>> 8);
     bs[++off] = (byte) (n);
   }
+
+  @FunctionalInterface
+  private interface ForkIDChecker {
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:321]: I suggest we put `implements Predicate<ForkId>` here so that we can get all the other `Predicate` methods for free

Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:321]: Nice catch. Done

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java (hunk 1 above)
Comment (shemnon) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:61]: Unit tests and the EIP2124 spec also validate that the correct hashes are arrived at.
