### PR TITLE
Fix flaky test: Permissioning + IBFT stall

### LINKED ISSUE #1011: Fix NodeSmartContractPermissioningIbftStallAcceptanceTest
The fix for blocking on randomness for a large number of other tests has made this one more flakey, possibly because timeouts are mis-firing.  We need to revisit this one and fix it.  In the interim I'm marking it `@Ignore`

### PR DESCRIPTION
**Pull request by macfarla**
## PR description
Test was failing with timeout when trying to verify that node was added to whitelist successfully. This was because blocks were not yet being produced, caused by IBFT rounds not completing successfully - ie nodes were still starting up and getting rounds in sync (takes ~1.5 min). Block 1 is usually produced in IBFT round 2 or 3.

To fix:
* verify that blocks are being produced BEFORE trying to send transactions adding nodes to whitelist
* reduced number of validators from 4 to 2
* reduced height of blocks being waited for in between test logic, since this was just wasting time - test doesn't require 15 blocks, we just need to know blocks are being produced
* removed checks for number of peers since this is already done in cluster.start()
 
## Fixed Issue(s)
Fixes #1011

### CODE REVIEW

File: acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningIbftStallAcceptanceTest.java [hunk 1]
```diff
@@ -73,12 +67,10 @@ public void restartedIbftClusterShouldNotStall() throws IOException {
...
     nodeB.setPermissioningConfiguration(permissioningConfiguration);
-    nodeC.setPermissioningConfiguration(permissioningConfiguration);
-    nodeD.setPermissioningConfiguration(permissioningConfiguration);
 
-    permissionedCluster.start(bootnode, nodeA, nodeB, nodeC, nodeD);
+    permissionedCluster.start(bootnode, nodeA, nodeB);
 
     // Verify blockchain is progressing
-    waitForBlockHeight(bootnode, 15);
+    bootnode.verify(blockchain.reachesHeight(bootnode, 1, 120));
```
Comment (jframe) [inline acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningIbftStallAcceptanceTest.java:74]: Think we should check all nodes have progressed not just the bootnode. So something like permissionedCluster.verify(blockchain.reachesHeight(bootnode, 1, 120))

Comment (macfarla) [reply acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningIbftStallAcceptanceTest.java]: done
