### PR TITLE
Shanghai Engine API Updates

### LINKED ISSUE #4916: Shanghai Engine API Updates
https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md
(c.f. https://hackmd.io/@n0ble/rywPcPTci)

Think some changes were introduced for V2 in https://github.com/ethereum/execution-apis/pull/338 which haven't been considered...

https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#specification

> 1. Client software MAY NOT validate terminal PoW block conditions during payload validation (point (2) in the Payload validation routine).
> 2. Client software MUST return {status: INVALID, latestValidHash: null, validationError: errorMessage | null} if the blockHash validation has failed.

https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#specification-1

> 1. Client software MAY NOT validate terminal PoW block conditions in the following places:
> * during payload validation (point (2) in the Payload validation routine specification),
> * when updating the forkchoice state (point (3) in the engine_forkchoiceUpdatedV1 method specification).

### PR DESCRIPTION
**Pull request by wcgcyx**
Signed-off-by: Zhenyang Shi <wcgcyx@gmail.com>

## PR description
Update engine API to include some new changes introduced in 
- [ethereum/execution-apis#338](https://github.com/ethereum/execution-apis/pull/338) and 
- [ethereum/execution-apis#337](https://github.com/ethereum/execution-apis/pull/337)

## Fixed Issue(s)

fixes #4916 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java [hunk 1]
```diff
@@ -244,7 +247,8 @@ public void shouldReturnValidWithoutFinalizedWithPayload() {
     BlockHeader mockHeader = blockHeaderBuilder.buildHeader();
     when(mergeCoordinator.getOrSyncHeadByHash(mockHeader.getHash(), Hash.ZERO))
         .thenReturn(Optional.of(mockHeader));
-    when(mergeCoordinator.latestValidAncestorDescendsFromTerminal(mockHeader)).thenReturn(true);
+    if (validateTerminalPoWBlock())
```
Comment (siladu) [inline ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java:250]: nit: think it's clearer (and more conventional with besu's code style) to use braces after the if () {...}

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java [hunk 2]
```diff
@@ -198,6 +199,7 @@ public void shouldReturnSuccessOnAlreadyPresent() {
 
   @Test
   public void shouldReturnInvalidOnBadTerminalBlock() {
+    if (!validateTerminalPoWBlock()) return;
```
Comment (siladu) [inline ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java:202]: For this test, probably better handled by cut-and-pasting this whole test into V1Test

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java [hunk 3]
```diff
@@ -526,12 +529,21 @@ private BlockHeader setupValidPayload(final BlockProcessingResult value) {
...
+          .thenReturn(true);
     when(mergeCoordinator.rememberBlock(any())).thenReturn(value);
     return mockHeader;
   }
 
+  protected boolean validateTerminalPoWBlock() {
+    return false;
+  }
+
+  protected ExecutionEngineJsonRpcMethod.EngineStatus getCorrectInvalidBlockHashStatus() {
```
Comment (siladu) [inline ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java:543]: I prefer 'expected' over 'correct' like your other tests: expectedInvalidBlockHashStatus

**Review by siladu — COMMENTED** [review]
Couple of nits but LGTM.

Will let a second reviewer approve since I paired with you on this a bit.

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java (hunk 3 above)
Comment (macfarla) [reply ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java:543]: or just getInvalidBlockHashStatus

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1Test.java [hunk 4]
```diff
@@ -32,4 +35,14 @@ public EngineNewPayloadV1Test() {
...
     assertThat(method.getName()).isEqualTo("engine_newPayloadV1");
   }
+
+  @Override
+  protected boolean validateTerminalPoWBlock() {
+    return true;
+  }
+
+  @Override
+  protected ExecutionEngineJsonRpcMethod.EngineStatus getCorrectInvalidBlockHashStatus() {
```
Comment (macfarla) [inline ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1Test.java:45]:
```suggestion
  protected ExecutionEngineJsonRpcMethod.EngineStatus getInvalidBlockHashStatus() {
```

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java (hunk 3 above)
Comment (macfarla) [reply ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java:543]:
```suggestion
  protected ExecutionEngineJsonRpcMethod.EngineStatus getInvalidBlockHashStatus() {
```

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java [hunk 5]
```diff
@@ -154,7 +155,7 @@ public JsonRpcResponse syncResponse(final JsonRpcRequestContext requestContext)
           "Invalid payload attributes: {}",
           () ->
               maybePayloadAttributes.map(EnginePayloadAttributesParameter::serialize).orElse(null));
-      return new JsonRpcErrorResponse(requestId, JsonRpcError.INVALID_PAYLOAD_ATTRIBUTES);
```
Comment (macfarla) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java:157]: I didn't see this change mentioned in https://github.com/ethereum/execution-apis/pull/338 - is this something different?

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java (hunk 1 above)
Comment (wcgcyx) [reply ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java]: Updated

File: ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java (hunk 2 above)
Comment (wcgcyx) [reply ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayloadTest.java]: Yes, updated

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java (hunk 5 above)
Comment (wcgcyx) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java:157]: Yea, bring some changes from https://github.com/ethereum/execution-apis/pull/337 too. Sorry should have updated the description.

Comment (siladu) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java:157]: my bad, I got Zhenyang to crowbar that change in too :)

Comment (macfarla) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java:157]: ok makes sense

**Review by macfarla — APPROVED** [review]
LGTM

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java [hunk 6]
```diff
@@ -208,7 +208,8 @@ public JsonRpcResponse syncResponse(final JsonRpcRequestContext requestContext)
     }
 
     // TODO: post-merge cleanup
-    if (!mergeContext.get().isCheckpointPostMergeSync()
+    if (requireTerminalPoWBlockValidation()
```
Comment (jframe) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java:211]: would be nice to move the terminal pow block condition validation logic into the V1 API now since it's no longer common code

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1.java [hunk 7]
```diff
@@ -39,4 +41,14 @@ public EngineNewPayloadV1(
   public String getName() {
     return RpcMethod.ENGINE_NEW_PAYLOAD_V1.getMethodName();
   }
+
+  @Override
+  protected boolean requireTerminalPoWBlockValidation() {
```
Comment (jframe) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineNewPayloadV1.java:46]: Do these need to be methods? Could just configure Abstract class by passing the in these values. What would be more readable though?

**Review by jframe — APPROVED** [review]
