### PR TITLE
Verify plugins on start

### LINKED ISSUE #8551: Besu should not startup if two versions of the same plugin are loaded
Plugin registration should be stopped if two versions of the same plugin are detected. Failure to do so can result in misconfigurations or outdated plugin versions in the plugin's directory, which may cause the node to malfunction.

When this is detected, Besu should fail fast, with logging to indicate the locations of both conflicting plugins.

### PR DESCRIPTION
**Pull request by fab-10**
## PR description

  Add comprehensive plugin verification on startup

  This PR introduces plugin verification checks that run before plugin registration to ensure compatibility and prevent runtime conflicts. The verification includes:

  - Unique plugin names: Ensures no duplicate plugin names are loaded
  - Artifact catalog validation: Verifies all plugins have associated metadata catalogs
  - Besu version compatibility: Checks plugins were built against the running Besu version
  - Inter-plugin dependency conflicts: Detects when multiple plugins bring different versions of the same dependency
  - Besu dependency conflicts: Identifies plugins bundling dependencies already provided by Besu

The verification behavior is configurable via the new option `plugins-verification-mode`, that could take the values: 
* `NONE` (default): log at WARN any issue found during the verification phase, but does not prevent the start of Besu
* `FULL`: log at ERROR and prevent Besu from starting in case of any issue found during the verification.

More fine grained options could to come later if needed, to further customize the verification phase

The core of the feature is implemented in these classes:
* `PluginVerifier`
* `BesuPluginContextImpl`

the rest of the PR consists mainly in the extensions of the tests to cover all the different scenarios

## Fixed Issue(s)

fixes #8551

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java [hunk 1]
```diff
@@ -220,11 +227,21 @@ public BesuNode(
...
-          } catch (final IOException e) {
-            LOG.error("Could not find plugin \"{}\" in resources", pluginName);
+            try {
+              copyResource(
+                  pluginName + ".jar", homeDirectory.resolve("plugins/" + pluginName + ".jar"));
+              BesuNode.this.plugins.add(pluginName);
+            } catch (final IllegalArgumentException jarException) {
+              // JAR not found, try ZIP
+              try {
+                unzipPlugin(pluginName + ".zip", homeDirectory.resolve("plugins"));
```
Comment (usmansaleem) [inline acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java:237]: nit: do we have any plans to override `plugins` folder name in future?

File: acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/DependencyConflictPluginTest.java [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+import java.util.Collections;
+import java.util.List;
+
+import org.junit.jupiter.api.Test;
+
+public class DependencyConflictPluginTest extends AcceptanceTestBase {
+  private BesuNode pluginNode;
+
+  @Test
+  public void warnOnOutdatedPluginByDefault() throws IOException {
```
Comment (macfarla) [inline acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/DependencyConflictPluginTest.java]:
```suggestion
  public void warnOnDependencyConflictPluginByDefault() throws IOException {
```

File: acceptance-tests/detached-test-plugins/dependency-conflict-2/build.gradle [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+                'Specification-Version': project.version,
+                'Implementation-Title': archiveBaseName,
+                'Implementation-Version': project.version
+        )
+    }
+}
+
+tasks.withType(AbstractArchiveTask).configureEach {
+    archiveVersion = ''
+    archiveBaseName = 'dependencyConflictPlugin1'
```
Comment (macfarla) [inline acceptance-tests/detached-test-plugins/dependency-conflict-2/build.gradle]: should this be 1 or 2?

File: app/src/main/java/org/hyperledger/besu/services/PluginVerifier.java [hunk 4]
```diff
@@ -0,0 +1,498 @@
...
+     * @param url the URL to load the catalog from
+     * @return the loaded artifact catalog
+     * @throws RuntimeException if an I/O error occurs
+     */
+    static ArtifactCatalog load(final URL url) {
+      final var objectMapper = new ObjectMapper();
+      try {
+        return objectMapper.readValue(url, ArtifactCatalog.class);
+      } catch (IOException e) {
+        throw new RuntimeException(e);
```
Comment (usmansaleem) [inline app/src/main/java/org/hyperledger/besu/services/PluginVerifier.java]: nit: UncheckedIOException

File: acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java (hunk 1 above)
Comment (fab-10) [reply acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/BesuNode.java:237]: I do not see any good reason :)

File: app/src/main/java/org/hyperledger/besu/services/PluginVerifier.java (hunk 4 above)
Comment (fab-10) [reply app/src/main/java/org/hyperledger/besu/services/PluginVerifier.java]: done
