### PR TITLE
Fix EIP-2124 Fork identifier for chain compatibility checks.

### LINKED ISSUE #1044: ForkId issue for yolo network
### Description

When there is only 0 blocks on the genesis file we have a null forkId (only private network). 
Result : it is impossible to connect to a geth node

### PR DESCRIPTION
**Pull request by abdelhamidbakhta**
## PR description

Before this pull request `Besu` was using the latest known fork id to create status message for Ethereum P2P protocol handshake.

This latest known fork id was created based on a list of forks retrieved from the Genesis.
For private networks it is possible that all fork blocks number are set to `0`.
The algorithm to compute the valid fork hashes excludes `0` values.
As a result, the list was empty and the `getLatestForkId` was returning `null`. This is an issue when you support `capabilities >= to Eth/64` sub protocol because other peers expect the fork id value in the `RLP` encoded message.
Moreover, the algorithm to compute the fork id should be aware of the chain head number and update `CRC` value only for fork blocks below the current head.
This pull request fixes this issue by fetching the chain head number and update accordingly the `CRC` value.
Unit tests have been extended to cover an exhaustive list of possible combinations on named networks (`goerli`, `rinkeby`, `ropsten` and `mainnet`).

## Fixed Issue(s)

fixes #1044 

### Automated 
Added unit tests.
[Test Results - EIP2124Test.pdf](https://github.com/hyperledger/besu/files/4735725/Test.Results.-.EIP2124Test.pdf)

### Manual

|   Network	| Status  	| 
|---	|---	|
|  mainnet 	|  OK 	| 
|  ropsten 	|  OK 	| 
|  goerli 	|  OK 	|
|  mordor 	|  OK	|  
|  classic 	|  NOT STARTED	|  
|  private 	|  OK	| 

Signed-off-by: Abdelhamid Bakhta <abdelhamid.bakhta@consensys.net>

### CODE REVIEW

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java [hunk 1]
```diff
@@ -0,0 +1,235 @@
...
+@RunWith(Parameterized.class)
+public class EIP2124Test {
+  private static final Logger LOG = LogManager.getLogger();
+
+  @Parameters(name = "{index}: {0}")
+  public static Collection<Object[]> data() {
+    return Arrays.asList(
+        new Object[][] {
+          // Mainnet test cases
+          {"Mainnet // First Homestead block", Network.MAINNET, 1150000L, "0x97c2c34c", 1920000L},
```
Comment (shemnon) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java:48]: This feels like a lot of duplication with ` org.hyperledger.besu.ethereum.eth.manager.ForkIdManagerTest` - What is being tested here that is not being tested there and can these two files be merged into one?

Comment (abdelhamidbakhta) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java:48]: They don't exactly test the same things. The new test class `EIP2124Test` is focused on testing the fork id sent in P2P status messages. It also performs the assertions on multiple combinations of chain heights. The `ForkIdManagerTest` is focus on testing the intermediate fork hashes generated to perform the peer check. I think they have different scopes of responsibilities. I would keep them both. Moreover, the new test class cases are aligned with some tests in the EIP specification and also the implementation of other clients.

Comment (abdelhamidbakhta) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java:48]: Simply put: `ForkIdManagerTest` tests the behaviour of `peerCheck` method whereas `EIP2124Test` tests the behaviour of `computeForkId` method used by `EthProtocolManager`.

Comment (abdelhamidbakhta) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java:48]: Are you ok if i keep both files ?

Comment (shemnon) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java:48]: There's too much duplication.  They are testing two things in the same java file, so they should at least be in the same file.  Also, the data sets (what the fork IDs of the well known networks are) should be normalized into one data set.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 2]
```diff
@@ -66,12 +69,41 @@ public ForkIdManager(final Blockchain blockchain, final List<Long> forks) {
...
+        continue;
+      }
+      next = fork;
+      break;
+    }
+    lastComputedForkId = new ForkId(getCurrentCrcHash(crc), next);
+    return lastComputedForkId;
+  }
+
+  ForkId getLatestForkId() {
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:100]: Is this just for testing?

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 3]
```diff
@@ -40,23 +41,25 @@
...
     checkNotNull(forks);
+    this.chainHeadSupplier = blockchain::getChainHeadBlockNumber;
     this.genesisHash = blockchain.getGenesisBlock().getHash();
     this.forkAndHashList = new ArrayList<>();
+    this.forks =
+        forks.stream()
+            .filter(fork -> fork > 0)
+            .distinct()
+            .sorted()
+            .collect(Collectors.toUnmodifiableList());
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:60]: Since `forks` doesn't include 0, `onlyZerosForkBlocks` is not doing what it looks like it's doing. As it happens, it will be true because `allMatch` is true for empty but it's pretty misleading right now.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 4]
```diff
@@ -40,23 +41,25 @@
...
-            blockchain,
-            genesisHash,
-            forks,
-            fs ->
-                fs.stream()
-                    .filter(fork -> fork > 0)
-                    .distinct()
-                    .collect(Collectors.toUnmodifiableList()),
-            forkAndHashList);
+        createForkIDChecker(blockchain, genesisHash, forks, fs -> forks, forkAndHashList);
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:62]: If this isn't used anywhere else, we should probably move it into the else clause.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 5]
```diff
@@ -205,16 +230,20 @@ private static long createForkIds(
     final CRC32 crc = new CRC32();
     crc.update(genesisHash.toArray());
     final List<Bytes> forkHashes = new ArrayList<>(List.of(getCurrentCrcHash(crc)));
-    for (final Long fork : forks) {
-      updateCrc(crc, fork);
-      forkHashes.add(getCurrentCrcHash(crc));
-    }
+    final List<Long> filteredForks =
+        forks.stream().filter(v -> v > 0).distinct().collect(Collectors.toUnmodifiableList());
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:234]: Do we need this filter as well? I thought we already got rid of the 0's above. If it does break when this is removed, I wonder if there's a way we can do this filter in only one place.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 6]
```diff
@@ -205,16 +230,20 @@ private static long createForkIds(
...
-      forkIds.add(new ForkId(forkHashes.get(i), forks.get(i)));
+    for (int i = 0; i < filteredForks.size(); i++) {
+      forkIds.add(new ForkId(forkHashes.get(i), filteredForks.get(i)));
     }
     long forkNext = 0;
-    if (!forks.isEmpty()) {
+    if (!filteredForks.isEmpty()) {
       forkNext = forkIds.get(forkIds.size() - 1).getNext();
       forkIds.add(new ForkId(forkHashes.get(forkHashes.size() - 1), 0));
     }
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:249]: Can we reuse the `getLatestForkId` here?

Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:249]: Can't really unless i move everything from static methods to instance methods

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java (hunk 2 above)
Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:100]: Yes. Added `@VisibleForTesting` annotation.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java (hunk 3 above)
Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:60]: Fixed.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java (hunk 6 above)
Comment (RatanRSur) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:249]: ahh ok

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java (hunk 5 above)
Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:234]: Fixed.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java (hunk 4 above)
Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:62]: Non relevant anymore.

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java (hunk 1 above)
Comment (sambacha) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java]: It is not a well-documented feature in the genesis configuration that this can occur. Esp. with EthProtocolManager handshake as that has been a worry for us.

Comment (abdelhamidbakhta) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java]: I refactored both the implementation and the testing.

Comment (abdelhamidbakhta) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java]: And tested on almost all Ethereum networks, including consortium networks.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java [hunk 7]
```diff
@@ -39,69 +36,58 @@
...
+    for (final Long fork : forks) {
+      if (fork <= head) {
+        updateCrc(crc, fork);
+        continue;
+      }
+      next = fork;
+      break;
+    }
+    lastComputedForkId = new ForkId(getCurrentCrcHash(crc), next);
+    return lastComputedForkId;
```
Comment (RatanRSur) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:83]: Is there a way to get this from the `forkAndHashList`? If I understand correctly we just need to filter out the hashes that are for forks past the chain head, right?

Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:83]: Maybe we can. Let me check.

Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java:83]: Well. We can

Comment (abdelhamidbakhta) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java]: Fixed here https://github.com/hyperledger/besu/pull/1050/commits/db09f7677652d3ad561b2f78746b98e796f277ad

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkId.java [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+  Bytes forkIdRLP;
+
+  protected ForkId(final Bytes hash, final Bytes next) {
+    this.hash = hash;
+    this.next = next;
+    createForkIdRLP();
+  }
+
+  public ForkId(final Bytes hash, final long next) {
+    this(hash, Bytes.wrap(EndianUtils.longToBigEndian(next)).trimLeadingZeros());
```
Comment (shemnon) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkId.java:39]: nit: `java.lang.Long#reverseBytes` is quicker and hotspot compiles faster.

File: util/src/main/java/org/hyperledger/besu/util/EndianUtils.java [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
+ * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
+ * specific language governing permissions and limitations under the License.
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+package org.hyperledger.besu.util;
+
+public class EndianUtils {
```
Comment (shemnon) [inline util/src/main/java/org/hyperledger/besu/util/EndianUtils.java:17]: nit: we don't need this.  `Integer` and `Long` both have `reerseBytes` that can do this as HotSpot 'Intrinsic' methods, which means it goes straight to ASM when JITed.

**Comment by RatanRSur** [comment]
Mainly just read the code. Didn't run the tests locally as that would be enforced.
