### PR TITLE
use tmp dir for --data-path in BesuCommand tests

### LINKED ISSUE #9313: flaky test: CLI Options test
Sometimes CLI Options tests have a [failure](https://github.com/hyperledger/besu/actions/runs/18488059153/job/52675394377?pr=9303) that looks like

```
NetworkingOptionsTest > getCLIOptions_default() FAILED
    java.lang.AssertionError at AbstractCLIOptionsTest.java:76
```

Downloading the test report, the full error is:

```
java.lang.AssertionError: 
Expecting empty but was: "Invalid metadata file /home/runner/work/besu/besu/app/build/data/VERSION_METADATA.json
```

I guess it's a concurrency issue with multiple tests reading/writing the same version metadata file

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
## PR description
Modified abstract test class to add --data-path if not already present
* exclude tests that use config file since this could contain data-path

## Fixed Issue(s)
Fixes #9313

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] spotless: `./gradlew spotlessApply`
- [x] unit tests: `./gradlew build`
- [x] acceptance tests: `./gradlew acceptanceTest`
- [x] integration tests: `./gradlew integrationTest`
- [x] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

File: app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java [hunk 1]
```diff
@@ -464,14 +465,39 @@ protected TestBesuCommand parseCommand(
...
+    if (isMainCommand && !hasDataPath && !hasConfigFile) {
+      try {
+        final Path tmpDir = Files.createTempDirectory("besu-test-");
+        tmpDir.toFile().deleteOnExit();
+        argsList.add(0, "--data-path");
+        argsList.add(1, tmpDir.toString());
+      } catch (IOException e) {
+        throw new RuntimeException("Failed to create temporary directory", e);
+      }
+    }
```
Comment (siladu) [inline app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: nit: Think it's worth extracting this to a method.

File: app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java [hunk 2]
```diff
@@ -464,14 +465,39 @@ protected TestBesuCommand parseCommand(
...
-    // parse using Ansi.OFF to be able to assert on non formatted output results
+    // if data-path is not set and this is not a subcommand, set to a tmp dir
+    final List<String> argsList = new ArrayList<>(Arrays.asList(args));
+
+    // could add in more subcommands here but this is the only one where parsing args in tests
+    // currently needs this
+    boolean isTrieLogSubcommand = argsList.stream().anyMatch(arg -> arg.equals("trie-log"));
+
+    // If first arg starts with "-" or args is empty, it's likely main command
+    boolean isMainCommand = !isTrieLogSubcommand && (args.length == 0 || args[0].startsWith("-"));
```
Comment (siladu) [inline app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: This is pretty fuzzy - is there not a better way to work out we're the main command... parentCommand == null or something perhaps?

File: app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java [hunk 3]
```diff
@@ -464,14 +465,39 @@ protected TestBesuCommand parseCommand(
...
+
+    boolean hasDataPath = argsList.stream().anyMatch(arg -> arg.contains("data-path"));
+
+    boolean hasConfigFile = argsList.stream().anyMatch(arg -> arg.contains("config-file"));
```
Comment (siladu) [inline app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java:504]: What happens if the test has a config-file but that doesn't have a data-path set?

Comment (macfarla) [reply app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java:504]: it will use the default data-path - something like `/home/runner/work/besu/besu/app/build/data/`

Comment (macfarla) [reply app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java:504]: think there's only one test using config-file atm so chances of that still causing flaking are minimal

File: app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java (hunk 2 above)
Comment (macfarla) [reply app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: not really because that only happens after the args are parsed

File: app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java [hunk 4]
```diff
@@ -464,17 +466,48 @@ protected TestBesuCommand parseCommand(
...
         besuCommand.executionExceptionHandler(),
         in,
         mockBesuComponent,
-        args);
+        argsList.toArray(new String[0]));
     return besuCommand;
   }
 
+  @NotNull
+  private static List<String> constructArgsWithDataPathIfNotSpecified(String[] args) {
```
Comment (siladu) [inline app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]:
```suggestion
  private static List<String> constructArgsWithTmpDataPathIfNotSpecified(String[] args) {
```

Comment (siladu) [reply app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: nit ^

File: app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java (hunk 2 above)
Comment (macfarla) [reply app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: not needed since prepending data-path args to the beginning

File: app/src/main/java/org/hyperledger/besu/cli/BesuCommand.java [hunk 5]
```diff
@@ -771,16 +771,6 @@ protected BesuCommand(
     this.transactionValidatorServiceImpl = transactionValidatorServiceImpl;
   }
 
-  /**
-   * Parse Besu command line arguments. Visible for testing.
```
Comment (siladu) [inline app/src/main/java/org/hyperledger/besu/cli/BesuCommand.java:775]: Maybe could use `@VisibleForTesting` is that's the case?

File: app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java [hunk 6]
```diff
@@ -464,17 +466,43 @@ protected TestBesuCommand parseCommand(
...
+        argsList.toArray(new String[0]));
     return besuCommand;
   }
 
+  @Nonnull
+  private static List<String> constructArgsWithDataPathIfNotSpecified(final String[] args) {
+    final List<String> argsList = new ArrayList<>(Arrays.asList(args));
+
+    // If first arg starts with "-" or args is empty, it's likely main command
+    boolean isMainCommand = args.length == 0 || args[0].startsWith("-");
```
Comment (siladu) [inline app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: Do we still need this?

Comment (macfarla) [reply app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: PublicKeySubCommandTest needs more work if we don't have this

Comment (siladu) [reply app/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java]: I think the simplicity of applying to all subcommands here is worth making a special case out of PublicKeySubCommandTest
