### PR TITLE
Devnet-5: bug fixes for 7702

### LINKED ISSUE #8147: Fix failing 7702 test for devnet-5

### PR DESCRIPTION
**Pull request by daniellehrner**
## PR description

* fix code hash for delegated accounts in ExtCodeHashOperation
* move common code to AbstractExtCodeOperation class

## Fixed Issue(s)
fixes #8147 

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by siladu — APPROVED** [review]
LGTM

File: ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/CodeDelegationProcessorTest.java [hunk 1]
```diff
@@ -47,7 +47,7 @@ class CodeDelegationProcessorTest {
 
   @Mock private Transaction transaction;
 
-  @Mock private DelegatedCodeService authorizedCodeService;
+  @Mock private CodeDelegationService authorizedCodeService;
```
Comment (siladu) [inline ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/CodeDelegationProcessorTest.java:50]:
```suggestion
  @Mock private CodeDelegationService delegationCodeService;
```

File: evm/src/main/java/org/hyperledger/besu/evm/account/Account.java [hunk 2]
```diff
@@ -66,7 +66,7 @@ default Optional<Address> delegatedCodeAddress() {
    *
    * @return true if the account has delegated code otherwise false.
    */
-  default boolean hasDelegatedCode() {
+  default boolean hasCodeDelegation() {
```
Comment (siladu) [inline evm/src/main/java/org/hyperledger/besu/evm/account/Account.java:69]: very much a nit pick: I think I actually prefer hasDelegatedCode in this case, since it is clear the code is actually delegated. `hasCodeDelegation` could be read as "has code delegation feature but maybe it's not currently delegated"

File: evm/src/main/java/org/hyperledger/besu/evm/account/AccountState.java [hunk 3]
```diff
@@ -78,9 +78,9 @@ public interface AccountState {
   /**
    * The optional EVM bytecode if the account has set a 7702 code delegation.
    *
-   * @return the delegated code (which may be empty).
+   * @return the code of the target account (which may be empty).
```
Comment (siladu) [inline evm/src/main/java/org/hyperledger/besu/evm/account/AccountState.java:81]:
```suggestion
   * @return the code of the target account that this account delegates to (which may be empty).
```

...checking my understanding

**Review by siladu — APPROVED** [review]
