### PR TITLE
Ignore gasPrice if 1559 gas params are specified

### LINKED ISSUE #8055: `eth_createAccessList` should gracefully handle multiple gas params
Bug reported by ethPandaOps testing besu/teku via kurtosis - 

```
[el-1-besu-teku] 2024-12-19 09:26:12.788+00:00 | vert.x-worker-thread-5 | DEBUG | BaseJsonRpcProcessor | Invalid Params for method: eth_createAccessList, error: Invalid gas price params
[el-1-besu-teku] org.hyperledger.besu.ethereum.api.jsonrpc.internal.exception.InvalidJsonRpcParameters: gasPrice cannot be used with maxFeePerGas or maxPriorityFeePerGas
[19:30]parithosh: Seems like besu closes all json rpc connections after this, meaning the engine API isnt able to receive messages -> CL thinks EL is offline -> missed slots 
```

So root cause is in the besu bug linked above. The behavior IMO is wrong, this shouldn't trigger a RPC failure, but instead just gracefully error out.

### Steps to Reproduce

1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Logs
Please post relevant logs from Besu (and the consensus client, if running proof of stake) from before and after the issue.

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]
* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
* System info - memory, CPU

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>

## PR description
Previously we were returning an error response if gasPrice was specified along with maxFeePerGas or maxPriorityFeePerGas. 
This PR modifies that to accept requests that specify both (legacy and 1559) types of gas pricing params.

No change made to the TransactionSimulator as it uses the 1559 values if they are present, so in this case gasPrice is effectively ignored. 

Also added some logging for parameters if there is an InvalidJsonRpcParameters exception

This affects
* eth_call
* eth_estimateGas
* eth_createAccessList

## Fixed Issue(s)
fixes #8055 

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by siladu — APPROVED** [review]
LGTM

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/JsonCallParameterUtil.java [hunk 1]
```diff
@@ -36,9 +42,14 @@ public static JsonCallParameter validateAndGetCallParams(final JsonRpcRequestCon
     if (callParams.getGasPrice() != null
         && (callParams.getMaxFeePerGas().isPresent()
             || callParams.getMaxPriorityFeePerGas().isPresent())) {
-      throw new InvalidJsonRpcParameters(
-          "gasPrice cannot be used with maxFeePerGas or maxPriorityFeePerGas",
-          RpcErrorType.INVALID_GAS_PRICE_PARAMS);
+      try {
+        LOG.warn(
```
Comment (macfarla) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/JsonCallParameterUtil.java:46]: @siladu do you think this log will be too spammy?

**Review by jframe — APPROVED** [review]
LGTM

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/JsonCallParameterUtil.java (hunk 1 above)
Comment (siladu) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/JsonCallParameterUtil.java:46]: hmmm good point maybe is, happy to switch to debug for now to avoid devnet noise.
