### PR TITLE
Fix empty body concept after shanghai

### LINKED ISSUE #4976: Withdrawals to handle filling empty blocks when syncing
The empty block check is missing checking the withdrawals in the CompleteBlocksTask hasEmptyBody method. Not sure if this is necessary, we need to understand more about what this class is doing but we need to consider withdrawals here as well.

### PR DESCRIPTION
**Pull request by gfukushima**
## PR description
This PR adds withdrawals to the method that checks for empty block bodies in CompleteBlocksTask.java
Adding withdrawals allows Besu to be able to distinguish empty blocks after shanghai skiping the block body download when body is empty.
Prior to this PR Besu would understand blocks like (0txs, 0 ommers, x ws) as an empty block, during the sync process. (x > 0)

## Fixed Issue(s)

Fixes #4976 

This PR has performed the following tests:
- [x] Recreated and tested fix on zhejiang-testnet using FAST sync
- [x] Successfully synced Sepolia (starting from checkpoint and transitioning to Shanghai)
- [x] Successfully synced Goerli 
- [ ] Successfully synced Mainnet
 
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Acceptance Tests (Non Mainnet)

- [x] I have considered running `./gradlew acceptanceTestNonMainnet` locally if my PR affects non-mainnet modules.

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java [hunk 1]
```diff
@@ -79,7 +79,11 @@ private CompleteBlocksTask(
 
   private boolean hasEmptyBody(final BlockHeader header) {
     return header.getOmmersHash().equals(Hash.EMPTY_LIST_HASH)
-        && header.getTransactionsRoot().equals(Hash.EMPTY_TRIE_HASH);
+        && header.getTransactionsRoot().equals(Hash.EMPTY_TRIE_HASH)
+        && header
+            .getWithdrawalsRoot()
```
[the remark this answers is not in the document]
Comment (garyschulte) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java:84]: does it though?  if withdrawals are not enabled wouldn't we get an empty Optional?  This looks correct to me.  

I presume we already have test coverage that asserts we will fail a block that tries to execute withdrawals before shanghai.

[the remark this answers is not in the document]
Comment (siladu) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java:84]: We discussed on a call. Decided it wasn't needed due to later validation as you say, but we do need to check the protocolSchedule for if withdrawals is enabled to be able to create a withdrawals-aware empty block. That changes and unit tests incoming

[the remark this answers is not in the document]
Comment (jframe) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java:84]: Yeah it didn't look right when I first looked at it. But we had a closer look at your right we don't need to do that check here as the validation will take care of that. It would be moving some of the validation into the class which isn't right.

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java [hunk 2]
```diff
@@ -79,7 +79,11 @@ private CompleteBlocksTask(
```
Comment (jframe) [inline ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java:79]: The constructor needs to correct a block body with an empty list of withdrawals when there is an empty block Shanghai. This always creates a block body with an empty optional which is incorrect post-shanghai.

Comment (gfukushima) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java:79]: Yes, we've changed the implementation to take protocolSchedule into account for the empty body creation Will push that change soon. Thanks!

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java [hunk 3]
```diff
@@ -79,6 +95,115 @@ public void shouldCompleteWithoutPeersWhenAllBlocksAreEmpty() {
...
+            mockProtocolSchedule,
+            ethContext,
+            List.of(header1, header2),
+            maxRetries,
+            new NoOpMetricsSystem());
+    assertThat(task.run()).isCompletedWithValue(expectedBlocks);
+  }
+
+  @Test
+  public void shouldCompleteWhenBlocksAreEmptyExceptForWithdrawals() {
```
Comment (jframe) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:138]: Is this testing that when blocks are empty but have withdrawals they are still downloaded? i.e. that they are considered empty blocks. Was a bit confused from the test name

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java [hunk 4]
```diff
@@ -79,6 +95,115 @@ public void shouldCompleteWithoutPeersWhenAllBlocksAreEmpty() {
...
+            secondWithdrawalsHeader,
+            new BlockBody(
+                Collections.emptyList(),
+                Collections.emptyList(),
+                Optional.of(Collections.emptyList())));
+    final List<Block> expected = asList(block1, block2, block3);
+
+    final RespondingEthPeer respondingPeer =
+        EthProtocolManagerTestUtil.createPeer(ethProtocolManager, 1000);
+    final RespondingEthPeer.Responder responder = responderForFakeBlocks(expected);
```
Comment (jframe) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:172]: Why does the responder need all the blocks? It should only need to download block2 as the others are empty

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java [hunk 5]
```diff
@@ -79,6 +95,115 @@ public void shouldCompleteWithoutPeersWhenAllBlocksAreEmpty() {
...
+    final List<Withdrawal> withdrawals = List.of(withdrawal);
+    final Hash withdrawalsRoot = BodyValidation.withdrawalsRoot(withdrawals);
+
+    final BlockHeader preWithdrawalsHeader = new BlockHeaderTestFixture().number(1).buildHeader();
+    final BlockHeader firstWithdrawalsHeader =
+        new BlockHeaderTestFixture().number(2).withdrawalsRoot(withdrawalsRoot).buildHeader();
+    final BlockHeader secondWithdrawalsHeader =
+        new BlockHeaderTestFixture().number(3).withdrawalsRoot(Hash.EMPTY_TRIE_HASH).buildHeader();
+
+    final Block block1 = new Block(preWithdrawalsHeader, BlockBody.empty());
```
Comment (jframe) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:155]: nit: rename to emptyBlock

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java [hunk 6]
```diff
@@ -79,6 +95,115 @@ public void shouldCompleteWithoutPeersWhenAllBlocksAreEmpty() {
...
+    final Block block2 =
+        new Block(
+            firstWithdrawalsHeader,
+            new BlockBody(
+                Collections.emptyList(), Collections.emptyList(), Optional.of(withdrawals)));
+    final Block block3 =
```
Comment (jframe) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:161]: nit: rename to empyWithdrawalsBlock?

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java [hunk 7]
```diff
@@ -79,6 +95,115 @@ public void shouldCompleteWithoutPeersWhenAllBlocksAreEmpty() {
...
+            List.of(preWithdrawalsHeader, firstWithdrawalsHeader, secondWithdrawalsHeader),
+            maxRetries,
+            new NoOpMetricsSystem());
+
+    final CompletableFuture<List<Block>> runningTask = task.run();
+
+    assertThat(runningTask).isNotDone();
+    respondingPeer.respond(responder);
+    assertThat(runningTask).isCompletedWithValue(expected);
+    //    assertThat(task.run()).isCompletedWithValue(expected);
```
Comment (jframe) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:195]: Left over from testing?

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java (hunk 4 above)
Comment (siladu) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:172]: it doesn't we thought it was a good test - e.g. let's say the code under test had a bug where it requested 3 blocks instead of 1, but we only ever returned one block in the responser, we wouldn't catch that.

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java (hunk 7 above)
Comment (siladu) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:195]: hmmm, wonder if @gfukushima didn't push the latest commit, I thought we removed that

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java (hunk 6 above)
Comment (siladu) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:161]: arguably some value in keeping header1, block1, blockNumber = 1 all in sync

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java (hunk 3 above)
Comment (siladu) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:138]: > Is this testing that when blocks are empty but have withdrawals they are still downloaded?
yes, i.e. that they are _not_ considered empty blocks like they were being before.

Any name suggestion? This was an modification of the existing test's name: `shouldCompleteWithoutPeersWhenAllBlocksAreEmpty`. Agree the new one could be better

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java (hunk 7 above)
Comment (gfukushima) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:195]: Good catch, thanks

File: ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java [hunk 8]
```diff
@@ -74,12 +75,32 @@ private CompleteBlocksTask(
...
+                    BlockHeader::getNumber,
+                    header ->
+                        new Block(
+                            header,
+                            new BlockBody(
+                                Collections.emptyList(),
+                                Collections.emptyList(),
+                                isWithdrawalsEnabled(protocolSchedule, header)
+                                    ? Optional.of(Collections.emptyList())
+                                    : Optional.empty()))));
```
[the remark this answers is not in the document]
Comment (gfukushima) [reply ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTask.java:89]: Done

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java (hunk 4 above)
Comment (gfukushima) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:172]: It does not, you're right, good catch!

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java [hunk 9]
```diff
@@ -79,6 +95,112 @@ public void shouldCompleteWithoutPeersWhenAllBlocksAreEmpty() {
     assertThat(task.run()).isCompletedWithValue(blocks);
   }
 
+  @Test
+  public void shouldCreateCorrectEmptyBlockWhenWithdrawalsAreEnabled() {
```
Comment (macfarla) [inline ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java:99]:
```suggestion
  public void whenWithdrawalsAreEnabled_shouldCreateEmptyBlockWithEmptyWithdrawalsList() {
```

**Review by macfarla — APPROVED** [review]
LGTM

File: ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java (hunk 9 above)
Comment (siladu) [reply ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/CompleteBlocksTaskTest.java]: Renamed both tests to be (hopefully) clearer and more consistent

**Review by jframe — APPROVED** [review]
