### PR TITLE
fix: debug_traceTransaction default param

### LINKED ISSUE #9787: debug_traceTransaction default param behavior
Passing no options vs passing an empty {} produces different behavior:
  
| Scenario                                           | traceMemory | traceStorage | traceStack |
|----------------------------------------------------|-------------|--------------|------------|
| debug_traceTransaction(hash) — no options          | false       | true         | true       |
| debug_traceTransaction(hash, {}) — empty options   | true        | true         | true       |
  
  The empty options case goes through TransactionTraceParams.traceOptions() which starts from OpCodeTracerConfig.DEFAULT but then blindly overrides with !disableMemory() where disableMemory() returns false for a missing field (null → false). So traceMemory flips from
  false to true.

  debug_traceTransaction(hash) and debug_traceTransaction(hash, {}) should be equivalent, but they're not — the empty object silently enables memory tracing, which is expensive.

  The fix would be in TransactionTraceParams.traceOptions() — only override a field when the nullable value is explicitly set:

```
  var builder = OpCodeTracerConfigBuilder.createFrom(OpCodeTracerConfig.DEFAULT);
  if (disableMemoryNullable() != null) {
      builder.traceMemory(!disableMemory());
  }
  if (disableStorageNullable() != null) {
      builder.traceStorage(!disableStorage());
  }
  if (disableStackNullable() != null) {
      builder.traceStack(!disableStack());
  }
```

### PR DESCRIPTION
**Pull request by macfarla**
## PR description
When reviewing [docs PR 1909](https://github.com/hyperledger/besu-docs/pull/1909), claude picked up an inconsistency with default parameters when no params are supplied vs empty {} params - as described in #9787 

Docs still needs correcting here to say disableMemory is true by default (all other booleans default to false)  https://besu.hyperledger.org/public-networks/reference/api#debug_tracetransaction 

## Fixed Issue(s)

fixes #9787 

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] spotless: `./gradlew spotlessApply`
- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`
- [ ] hive tests: [Engine or other RPCs modified?](https://lf-hyperledger.atlassian.net/wiki/spaces/BESU/pages/22156302/Using+Hive+Test+Suite)

### CODE REVIEW

**Comment by macfarla** [comment]
@lu-pinto can you review this one - the default param behavior is currently inconsistent between RPCs -  this came up from looking at a docs PR https://github.com/hyperledger/besu-docs/pull/1909 - in one spot we say the trace flags are all false by default but looking at the code that's not the case, and actually you currently get different behavior between passing no options and empty {} options

File: ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TransactionTraceParams.java [hunk 1]
```diff
@@ -97,20 +97,29 @@ default Set<String> opcodes() {
...
+      builder.traceMemory(!disableMemory());
+    } else if (tracerType != TracerType.OPCODE_TRACER) {
+      // Non-opcode tracers (e.g. callTracer) need memory capture enabled for internal
+      // operations such as extracting CREATE init code, even when disableMemory is not set
+      builder.traceMemory(true);
+    }
+    if (disableStackNullable() != null) {
+      builder.traceStack(!disableStack());
+    }
+    var defaultTracerConfig = builder.traceOpcodes(opcodes()).build();
```
Comment (lu-pinto) [inline ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TransactionTraceParams.java]: nit: I know this was like this before but this name `defaultTracerConfig` could be misleading. At this stage these option are not default anymore, they are a mix of user set params and defaults, so probably would just call it `tracerConfig`

Comment (macfarla) [reply ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TransactionTraceParams.java]: done
